-- file CreateDbsWdbeMy.sql
-- MySQL / MariaDB database create script
-- copyright: (C) 2016-2020 MPSI Technologies GmbH
-- author: Alexander Wirthmueller (auto-generation)
-- date created: 7 Feb 2024
-- IP header --- ABOVE

DROP DATABASE IF EXISTS DbsWdbe;
CREATE DATABASE DbsWdbe;
USE DbsWdbe;

CREATE USER IF NOT EXISTS 'default'@'%' IDENTIFIED BY 'asdf1234';
GRANT ALL PRIVILEGES ON DbsWdbe.* TO 'default'@'%';

CREATE USER IF NOT EXISTS 'default'@'localhost' IDENTIFIED BY 'asdf1234';
GRANT ALL PRIVILEGES ON DbsWdbe.* TO 'default'@'localhost';

CREATE TABLE TblWdbeAccRMUserUniversal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUser BIGINT UNSIGNED,
	unvIxWdbeVMaintable INT UNSIGNED,
	unvUref BIGINT UNSIGNED,
	ixWdbeVRecaccess INT UNSIGNED,
	INDEX (refWdbeMUser),
	INDEX (unvIxWdbeVMaintable),
	INDEX (unvUref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAMCommandInvpar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	cmdRefWdbeMCommand BIGINT UNSIGNED,
	cmdNum INT UNSIGNED,
	sref VARCHAR(50),
	ixWdbeVPartype INT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	Length TINYINT UNSIGNED,
	Defval TEXT,
	refWdbeMVectoritem BIGINT UNSIGNED,
	Comment TEXT,
	INDEX (cmdRefWdbeMCommand),
	INDEX (cmdNum),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAMCommandRetpar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	cmdRefWdbeMCommand BIGINT UNSIGNED,
	cmdNum INT UNSIGNED,
	sref VARCHAR(50),
	ixWdbeVPartype INT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	Length TINYINT UNSIGNED,
	Comment TEXT,
	INDEX (cmdRefWdbeMCommand),
	INDEX (cmdNum),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAMCoreversionIp(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	cvrRefWdbeMCoreversion BIGINT UNSIGNED,
	cvrNum INT UNSIGNED,
	sref VARCHAR(50),
	ixVTagtype INT UNSIGNED,
	Comment TEXT,
	INDEX (cvrRefWdbeMCoreversion),
	INDEX (cvrNum),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAMCoreversionPlh(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	cvrRefWdbeMCoreversion BIGINT UNSIGNED,
	cvrNum INT UNSIGNED,
	sref VARCHAR(50),
	Comment TEXT,
	INDEX (cvrRefWdbeMCoreversion),
	INDEX (cvrNum),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAMErrorPar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	errRefWdbeMError BIGINT UNSIGNED,
	errNum INT UNSIGNED,
	sref VARCHAR(50),
	ixWdbeVPartype INT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	Length TINYINT UNSIGNED,
	Comment TEXT,
	INDEX (errRefWdbeMError),
	INDEX (errNum),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAMFsmstateStep(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	fstRefWdbeMFsmstate BIGINT UNSIGNED,
	fstNum INT UNSIGNED,
	fnxRefWdbeMFsmstate BIGINT UNSIGNED,
	Cond1 TEXT,
	Ip1 VARCHAR(50),
	Cond2 TEXT,
	Ip2 VARCHAR(50),
	Cond3 TEXT,
	Ip3 VARCHAR(50),
	Cond4 TEXT,
	Ip4 VARCHAR(50),
	Cond5 TEXT,
	Ip5 VARCHAR(50),
	Cond6 TEXT,
	Ip6 VARCHAR(50),
	INDEX (fstRefWdbeMFsmstate),
	INDEX (fstNum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAMLibraryMakefile(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMLibrary BIGINT UNSIGNED,
	x1RefWdbeMMachine BIGINT UNSIGNED,
	x2SrefKTag VARCHAR(50),
	Val TEXT,
	INDEX (refWdbeMLibrary),
	INDEX (x1RefWdbeMMachine),
	INDEX (x2SrefKTag)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAMMachineMakefile(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMMachine BIGINT UNSIGNED,
	x1SrefKTag VARCHAR(50),
	Val TEXT,
	INDEX (refWdbeMMachine),
	INDEX (x1SrefKTag)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAMMachinePar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMMachine BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (refWdbeMMachine),
	INDEX (x1SrefKKey)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAMModulePar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	mdlRefWdbeMModule BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (mdlRefWdbeMModule),
	INDEX (mdlNum),
	INDEX (x1SrefKKey)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAMPeripheralPar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMPeripheral BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (refWdbeMPeripheral),
	INDEX (x1SrefKKey)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAMPersonDetail(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMPerson BIGINT UNSIGNED,
	x1SrefKType VARCHAR(50),
	Val VARCHAR(192),
	INDEX (refWdbeMPerson)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAMPinPar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMPin BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (refWdbeMPin),
	INDEX (x1SrefKKey)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAMUserAccess(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUser BIGINT UNSIGNED,
	x1IxWdbeVFeatgroup INT UNSIGNED,
	x2FeaSrefUix VARCHAR(50),
	ixWdbeWAccess INT UNSIGNED,
	INDEX (refWdbeMUser),
	INDEX (x1IxWdbeVFeatgroup),
	INDEX (x2FeaSrefUix)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAMUsergroupAccess(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUsergroup BIGINT UNSIGNED,
	x1IxWdbeVFeatgroup INT UNSIGNED,
	x2FeaSrefUix VARCHAR(50),
	ixWdbeWAccess INT UNSIGNED,
	INDEX (refWdbeMUsergroup),
	INDEX (x1IxWdbeVFeatgroup),
	INDEX (x2FeaSrefUix)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAVControlPar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixWdbeVControl INT UNSIGNED,
	x1RefWdbeMUser BIGINT UNSIGNED,
	x2IxWdbeVLocale INT UNSIGNED,
	Par VARCHAR(192),
	Val VARCHAR(192),
	INDEX (ixWdbeVControl),
	INDEX (x1RefWdbeMUser),
	INDEX (x2IxWdbeVLocale),
	INDEX (Par)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAVKeylistKey(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	klsIxWdbeVKeylist INT UNSIGNED,
	klsNum INT UNSIGNED,
	x1IxWdbeVMaintable INT UNSIGNED,
	x1Uref BIGINT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(1024),
	Implied VARCHAR(1024),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (klsIxWdbeVKeylist),
	INDEX (klsNum),
	INDEX (x1IxWdbeVMaintable),
	INDEX (x1Uref),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeAVValuelistVal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	vlsIxWdbeVValuelist INT UNSIGNED,
	vlsNum INT UNSIGNED,
	x1IxWdbeVLocale INT UNSIGNED,
	Val VARCHAR(192),
	INDEX (vlsIxWdbeVValuelist),
	INDEX (vlsNum),
	INDEX (x1IxWdbeVLocale)
) ENGINE = ARIA;

CREATE TABLE TblWdbeCFile(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = ARIA;

CREATE TABLE TblWdbeCFsmstate(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = ARIA;

CREATE TABLE TblWdbeCGeneric(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = ARIA;

CREATE TABLE TblWdbeCPin(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = ARIA;

CREATE TABLE TblWdbeCPort(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = ARIA;

CREATE TABLE TblWdbeCSegment(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = ARIA;

CREATE TABLE TblWdbeCSignal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = ARIA;

CREATE TABLE TblWdbeCVariable(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = ARIA;

CREATE TABLE TblWdbeHistRMUserUniversal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUser BIGINT UNSIGNED,
	unvIxWdbeVMaintable INT UNSIGNED,
	unvUref BIGINT UNSIGNED,
	ixWdbeVCard INT UNSIGNED,
	ixWdbeVPreset INT UNSIGNED,
	preIxWdbeVMaintable INT UNSIGNED,
	preUref BIGINT UNSIGNED,
	start INT UNSIGNED,
	INDEX (refWdbeMUser),
	INDEX (unvIxWdbeVMaintable),
	INDEX (unvUref),
	INDEX (ixWdbeVCard),
	INDEX (ixWdbeVPreset),
	INDEX (preIxWdbeVMaintable),
	INDEX (preUref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeJAVKeylistKey(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeAVKeylistKey BIGINT UNSIGNED,
	x1IxWdbeVLocale INT UNSIGNED,
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (refWdbeAVKeylistKey),
	INDEX (x1IxWdbeVLocale)
) ENGINE = ARIA;

CREATE TABLE TblWdbeJMCoreversionState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMCoreversion BIGINT UNSIGNED,
	x1Start INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refWdbeMCoreversion),
	INDEX (x1Start)
) ENGINE = ARIA;

CREATE TABLE TblWdbeJMPersonLastname(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMPerson BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	Lastname VARCHAR(50),
	INDEX (refWdbeMPerson),
	INDEX (x1Startd),
	INDEX (Lastname)
) ENGINE = ARIA;

CREATE TABLE TblWdbeJMPinSref(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMPin BIGINT UNSIGNED,
	x1RefWdbeMPeripheral BIGINT UNSIGNED,
	sref VARCHAR(50),
	INDEX (refWdbeMPin),
	INDEX (x1RefWdbeMPeripheral),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeJMUserState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUser BIGINT UNSIGNED,
	x1Start INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refWdbeMUser),
	INDEX (x1Start)
) ENGINE = ARIA;

CREATE TABLE TblWdbeJMVersionState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMVersion BIGINT UNSIGNED,
	x1Start INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refWdbeMVersion),
	INDEX (x1Start)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMBank(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUnit BIGINT UNSIGNED,
	sref VARCHAR(50),
	srefKVoltstd VARCHAR(50),
	INDEX (refWdbeMUnit),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMCdc(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMModule BIGINT UNSIGNED,
	fckSrefWdbeMSignal VARCHAR(50),
	farSrefWdbeMSignal VARCHAR(50),
	sckSrefWdbeMSignal VARCHAR(50),
	sarSrefWdbeMSignal VARCHAR(50),
	Ratio DOUBLE,
	INDEX (refWdbeMModule)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMCommand(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	sref VARCHAR(50),
	Fullsref VARCHAR(50),
	ixVRettype INT UNSIGNED,
	ivrRefWdbeMSignal BIGINT UNSIGNED,
	rvrRefWdbeMSignal BIGINT UNSIGNED,
	rerRefWdbeMSignal BIGINT UNSIGNED,
	Comment TEXT,
	INDEX (refIxVTbl),
	INDEX (refUref),
	INDEX (refNum),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMComponent(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixVBasetype INT UNSIGNED,
	refWdbeMVersion BIGINT UNSIGNED,
	sref VARCHAR(50),
	Comment TEXT,
	INDEX (ixVBasetype),
	INDEX (refWdbeMVersion),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMController(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMModule BIGINT UNSIGNED,
	Fullsref VARCHAR(50),
	clrRefWdbeMSignal BIGINT UNSIGNED,
	INDEX (refWdbeMModule)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMCoreproject(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	ixVBasetype INT UNSIGNED,
	refWdbeMCoreversion BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(50),
	Giturl VARCHAR(192),
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (ixVBasetype),
	INDEX (refWdbeMCoreversion),
	INDEX (sref),
	INDEX (Title)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMCoreversion(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refWdbeMCoreproject BIGINT UNSIGNED,
	bcvRefWdbeMCoreversion BIGINT UNSIGNED,
	refWdbeMModule BIGINT UNSIGNED,
	Major SMALLINT UNSIGNED,
	Minor SMALLINT UNSIGNED,
	Sub SMALLINT UNSIGNED,
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	ixWSpectype INT UNSIGNED,
	INDEX (grp),
	INDEX (own),
	INDEX (refWdbeMCoreproject),
	INDEX (bcvRefWdbeMCoreversion),
	INDEX (refWdbeMModule),
	INDEX (ixVState)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMError(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	sref VARCHAR(50),
	Fullsref VARCHAR(50),
	traRefWdbeMSignal BIGINT UNSIGNED,
	Comment TEXT,
	INDEX (refIxVTbl),
	INDEX (refUref),
	INDEX (refNum),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMFamily(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	srefWdbeKVendor VARCHAR(50),
	Title VARCHAR(50),
	Comment TEXT,
	INDEX (srefWdbeKVendor),
	INDEX (Title)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMFile(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refWdbeCFile BIGINT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	osrefKContent VARCHAR(50),
	Archived INT UNSIGNED,
	Filename VARCHAR(50),
	Archivename VARCHAR(30),
	srefKMimetype VARCHAR(50),
	Size SMALLINT UNSIGNED,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refWdbeCFile),
	INDEX (refIxVTbl),
	INDEX (refUref),
	INDEX (Filename)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMFsm(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMProcess BIGINT UNSIGNED,
	ixVDbgtaptype INT UNSIGNED,
	INDEX (refWdbeMProcess)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMFsmstate(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeCFsmstate BIGINT UNSIGNED,
	fsmRefWdbeMFsm BIGINT UNSIGNED,
	fsmNum INT UNSIGNED,
	sref VARCHAR(50),
	Extip TINYINT,
	Comment TEXT,
	INDEX (refWdbeCFsmstate),
	INDEX (fsmRefWdbeMFsm),
	INDEX (fsmNum),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMGeneric(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeCGeneric BIGINT UNSIGNED,
	mdlRefWdbeMModule BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	sref VARCHAR(50),
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	Defval TEXT,
	srcSrefWdbeMGeneric VARCHAR(50),
	Comment TEXT,
	INDEX (refWdbeCGeneric),
	INDEX (mdlRefWdbeMModule),
	INDEX (mdlNum),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMImbuf(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixVRotype INT UNSIGNED,
	refWdbeMModule BIGINT UNSIGNED,
	Fullsref VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	Prio TINYINT UNSIGNED,
	INDEX (refWdbeMModule),
	INDEX (Prio)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMInterrupt(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUnit BIGINT UNSIGNED,
	sref VARCHAR(50),
	Comment TEXT,
	INDEX (refWdbeMUnit),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMLibrary(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	sref VARCHAR(50),
	Title VARCHAR(50),
	Version VARCHAR(30),
	depSrefsWdbeMLibrary VARCHAR(192),
	Comment TEXT,
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMMachine(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	supRefWdbeMMachine BIGINT UNSIGNED,
	sref VARCHAR(50),
	cchRefWdbeMMachine BIGINT UNSIGNED,
	Comment TEXT,
	INDEX (supRefWdbeMMachine),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMModule(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixVBasetype INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	hkNum INT UNSIGNED,
	supRefWdbeMModule BIGINT UNSIGNED,
	tplRefWdbeMModule BIGINT UNSIGNED,
	refWdbeMController BIGINT UNSIGNED,
	refWdbeMImbuf BIGINT UNSIGNED,
	sref VARCHAR(50),
	srefWdbeKVendor VARCHAR(50),
	Srefrule VARCHAR(192),
	Comment TEXT,
	INDEX (ixVBasetype),
	INDEX (hkIxVTbl),
	INDEX (hkUref),
	INDEX (hkNum),
	INDEX (supRefWdbeMModule),
	INDEX (tplRefWdbeMModule),
	INDEX (refWdbeMController),
	INDEX (refWdbeMImbuf),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMPeripheral(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUnit BIGINT UNSIGNED,
	sref VARCHAR(50),
	Comment TEXT,
	INDEX (refWdbeMUnit),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMPerson(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	ixWDerivate INT UNSIGNED,
	ixVSex INT UNSIGNED,
	Title VARCHAR(30),
	Firstname VARCHAR(30),
	refJLastname BIGINT UNSIGNED,
	Lastname VARCHAR(50),
	telRefADetail BIGINT UNSIGNED,
	telVal VARCHAR(192),
	emlRefADetail BIGINT UNSIGNED,
	emlVal VARCHAR(192),
	Salutation VARCHAR(100),
	INDEX (grp),
	INDEX (own),
	INDEX (ixWDerivate),
	INDEX (Lastname)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMPin(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeCPin BIGINT UNSIGNED,
	refWdbeMBank BIGINT UNSIGNED,
	refJSref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Location VARCHAR(5),
	INDEX (refWdbeCPin),
	INDEX (refWdbeMBank),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMPipeline(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	hsmRefWdbeMModule BIGINT UNSIGNED,
	sref VARCHAR(50),
	clkSrefWdbeMSignal VARCHAR(50),
	clgSrefWdbeMSignal VARCHAR(50),
	asrSrefWdbeMSignal VARCHAR(50),
	Depth SMALLINT UNSIGNED,
	Comment TEXT,
	INDEX (hsmRefWdbeMModule),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMPort(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeCPort BIGINT UNSIGNED,
	mdlRefWdbeMModule BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	mdlIxVCat INT UNSIGNED,
	sref VARCHAR(50),
	ixVDir INT UNSIGNED,
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	Defval TEXT,
	cpiSrefWdbeMPin VARCHAR(50),
	cprSrefWdbeMPort VARCHAR(50),
	csiSrefWdbeMSignal VARCHAR(50),
	Comment TEXT,
	INDEX (refWdbeCPort),
	INDEX (mdlRefWdbeMModule),
	INDEX (mdlNum),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMProcess(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMModule BIGINT UNSIGNED,
	refWdbeMFsm BIGINT UNSIGNED,
	sref VARCHAR(50),
	clkSrefWdbeMSignal VARCHAR(50),
	asrSrefWdbeMSignal VARCHAR(50),
	Falling TINYINT,
	Syncrst VARCHAR(192),
	Extip TINYINT,
	Comment TEXT,
	INDEX (refWdbeMModule),
	INDEX (refWdbeMFsm),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMProject(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refWdbeMVersion BIGINT UNSIGNED,
	Short VARCHAR(5),
	Title VARCHAR(50),
	Easy TINYINT,
	Giturl VARCHAR(192),
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refWdbeMVersion),
	INDEX (Short),
	INDEX (Title)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMRelease(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMComponent BIGINT UNSIGNED,
	refWdbeMMachine BIGINT UNSIGNED,
	sref VARCHAR(50),
	srefsKOption VARCHAR(192),
	Comment TEXT,
	INDEX (refWdbeMComponent),
	INDEX (refWdbeMMachine),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMSegment(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeCSegment BIGINT UNSIGNED,
	pplRefWdbeMPipeline BIGINT UNSIGNED,
	pplNum INT UNSIGNED,
	supRefWdbeMSegment BIGINT UNSIGNED,
	sref VARCHAR(50),
	Infmt VARCHAR(30),
	Outfmt VARCHAR(30),
	Latency SMALLINT UNSIGNED,
	Comment TEXT,
	INDEX (refWdbeCSegment),
	INDEX (pplRefWdbeMPipeline),
	INDEX (pplNum),
	INDEX (supRefWdbeMSegment),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMSensitivity(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	srcIxVTbl INT UNSIGNED,
	srcUref BIGINT UNSIGNED,
	INDEX (refIxVTbl),
	INDEX (refUref),
	INDEX (srcIxVTbl),
	INDEX (srcUref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMSession(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUser BIGINT UNSIGNED,
	start INT UNSIGNED,
	stop INT UNSIGNED,
	Ip VARCHAR(30),
	INDEX (refWdbeMUser),
	INDEX (start)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMSignal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixVBasetype INT UNSIGNED,
	refWdbeCSignal BIGINT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	mgeIxVTbl INT UNSIGNED,
	mgeUref BIGINT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	sref VARCHAR(50),
	Const TINYINT,
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	Comb VARCHAR(192),
	Onval TEXT,
	Offval TEXT,
	Defon TINYINT,
	drvRefWdbeMPort BIGINT UNSIGNED,
	Comment TEXT,
	INDEX (ixVBasetype),
	INDEX (refWdbeCSignal),
	INDEX (refIxVTbl),
	INDEX (refUref),
	INDEX (refNum),
	INDEX (mgeIxVTbl),
	INDEX (mgeUref),
	INDEX (refWdbeMVector),
	INDEX (sref),
	INDEX (Const)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMUnit(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixVBasetype INT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	silRefWdbeMUnit BIGINT UNSIGNED,
	refWdbeMModule BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(192),
	Fullsref VARCHAR(50),
	srefKPackage VARCHAR(50),
	Easy TINYINT,
	srefKToolch VARCHAR(50),
	Comment TEXT,
	INDEX (ixVBasetype),
	INDEX (refIxVTbl),
	INDEX (refUref),
	INDEX (silRefWdbeMUnit),
	INDEX (refWdbeMModule),
	INDEX (sref),
	INDEX (Title)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMUser(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refRUsergroup BIGINT UNSIGNED,
	refWdbeMUsergroup BIGINT UNSIGNED,
	refWdbeMPerson BIGINT UNSIGNED,
	sref VARCHAR(50),
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	ixWdbeVLocale INT UNSIGNED,
	ixWdbeVUserlevel INT UNSIGNED,
	Password VARCHAR(30),
	Fullkey TEXT,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refWdbeMUsergroup),
	INDEX (refWdbeMPerson),
	INDEX (sref),
	INDEX (refJState),
	INDEX (ixVState)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMUsergroup(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	sref VARCHAR(50),
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMVariable(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeCVariable BIGINT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	sref VARCHAR(50),
	Const TINYINT,
	Falling TINYINT,
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	Onval TEXT,
	Offval TEXT,
	Defon TINYINT,
	Comment TEXT,
	INDEX (refWdbeCVariable),
	INDEX (refIxVTbl),
	INDEX (refUref),
	INDEX (refNum),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMVector(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixVBasetype INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	sref VARCHAR(50),
	srefsKOption VARCHAR(192),
	INDEX (ixVBasetype),
	INDEX (hkIxVTbl),
	INDEX (hkUref),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMVectoritem(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	vecRefWdbeMVector BIGINT UNSIGNED,
	vecNum INT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (vecRefWdbeMVector),
	INDEX (vecNum),
	INDEX (sref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeMVersion(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	prjRefWdbeMProject BIGINT UNSIGNED,
	prjNum INT UNSIGNED,
	bvrRefWdbeMVersion BIGINT UNSIGNED,
	Major SMALLINT UNSIGNED,
	Minor SMALLINT UNSIGNED,
	Sub SMALLINT UNSIGNED,
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	About TEXT,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (prjRefWdbeMProject),
	INDEX (prjNum),
	INDEX (bvrRefWdbeMVersion),
	INDEX (ixVState)
) ENGINE = ARIA;

CREATE TABLE TblWdbeRMCdcMSignal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMCdc BIGINT UNSIGNED,
	refWdbeMSignal BIGINT UNSIGNED,
	ixVDir INT UNSIGNED,
	INDEX (refWdbeMCdc),
	INDEX (refWdbeMSignal),
	INDEX (ixVDir)
) ENGINE = ARIA;

CREATE TABLE TblWdbeRMCommandMController(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMCommand BIGINT UNSIGNED,
	refWdbeMController BIGINT UNSIGNED,
	ivrRefWdbeMSignal BIGINT UNSIGNED,
	rvrRefWdbeMSignal BIGINT UNSIGNED,
	INDEX (refWdbeMCommand),
	INDEX (refWdbeMController)
) ENGINE = ARIA;

CREATE TABLE TblWdbeRMComponentMLibrary(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMComponent BIGINT UNSIGNED,
	refWdbeMLibrary BIGINT UNSIGNED,
	INDEX (refWdbeMComponent),
	INDEX (refWdbeMLibrary)
) ENGINE = ARIA;

CREATE TABLE TblWdbeRMCoreprojectMPerson(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	x1Startd INT UNSIGNED,
	x1Stopd INT UNSIGNED,
	refWdbeMCoreproject BIGINT UNSIGNED,
	refWdbeMPerson BIGINT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (x1Startd),
	INDEX (x1Stopd),
	INDEX (refWdbeMCoreproject),
	INDEX (refWdbeMPerson)
) ENGINE = ARIA;

CREATE TABLE TblWdbeRMModuleMModule(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ctdRefWdbeMModule BIGINT UNSIGNED,
	corRefWdbeMModule BIGINT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (ctdRefWdbeMModule),
	INDEX (corRefWdbeMModule),
	INDEX (srefKFunction)
) ENGINE = ARIA;

CREATE TABLE TblWdbeRMModuleMPeripheral(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMModule BIGINT UNSIGNED,
	refWdbeMPeripheral BIGINT UNSIGNED,
	INDEX (refWdbeMModule),
	INDEX (refWdbeMPeripheral)
) ENGINE = ARIA;

CREATE TABLE TblWdbeRMPersonMProject(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	x1Startd INT UNSIGNED,
	x1Stopd INT UNSIGNED,
	refWdbeMPerson BIGINT UNSIGNED,
	refWdbeMProject BIGINT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (x1Startd),
	INDEX (x1Stopd),
	INDEX (refWdbeMPerson),
	INDEX (refWdbeMProject)
) ENGINE = ARIA;

CREATE TABLE TblWdbeRMUsergroupUniversal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUsergroup BIGINT UNSIGNED,
	unvIxWdbeVMaintable INT UNSIGNED,
	unvUref BIGINT UNSIGNED,
	ixWdbeVRecaccess INT UNSIGNED,
	INDEX (refWdbeMUsergroup),
	INDEX (unvIxWdbeVMaintable),
	INDEX (unvUref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeRMUserMUsergroup(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUser BIGINT UNSIGNED,
	refWdbeMUsergroup BIGINT UNSIGNED,
	ixWdbeVUserlevel INT UNSIGNED,
	INDEX (refWdbeMUser),
	INDEX (refWdbeMUsergroup)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQBnk1NPin(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQBnkList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	refWdbeMUnit BIGINT UNSIGNED,
	srefKVoltstd VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCdcList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refWdbeMModule BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCdcMNSignal(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ixVDir INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCmdAInvpar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	cmdNum INT UNSIGNED,
	sref VARCHAR(50),
	ixWdbeVPartype INT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	Length TINYINT UNSIGNED,
	Defval TEXT,
	refWdbeMVectoritem BIGINT UNSIGNED,
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCmdARetpar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	cmdNum INT UNSIGNED,
	sref VARCHAR(50),
	ixWdbeVPartype INT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	Length TINYINT UNSIGNED,
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCmdList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Fullsref VARCHAR(50),
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	ixVRettype INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCmdMNController(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ivrRefWdbeMSignal BIGINT UNSIGNED,
	rvrRefWdbeMSignal BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCmp1NRelease(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCmpList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	refWdbeMVersion BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCmpMNLibrary(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCpr1NCoreversion(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCprList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	refWdbeMCoreversion BIGINT UNSIGNED,
	Giturl VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCprMNPerson(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	x1Stopd INT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCvrAIp(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	cvrNum INT UNSIGNED,
	sref VARCHAR(50),
	ixVTagtype INT UNSIGNED,
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCvrAPlh(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	cvrNum INT UNSIGNED,
	sref VARCHAR(50),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCvrBcv1NCoreversion(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCvrHk1NModule(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	hkNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQCvrList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refWdbeMCoreproject BIGINT UNSIGNED,
	Major SMALLINT UNSIGNED,
	Minor SMALLINT UNSIGNED,
	Sub SMALLINT UNSIGNED,
	bcvRefWdbeMCoreversion BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQErrAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	errNum INT UNSIGNED,
	sref VARCHAR(50),
	ixWdbeVPartype INT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	Length TINYINT UNSIGNED,
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQErrList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Fullsref VARCHAR(50),
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQFam1NUnit(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQFamList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	srefWdbeKVendor VARCHAR(50),
	Title VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQFilList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	Filename VARCHAR(50),
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	osrefKContent VARCHAR(50),
	srefKMimetype VARCHAR(50),
	Size SMALLINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQFstAStep(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	fstNum INT UNSIGNED,
	fnxRefWdbeMFsmstate BIGINT UNSIGNED,
	Cond1 TEXT,
	Ip1 VARCHAR(50),
	Cond2 TEXT,
	Ip2 VARCHAR(50),
	Cond3 TEXT,
	Ip3 VARCHAR(50),
	Cond4 TEXT,
	Ip4 VARCHAR(50),
	Cond5 TEXT,
	Ip5 VARCHAR(50),
	Cond6 TEXT,
	Ip6 VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQFstList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	fsmRefWdbeMFsm BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQGenList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	mdlRefWdbeMModule BIGINT UNSIGNED,
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQIntList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	refWdbeMUnit BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQIntSrc1NSensitivity(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQLibAMakefile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1RefWdbeMMachine BIGINT UNSIGNED,
	x2SrefKTag VARCHAR(50),
	Val TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQLibList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(50),
	Version VARCHAR(30),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQLibMNComponent(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMch1NRelease(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMchAMakefile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKTag VARCHAR(50),
	Val TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMchAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMchList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	supRefWdbeMMachine BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMchSup1NMachine(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMod1NCdc(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMod1NProcess(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModCorMNModule(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModCtdMNModule(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModCtrHk1NVector(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModCtrMNCommand(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ivrRefWdbeMSignal BIGINT UNSIGNED,
	rvrRefWdbeMSignal BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModCtrRef1NCommand(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModCtrRef1NError(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModHsm1NPipeline(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModKHdltype(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(1024),
	Implied VARCHAR(1024),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	srefWdbeKVendor VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	supRefWdbeMModule BIGINT UNSIGNED,
	tplRefWdbeMModule BIGINT UNSIGNED,
	Srefrule VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModMdl1NGeneric(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModMdl1NPort(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModMge1NSignal(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModMNPeripheral(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModRef1NSensitivity(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModRef1NSignal(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModRef1NVariable(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQModSup1NModule(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMtpAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMtpHsm1NPipeline(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMtpKHdltype(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(1024),
	Implied VARCHAR(1024),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMtpKParKey(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(1024),
	Implied VARCHAR(1024),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMtpList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	srefWdbeKVendor VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	Srefrule VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMtpMdl1NGeneric(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMtpMdl1NPort(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMtpMge1NSignal(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMtpRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMtpRef1NSensitivity(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMtpRef1NVariable(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMtpSup1NModule(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQMtpTpl1NModule(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPinAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPinList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	refWdbeMBank BIGINT UNSIGNED,
	Location VARCHAR(5),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPphAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPphList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	refWdbeMUnit BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPphMNModule(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPplList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	hsmRefWdbeMModule BIGINT UNSIGNED,
	Depth SMALLINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPplPpl1NSegment(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	pplNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrcFsmFsm1NFsmstate(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	fsmNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrcFsmHk1NVector(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrcKHdltype(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(1024),
	Implied VARCHAR(1024),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrcList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	refWdbeMModule BIGINT UNSIGNED,
	Falling TINYINT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrcMge1NSignal(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrcRef1NSensitivity(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrcRef1NVariable(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPreselect(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrjList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	Short VARCHAR(5),
	Title VARCHAR(50),
	refWdbeMVersion BIGINT UNSIGNED,
	Easy TINYINT,
	Giturl VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrjMNPerson(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	x1Stopd INT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrjPrj1NVersion(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	prjNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrsADetail(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKType VARCHAR(50),
	Val VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrsList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	Title VARCHAR(30),
	Firstname VARCHAR(30),
	Lastname VARCHAR(50),
	ixVSex INT UNSIGNED,
	telVal VARCHAR(192),
	emlVal VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrsMNCoreproject(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	x1Stopd INT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrsMNProject(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	x1Stopd INT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrtList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	mdlRefWdbeMModule BIGINT UNSIGNED,
	mdlIxVCat INT UNSIGNED,
	ixVDir INT UNSIGNED,
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQPrtSrc1NSensitivity(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQRlsList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	refWdbeMComponent BIGINT UNSIGNED,
	refWdbeMMachine BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSegList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	pplRefWdbeMPipeline BIGINT UNSIGNED,
	supRefWdbeMSegment BIGINT UNSIGNED,
	Infmt VARCHAR(30),
	Outfmt VARCHAR(30),
	Latency SMALLINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSegSup1NSegment(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSelect(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ix INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (ix)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSigList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	mgeIxVTbl INT UNSIGNED,
	mgeUref BIGINT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	Const TINYINT,
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSigMNCdc(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ixVDir INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSigSrc1NSensitivity(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSil1NBank(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSil1NInterrupt(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSil1NPeripheral(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSilHk1NModule(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	hkNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSilHk1NVector(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSilList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(192),
	Fullsref VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	refWdbeMModule BIGINT UNSIGNED,
	srefKPackage VARCHAR(50),
	Easy TINYINT,
	srefKToolch VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSilRef1NCommand(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSilRef1NError(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSilRef1NSignal(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSilSil1NUnit(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQSnsList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	srcIxVTbl INT UNSIGNED,
	srcUref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUnt1NBank(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUnt1NInterrupt(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUnt1NPeripheral(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUntHk1NModule(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	hkNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUntHk1NVector(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUntList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(192),
	Fullsref VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	refWdbeMModule BIGINT UNSIGNED,
	srefKPackage VARCHAR(50),
	Easy TINYINT,
	srefKToolch VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUntRef1NCommand(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUntRef1NError(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUntRef1NSignal(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUntSil1NUnit(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUsgAAccess(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1IxWdbeVFeatgroup INT UNSIGNED,
	x2FeaSrefUix VARCHAR(50),
	ixWdbeWAccess INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUsgList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	sref VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUsgMNUser(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ixWdbeVUserlevel INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUsr1NSession(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUsrAAccess(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1IxWdbeVFeatgroup INT UNSIGNED,
	x2FeaSrefUix VARCHAR(50),
	ixWdbeWAccess INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUsrList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refWdbeMPerson BIGINT UNSIGNED,
	sref VARCHAR(50),
	refWdbeMUsergroup BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	ixWdbeVLocale INT UNSIGNED,
	ixWdbeVUserlevel INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQUsrMNUsergroup(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ixWdbeVUserlevel INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQVarList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	Const TINYINT,
	Falling TINYINT,
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQVecList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQVecVec1NVectoritem(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	vecNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQVer1NComponent(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQVer1NUnit(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQVerBvr1NVersion(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQVerList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	prjRefWdbeMProject BIGINT UNSIGNED,
	Major SMALLINT UNSIGNED,
	Minor SMALLINT UNSIGNED,
	Sub SMALLINT UNSIGNED,
	bvrRefWdbeMVersion BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQVerRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;

CREATE TABLE TblWdbeQVitList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(192),
	vecRefWdbeMVector BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = ARIA;
