/**
	* \file WdbecmbdOpprc.h
	* operation processor for Wdbe combined daemon (declarations)
	* \copyright (C) 2016-2020 MPSI Technologies GmbH
	* \author Alexander Wirthmueller (auto-generation)
	* \date created: 28 Nov 2020
  */
// IP header --- ABOVE

#ifndef WDBECMBDOPPRC_H
#define WDBECMBDOPPRC_H

#include "WdbeCplmstCtrEctrHostifEhostif.h"
#include "WdbeCplmstImbuf.h"
#include "WdbeCplmstTplcpy.h"
#include "WdbeCplmstUnt.h"
#include "WdbeGenAux.h"
#include "WdbeGenStdvec.h"
#include "WdbeGenWiring.h"
#include "WdbeGenfstCmdbus.h"
#include "WdbeGenfstCtr.h"
#include "WdbeGenfstEctr.h"
#include "WdbeGenfstEhostif.h"
#include "WdbeGenfstHostif.h"
#include "WdbeGenfstImbuf.h"
#include "WdbeGenfstPpl.h"
#include "WdbeGenfstTop.h"
#include "WdbeMtpCplmstbuAximmcohostif_Easy_v1_0.h"
#include "WdbeMtpCplmstbuAxislave_v1_0.h"
#include "WdbeMtpCplmstbuCmdinv_v2_0.h"
#include "WdbeMtpCplmstbuCmdret_v2_0.h"
#include "WdbeMtpCplmstbuCmult_xlnx_v6_0.h"
#include "WdbeMtpCplmstbuCohostif_Easy_v1_0.h"
#include "WdbeMtpCplmstbuCohostif_v1_0.h"
#include "WdbeMtpCplmstbuCrcspec_v2_0.h"
#include "WdbeMtpCplmstbuCrcspec_v3_0.h"
#include "WdbeMtpCplmstbuCsi2_hard_mipi_rx_efnx_v1_3.h"
#include "WdbeMtpCplmstbuDdrmux_Easy_v1_0.h"
#include "WdbeMtpCplmstbuDft_xlnx_v4_0.h"
#include "WdbeMtpCplmstbuDiv_xlnx_v3_0.h"
#include "WdbeMtpCplmstbuDiv_xlnx_v5_1.h"
#include "WdbeMtpCplmstbuDotmx2x16_v1_0.h"
#include "WdbeMtpCplmstbuDpbram_efnx_v6_1.h"
#include "WdbeMtpCplmstbuDpbram_v1_0.h"
#include "WdbeMtpCplmstbuDpbram_xlnx_v8_4.h"
#include "WdbeMtpCplmstbuDpebram_lttc_v1_2.h"
#include "WdbeMtpCplmstbuDphy_rx_lttc_v1_4_csi.h"
#include "WdbeMtpCplmstbuDpram_efnx_v1_0.h"
#include "WdbeMtpCplmstbuDpsram_mchp_v1_1_110.h"
#include "WdbeMtpCplmstbuEbrom_lttc_v1_3.h"
#include "WdbeMtpCplmstbuEFX_DPRAM10.h"
#include "WdbeMtpCplmstbuEFX_RAM10.h"
#include "WdbeMtpCplmstbuFifo_lttc_v1_3.h"
#include "WdbeMtpCplmstbuFsmprobe_Easy_v1_0.h"
#include "WdbeMtpCplmstbuFsmtrack_Easy_v1_0.h"
#include "WdbeMtpCplmstbuGpio_Easy_v1_0.h"
#include "WdbeMtpCplmstbuGptrack_Easy_v1_0.h"
#include "WdbeMtpCplmstbuHostif_Easy_v1_0.h"
#include "WdbeMtpCplmstbuHostif_v1_0.h"
#include "WdbeMtpCplmstbuI2cmaster_v1_0.h"
#include "WdbeMtpCplmstbuI2c_Easy_v1_0.h"
#include "WdbeMtpCplmstbuIdent_Easy_v1_0.h"
#include "WdbeMtpCplmstbuIod_mchp_v1_0_mipirx.h"
#include "WdbeMtpCplmstbuIrq_Easy_v1_0.h"
#include "WdbeMtpCplmstbuMipidec_mchp_v1_0.h"
#include "WdbeMtpCplmstbuMipirx_xlnx_v5_1.h"
#include "WdbeMtpCplmstbuMult_xlnx_v12_0.h"
#include "WdbeMtpCplmstbuOled128x32_v1_0.h"
#include "WdbeMtpCplmstbuOscoll_v1_0.h"
#include "WdbeMtpCplmstbuSelectio_xlnx_v5_1_mipirx.h"
#include "WdbeMtpCplmstbuSmartreg_Easy_v1_0.h"
#include "WdbeMtpCplmstbuSmartreg_v1_0.h"
#include "WdbeMtpCplmstbuSpbram_efnx_v6_1.h"
#include "WdbeMtpCplmstbuSpbram_v1_0.h"
#include "WdbeMtpCplmstbuSpbram_xlnx_v8_4.h"
#include "WdbeMtpCplmstbuSpebram_lttc_v1_4.h"
#include "WdbeMtpCplmstbuSpram_efnx_v1_0.h"
#include "WdbeMtpCplmstbuToc_v1_0.h"
#include "WdbeMtpCplmstbuTop_v1_0.h"
#include "WdbeMtpCplmstbuTpsram_mchp_v1_1_108.h"
#include "WdbeMtpCplmstbuUartrx_v1_0_Mcu.h"
#include "WdbeMtpCplmstbuUarttx_v1_0_Mcu.h"
#include "WdbeMtpCplmstbuUart_Easy_v1_0.h"
#include "WdbeMtpCplmstbuUsbslave_slbs_v1_0_Mcu.h"
#include "WdbeMtpCplmstbuXadc_xlnx_v3_3.h"
#include "WdbeMtpCplmstbuXfft_xlnx_v9_1.h"
#include "WdbeMtpCplmsttdCmdinv_v2_0.h"
#include "WdbeMtpCplmsttdCmdret_v2_0.h"
#include "WdbeMtpCplmsttdCohostif_Easy_v1_0.h"
#include "WdbeMtpCplmsttdCohostif_v1_0.h"
#include "WdbeMtpCplmsttdDdrmux_Easy_v1_0.h"
#include "WdbeMtpCplmsttdDpbram_v1_0.h"
#include "WdbeMtpCplmsttdDpram_efnx_v1_0.h"
#include "WdbeMtpCplmsttdFsmtrack_Easy_v1_0.h"
#include "WdbeMtpCplmsttdGpio_Easy_v1_0.h"
#include "WdbeMtpCplmsttdGptrack_Easy_v1_0.h"
#include "WdbeMtpCplmsttdHostif_Easy_v1_0.h"
#include "WdbeMtpCplmsttdHostif_v1_0.h"
#include "WdbeMtpCplmsttdI2cmaster_v1_0.h"
#include "WdbeMtpCplmsttdSpbram_v1_0.h"
#include "WdbeMtpCplmsttdSpram_efnx_v1_0.h"
#include "WdbeMtpCplmsttdTop_v1_0.h"
#include "WdbeMtpGenfstBtshuffle_v1_0.h"
#include "WdbeMtpGenfstCohostif_Easy_v1_0.h"
#include "WdbeMtpGenfstDdrmux_Easy_v1_0.h"
#include "WdbeMtpGenfstFsmtrack_Easy_v1_0.h"
#include "WdbeMtpGenfstGpio_Easy_v1_0.h"
#include "WdbeMtpGenfstGptrack_Easy_v1_0.h"
#include "WdbeMtpGenfstHostif_Easy_v1_0.h"
#include "WdbeMtpGenfstTkclksrc_Easy_v1_0.h"
#include "WdbeMtpGenfstTkclksrc_v1_0.h"
#include "WdbeMtpGenfstUarthostif_Easy_v2_0_Mcu.h"
#include "WdbeMtpGenfstUsbhostif_Easy_v2_0_Mcu.h"
#include "WdbeMtpPlhfpgaAximmcohostif_Easy_v1_0.h"
#include "WdbeMtpPlhfpgaCohostif_Easy_v1_0.h"
#include "WdbeMtpPlhfpgaCohostif_v1_0.h"
#include "WdbeMtpPlhfpgaCrcspec_v2_0.h"
#include "WdbeMtpPlhfpgaCrcspec_v3_0.h"
#include "WdbeMtpPlhfpgaFsmtrack_Easy_v1_0.h"
#include "WdbeMtpPlhfpgaGptrack_Easy_v1_0.h"
#include "WdbeMtpPlhfpgaHostif_Easy_v1_0.h"
#include "WdbeMtpPlhfpgaHostif_v1_0.h"
#include "WdbeMtpPlhfpgaIdent_Easy_v1_0.h"
#include "WdbeMtpPlhfpgaOscoll_v1_0.h"
#include "WdbeMtpWrfpgaAximmcohostif_Easy_v1_0.h"
#include "WdbeMtpWrfpgaBtshuffle_v1_0.h"
#include "WdbeMtpWrfpgaCmdinv_v2_0.h"
#include "WdbeMtpWrfpgaCmdret_v2_0.h"
#include "WdbeMtpWrfpgaCohostif_Easy_v1_0.h"
#include "WdbeMtpWrfpgaCohostif_v1_0.h"
#include "WdbeMtpWrfpgaCrcspec_32_v1_0.h"
#include "WdbeMtpWrfpgaCrcspec_v1_0.h"
#include "WdbeMtpWrfpgaCrcspec_v2_0.h"
#include "WdbeMtpWrfpgaCrcspec_v3_0.h"
#include "WdbeMtpWrfpgaDdrmux_Easy_v1_0.h"
#include "WdbeMtpWrfpgaDpbram_v1_0.h"
#include "WdbeMtpWrfpgaDpram_efnx_v1_0.h"
#include "WdbeMtpWrfpgaFsmprobe_Easy_v1_0.h"
#include "WdbeMtpWrfpgaFsmtrack_Easy_v1_0.h"
#include "WdbeMtpWrfpgaGpio_Easy_v1_0.h"
#include "WdbeMtpWrfpgaGptrack_Easy_v1_0.h"
#include "WdbeMtpWrfpgaHostif_Easy_v1_0.h"
#include "WdbeMtpWrfpgaHostif_v1_0.h"
#include "WdbeMtpWrfpgaI2cmaster_v1_0.h"
#include "WdbeMtpWrfpgaIdent_Easy_v1_0.h"
#include "WdbeMtpWrfpgaIrq_Easy_v1_0.h"
#include "WdbeMtpWrfpgaSpbram_v1_0.h"
#include "WdbeMtpWrfpgaSpram_efnx_v1_0.h"
#include "WdbeMtpWrfpgaTkclksrc_v1_0.h"
#include "WdbeMtpWrmcuUarthostif_Easy_v2_0_Mcu.h"
#include "WdbeMtpWrmcuUsbhostif_Easy_v2_0_Mcu.h"
#include "WdbePlhfpgaCmdinv.h"
#include "WdbePlhfpgaCmdret.h"
#include "WdbePlhfpgaCtr.h"
#include "WdbePlhmcuEctr.h"
#include "WdbePlhmcuEhostif.h"
#include "WdbePrcfileConcat.h"
#include "WdbePrcfilePlhrpl.h"
#include "WdbePrctreeExtract.h"
#include "WdbePrctreeMerge.h"
#include "WdbePrctreeValidate.h"
#include "WdbeWrdevBase.h"
#include "WdbeWrdevCtr.h"
#include "WdbeWrdevDeploy.h"
#include "WdbeWrdevUnt.h"
#include "WdbeWrfpgaAux.h"
#include "WdbeWrfpgaBase.h"
#include "WdbeWrfpgaCtr.h"
#include "WdbeWrfpgaDeploy.h"
#include "WdbeWrfpgaMdlfine.h"
#include "WdbeWrfpgaMdlraw.h"
#include "WdbeWrfpgaTop.h"
#include "WdbeWrmcuBase.h"
#include "WdbeWrmcuCtr.h"
#include "WdbeWrmcuDeploy.h"
#include "WdbeWrmcuMdlfine.h"
#include "WdbeWrmcuMdlraw.h"
#include "WdbeWrtermDeploy.h"
#include "WdbeWrtermMain.h"

/**
	* WdbecmbdOpprc
	*/
namespace WdbecmbdOpprc {
	void* run(void* arg);
	void cleanup(void* arg);
};

#endif
