CREATE DATABASE DbsWdbe;
USE DbsWdbe;

CREATE USER 'mpsitech'@'%' IDENTIFIED BY 'asdf1234';
GRANT ALL PRIVILEGES ON DbsWdbe.* TO 'mpsitech'@'%';

CREATE USER 'mpsitech'@'localhost' IDENTIFIED BY 'asdf1234';
GRANT ALL PRIVILEGES ON DbsWdbe.* TO 'mpsitech'@'localhost';

DROP TABLE IF EXISTS TblWdbeAccRMUserUniversal;
DROP TABLE IF EXISTS TblWdbeAMCommandInvpar;
DROP TABLE IF EXISTS TblWdbeAMCommandRetpar;
DROP TABLE IF EXISTS TblWdbeAMCoreversionIp;
DROP TABLE IF EXISTS TblWdbeAMCoreversionPlh;
DROP TABLE IF EXISTS TblWdbeAMErrorPar;
DROP TABLE IF EXISTS TblWdbeAMFsmstateStep;
DROP TABLE IF EXISTS TblWdbeAMLibraryMakefile;
DROP TABLE IF EXISTS TblWdbeAMMachineMakefile;
DROP TABLE IF EXISTS TblWdbeAMMachinePar;
DROP TABLE IF EXISTS TblWdbeAMModulePar;
DROP TABLE IF EXISTS TblWdbeAMPeripheralPar;
DROP TABLE IF EXISTS TblWdbeAMPersonDetail;
DROP TABLE IF EXISTS TblWdbeAMPinPar;
DROP TABLE IF EXISTS TblWdbeAMUserAccess;
DROP TABLE IF EXISTS TblWdbeAMUsergroupAccess;
DROP TABLE IF EXISTS TblWdbeAVControlPar;
DROP TABLE IF EXISTS TblWdbeAVKeylistKey;
DROP TABLE IF EXISTS TblWdbeAVValuelistVal;
DROP TABLE IF EXISTS TblWdbeCFile;
DROP TABLE IF EXISTS TblWdbeCFsmstate;
DROP TABLE IF EXISTS TblWdbeCGeneric;
DROP TABLE IF EXISTS TblWdbeCPin;
DROP TABLE IF EXISTS TblWdbeCPort;
DROP TABLE IF EXISTS TblWdbeCSignal;
DROP TABLE IF EXISTS TblWdbeCVariable;
DROP TABLE IF EXISTS TblWdbeHistRMUserUniversal;
DROP TABLE IF EXISTS TblWdbeJAVKeylistKey;
DROP TABLE IF EXISTS TblWdbeJMCoreversionState;
DROP TABLE IF EXISTS TblWdbeJMPersonLastname;
DROP TABLE IF EXISTS TblWdbeJMPinSref;
DROP TABLE IF EXISTS TblWdbeJMUserState;
DROP TABLE IF EXISTS TblWdbeJMVersionState;
DROP TABLE IF EXISTS TblWdbeMBank;
DROP TABLE IF EXISTS TblWdbeMCommand;
DROP TABLE IF EXISTS TblWdbeMController;
DROP TABLE IF EXISTS TblWdbeMCoreproject;
DROP TABLE IF EXISTS TblWdbeMCoreversion;
DROP TABLE IF EXISTS TblWdbeMError;
DROP TABLE IF EXISTS TblWdbeMFamily;
DROP TABLE IF EXISTS TblWdbeMFile;
DROP TABLE IF EXISTS TblWdbeMFsm;
DROP TABLE IF EXISTS TblWdbeMFsmstate;
DROP TABLE IF EXISTS TblWdbeMGeneric;
DROP TABLE IF EXISTS TblWdbeMImbuf;
DROP TABLE IF EXISTS TblWdbeMLibrary;
DROP TABLE IF EXISTS TblWdbeMMachine;
DROP TABLE IF EXISTS TblWdbeMModule;
DROP TABLE IF EXISTS TblWdbeMPeripheral;
DROP TABLE IF EXISTS TblWdbeMPerson;
DROP TABLE IF EXISTS TblWdbeMPin;
DROP TABLE IF EXISTS TblWdbeMPort;
DROP TABLE IF EXISTS TblWdbeMProcess;
DROP TABLE IF EXISTS TblWdbeMProject;
DROP TABLE IF EXISTS TblWdbeMRelease;
DROP TABLE IF EXISTS TblWdbeMSession;
DROP TABLE IF EXISTS TblWdbeMSignal;
DROP TABLE IF EXISTS TblWdbeMSystem;
DROP TABLE IF EXISTS TblWdbeMTarget;
DROP TABLE IF EXISTS TblWdbeMUnit;
DROP TABLE IF EXISTS TblWdbeMUser;
DROP TABLE IF EXISTS TblWdbeMUsergroup;
DROP TABLE IF EXISTS TblWdbeMVariable;
DROP TABLE IF EXISTS TblWdbeMVector;
DROP TABLE IF EXISTS TblWdbeMVectoritem;
DROP TABLE IF EXISTS TblWdbeMVersion;
DROP TABLE IF EXISTS TblWdbeRMCommandMController;
DROP TABLE IF EXISTS TblWdbeRMCoreprojectMPerson;
DROP TABLE IF EXISTS TblWdbeRMLibraryMVersion;
DROP TABLE IF EXISTS TblWdbeRMPersonMProject;
DROP TABLE IF EXISTS TblWdbeRMUsergroupUniversal;
DROP TABLE IF EXISTS TblWdbeRMUserMUsergroup;

DROP TABLE IF EXISTS TblWdbeQBnk1NPin;
DROP TABLE IF EXISTS TblWdbeQBnkList;
DROP TABLE IF EXISTS TblWdbeQCmdAInvpar;
DROP TABLE IF EXISTS TblWdbeQCmdARetpar;
DROP TABLE IF EXISTS TblWdbeQCmdList;
DROP TABLE IF EXISTS TblWdbeQCmdMNController;
DROP TABLE IF EXISTS TblWdbeQCpr1NCoreversion;
DROP TABLE IF EXISTS TblWdbeQCprList;
DROP TABLE IF EXISTS TblWdbeQCprMNPerson;
DROP TABLE IF EXISTS TblWdbeQCvrAIp;
DROP TABLE IF EXISTS TblWdbeQCvrAPlh;
DROP TABLE IF EXISTS TblWdbeQCvrBcv1NCoreversion;
DROP TABLE IF EXISTS TblWdbeQCvrHk1NModule;
DROP TABLE IF EXISTS TblWdbeQCvrList;
DROP TABLE IF EXISTS TblWdbeQErrAPar;
DROP TABLE IF EXISTS TblWdbeQErrList;
DROP TABLE IF EXISTS TblWdbeQFam1NUnit;
DROP TABLE IF EXISTS TblWdbeQFamList;
DROP TABLE IF EXISTS TblWdbeQFilList;
DROP TABLE IF EXISTS TblWdbeQFstAStep;
DROP TABLE IF EXISTS TblWdbeQFstList;
DROP TABLE IF EXISTS TblWdbeQGenList;
DROP TABLE IF EXISTS TblWdbeQLibAMakefile;
DROP TABLE IF EXISTS TblWdbeQLibList;
DROP TABLE IF EXISTS TblWdbeQLibMNVersion;
DROP TABLE IF EXISTS TblWdbeQMch1NRelease;
DROP TABLE IF EXISTS TblWdbeQMchAMakefile;
DROP TABLE IF EXISTS TblWdbeQMchAPar;
DROP TABLE IF EXISTS TblWdbeQMchList;
DROP TABLE IF EXISTS TblWdbeQMod1NPeripheral;
DROP TABLE IF EXISTS TblWdbeQMod1NProcess;
DROP TABLE IF EXISTS TblWdbeQModAPar;
DROP TABLE IF EXISTS TblWdbeQModCor1NImbuf;
DROP TABLE IF EXISTS TblWdbeQModCtrHk1NVector;
DROP TABLE IF EXISTS TblWdbeQModCtrMNCommand;
DROP TABLE IF EXISTS TblWdbeQModCtrRef1NCommand;
DROP TABLE IF EXISTS TblWdbeQModCtrRef1NError;
DROP TABLE IF EXISTS TblWdbeQModKHdltype;
DROP TABLE IF EXISTS TblWdbeQModList;
DROP TABLE IF EXISTS TblWdbeQModMdl1NGeneric;
DROP TABLE IF EXISTS TblWdbeQModMdl1NPort;
DROP TABLE IF EXISTS TblWdbeQModMdl1NSignal;
DROP TABLE IF EXISTS TblWdbeQModMge1NSignal;
DROP TABLE IF EXISTS TblWdbeQModSup1NModule;
DROP TABLE IF EXISTS TblWdbeQMtpAPar;
DROP TABLE IF EXISTS TblWdbeQMtpKHdltype;
DROP TABLE IF EXISTS TblWdbeQMtpKParKey;
DROP TABLE IF EXISTS TblWdbeQMtpList;
DROP TABLE IF EXISTS TblWdbeQMtpMdl1NGeneric;
DROP TABLE IF EXISTS TblWdbeQMtpMdl1NPort;
DROP TABLE IF EXISTS TblWdbeQMtpMge1NSignal;
DROP TABLE IF EXISTS TblWdbeQMtpRef1NFile;
DROP TABLE IF EXISTS TblWdbeQMtpSup1NModule;
DROP TABLE IF EXISTS TblWdbeQMtpTpl1NModule;
DROP TABLE IF EXISTS TblWdbeQPinAPar;
DROP TABLE IF EXISTS TblWdbeQPinList;
DROP TABLE IF EXISTS TblWdbeQPphAPar;
DROP TABLE IF EXISTS TblWdbeQPphList;
DROP TABLE IF EXISTS TblWdbeQPrcFsmFsm1NFsmstate;
DROP TABLE IF EXISTS TblWdbeQPrcKHdltype;
DROP TABLE IF EXISTS TblWdbeQPrcList;
DROP TABLE IF EXISTS TblWdbeQPrcMge1NSignal;
DROP TABLE IF EXISTS TblWdbeQPrcPrc1NVariable;
DROP TABLE IF EXISTS TblWdbeQPreselect;
DROP TABLE IF EXISTS TblWdbeQPrj1NVersion;
DROP TABLE IF EXISTS TblWdbeQPrjList;
DROP TABLE IF EXISTS TblWdbeQPrjMNPerson;
DROP TABLE IF EXISTS TblWdbeQPrsADetail;
DROP TABLE IF EXISTS TblWdbeQPrsList;
DROP TABLE IF EXISTS TblWdbeQPrsMNCoreproject;
DROP TABLE IF EXISTS TblWdbeQPrsMNProject;
DROP TABLE IF EXISTS TblWdbeQPrtList;
DROP TABLE IF EXISTS TblWdbeQRlsList;
DROP TABLE IF EXISTS TblWdbeQSelect;
DROP TABLE IF EXISTS TblWdbeQSigList;
DROP TABLE IF EXISTS TblWdbeQSil1NBank;
DROP TABLE IF EXISTS TblWdbeQSil1NPeripheral;
DROP TABLE IF EXISTS TblWdbeQSil1NTarget;
DROP TABLE IF EXISTS TblWdbeQSilFwd1NController;
DROP TABLE IF EXISTS TblWdbeQSilHk1NModule;
DROP TABLE IF EXISTS TblWdbeQSilHk1NVector;
DROP TABLE IF EXISTS TblWdbeQSilList;
DROP TABLE IF EXISTS TblWdbeQSilRef1NCommand;
DROP TABLE IF EXISTS TblWdbeQSilRef1NError;
DROP TABLE IF EXISTS TblWdbeQSilSil1NUnit;
DROP TABLE IF EXISTS TblWdbeQSysHk1NVector;
DROP TABLE IF EXISTS TblWdbeQSysList;
DROP TABLE IF EXISTS TblWdbeQSysSys1NTarget;
DROP TABLE IF EXISTS TblWdbeQTrgList;
DROP TABLE IF EXISTS TblWdbeQUnt1NBank;
DROP TABLE IF EXISTS TblWdbeQUnt1NPeripheral;
DROP TABLE IF EXISTS TblWdbeQUnt1NTarget;
DROP TABLE IF EXISTS TblWdbeQUntFwd1NController;
DROP TABLE IF EXISTS TblWdbeQUntHk1NModule;
DROP TABLE IF EXISTS TblWdbeQUntHk1NVector;
DROP TABLE IF EXISTS TblWdbeQUntList;
DROP TABLE IF EXISTS TblWdbeQUntRef1NCommand;
DROP TABLE IF EXISTS TblWdbeQUntRef1NError;
DROP TABLE IF EXISTS TblWdbeQUntSil1NUnit;
DROP TABLE IF EXISTS TblWdbeQUsgAAccess;
DROP TABLE IF EXISTS TblWdbeQUsgList;
DROP TABLE IF EXISTS TblWdbeQUsgMNUser;
DROP TABLE IF EXISTS TblWdbeQUsr1NSession;
DROP TABLE IF EXISTS TblWdbeQUsrAAccess;
DROP TABLE IF EXISTS TblWdbeQUsrList;
DROP TABLE IF EXISTS TblWdbeQUsrMNUsergroup;
DROP TABLE IF EXISTS TblWdbeQVarList;
DROP TABLE IF EXISTS TblWdbeQVecList;
DROP TABLE IF EXISTS TblWdbeQVecVec1NVectoritem;
DROP TABLE IF EXISTS TblWdbeQVer1NRelease;
DROP TABLE IF EXISTS TblWdbeQVer1NSystem;
DROP TABLE IF EXISTS TblWdbeQVer1NUnit;
DROP TABLE IF EXISTS TblWdbeQVerBvr1NVersion;
DROP TABLE IF EXISTS TblWdbeQVerList;
DROP TABLE IF EXISTS TblWdbeQVerMNLibrary;
DROP TABLE IF EXISTS TblWdbeQVerRef1NFile;
DROP TABLE IF EXISTS TblWdbeQVitList;

CREATE TABLE TblWdbeAccRMUserUniversal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUser BIGINT UNSIGNED,
	unvIxWdbeVMaintable INT UNSIGNED,
	unvUref BIGINT UNSIGNED,
	ixWdbeVRecaccess INT UNSIGNED,
	INDEX (refWdbeMUser),
	INDEX (unvIxWdbeVMaintable),
	INDEX (unvUref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAMCommandInvpar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	cmdRefWdbeMCommand BIGINT UNSIGNED,
	cmdNum INT UNSIGNED,
	sref VARCHAR(50),
	ixWdbeVPartype INT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	Length TINYINT UNSIGNED,
	Defval TEXT,
	refWdbeMVectoritem BIGINT UNSIGNED,
	Comment TEXT,
	INDEX (cmdRefWdbeMCommand),
	INDEX (cmdNum),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAMCommandRetpar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	cmdRefWdbeMCommand BIGINT UNSIGNED,
	cmdNum INT UNSIGNED,
	sref VARCHAR(50),
	ixWdbeVPartype INT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	Length TINYINT UNSIGNED,
	Comment TEXT,
	INDEX (cmdRefWdbeMCommand),
	INDEX (cmdNum),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAMCoreversionIp(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	cvrRefWdbeMCoreversion BIGINT UNSIGNED,
	cvrNum INT UNSIGNED,
	sref VARCHAR(50),
	ixVTagtype INT UNSIGNED,
	Comment TEXT,
	INDEX (cvrRefWdbeMCoreversion),
	INDEX (cvrNum),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAMCoreversionPlh(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	cvrRefWdbeMCoreversion BIGINT UNSIGNED,
	cvrNum INT UNSIGNED,
	sref VARCHAR(50),
	Comment TEXT,
	INDEX (cvrRefWdbeMCoreversion),
	INDEX (cvrNum),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAMErrorPar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	errRefWdbeMError BIGINT UNSIGNED,
	errNum INT UNSIGNED,
	sref VARCHAR(50),
	ixWdbeVPartype INT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	Length TINYINT UNSIGNED,
	Comment TEXT,
	INDEX (errRefWdbeMError),
	INDEX (errNum),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAMFsmstateStep(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	fstRefWdbeMFsmstate BIGINT UNSIGNED,
	fstNum INT UNSIGNED,
	fnxRefWdbeMFsmstate BIGINT UNSIGNED,
	Cond1 TEXT,
	Ip1 VARCHAR(50),
	Cond2 TEXT,
	Ip2 VARCHAR(50),
	Cond3 TEXT,
	Ip3 VARCHAR(50),
	Cond4 TEXT,
	Ip4 VARCHAR(50),
	INDEX (fstRefWdbeMFsmstate),
	INDEX (fstNum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAMLibraryMakefile(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMLibrary BIGINT UNSIGNED,
	x1RefWdbeMMachine BIGINT UNSIGNED,
	x2SrefKTag VARCHAR(50),
	Val TEXT,
	INDEX (refWdbeMLibrary),
	INDEX (x1RefWdbeMMachine),
	INDEX (x2SrefKTag)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAMMachineMakefile(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMMachine BIGINT UNSIGNED,
	x1SrefKTag VARCHAR(50),
	Val TEXT,
	INDEX (refWdbeMMachine),
	INDEX (x1SrefKTag)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAMMachinePar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMMachine BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (refWdbeMMachine),
	INDEX (x1SrefKKey)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAMModulePar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	mdlRefWdbeMModule BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (mdlRefWdbeMModule),
	INDEX (mdlNum),
	INDEX (x1SrefKKey)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAMPeripheralPar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMPeripheral BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (refWdbeMPeripheral),
	INDEX (x1SrefKKey)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAMPersonDetail(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMPerson BIGINT UNSIGNED,
	x1SrefKType VARCHAR(50),
	Val VARCHAR(192),
	INDEX (refWdbeMPerson)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAMPinPar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMPin BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (refWdbeMPin),
	INDEX (x1SrefKKey)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAMUserAccess(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUser BIGINT UNSIGNED,
	x1IxWdbeVFeatgroup INT UNSIGNED,
	x2FeaSrefUix VARCHAR(50),
	ixWdbeWAccess INT UNSIGNED,
	INDEX (refWdbeMUser),
	INDEX (x1IxWdbeVFeatgroup),
	INDEX (x2FeaSrefUix)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAMUsergroupAccess(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUsergroup BIGINT UNSIGNED,
	x1IxWdbeVFeatgroup INT UNSIGNED,
	x2FeaSrefUix VARCHAR(50),
	ixWdbeWAccess INT UNSIGNED,
	INDEX (refWdbeMUsergroup),
	INDEX (x1IxWdbeVFeatgroup),
	INDEX (x2FeaSrefUix)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAVControlPar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixWdbeVControl INT UNSIGNED,
	x1RefWdbeMUser BIGINT UNSIGNED,
	x2IxWdbeVLocale INT UNSIGNED,
	Par VARCHAR(192),
	Val VARCHAR(192),
	INDEX (ixWdbeVControl),
	INDEX (x1RefWdbeMUser),
	INDEX (x2IxWdbeVLocale),
	INDEX (Par)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAVKeylistKey(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	klsIxWdbeVKeylist INT UNSIGNED,
	klsNum INT UNSIGNED,
	x1IxWdbeVMaintable INT UNSIGNED,
	x1Uref BIGINT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(1024),
	Implied VARCHAR(1024),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (klsIxWdbeVKeylist),
	INDEX (klsNum),
	INDEX (x1IxWdbeVMaintable),
	INDEX (x1Uref),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeAVValuelistVal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	vlsIxWdbeVValuelist INT UNSIGNED,
	vlsNum INT UNSIGNED,
	x1IxWdbeVLocale INT UNSIGNED,
	Val VARCHAR(192),
	INDEX (vlsIxWdbeVValuelist),
	INDEX (vlsNum),
	INDEX (x1IxWdbeVLocale)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeCFile(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = MYISAM;

CREATE TABLE TblWdbeCFsmstate(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = MYISAM;

CREATE TABLE TblWdbeCGeneric(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = MYISAM;

CREATE TABLE TblWdbeCPin(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = MYISAM;

CREATE TABLE TblWdbeCPort(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = MYISAM;

CREATE TABLE TblWdbeCSignal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = MYISAM;

CREATE TABLE TblWdbeCVariable(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = MYISAM;

CREATE TABLE TblWdbeHistRMUserUniversal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUser BIGINT UNSIGNED,
	unvIxWdbeVMaintable INT UNSIGNED,
	unvUref BIGINT UNSIGNED,
	ixWdbeVCard INT UNSIGNED,
	ixWdbeVPreset INT UNSIGNED,
	preIxWdbeVMaintable INT UNSIGNED,
	preUref BIGINT UNSIGNED,
	start INT UNSIGNED,
	INDEX (refWdbeMUser),
	INDEX (unvIxWdbeVMaintable),
	INDEX (unvUref),
	INDEX (ixWdbeVCard),
	INDEX (ixWdbeVPreset),
	INDEX (preIxWdbeVMaintable),
	INDEX (preUref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeJAVKeylistKey(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeAVKeylistKey BIGINT UNSIGNED,
	x1IxWdbeVLocale INT UNSIGNED,
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (refWdbeAVKeylistKey),
	INDEX (x1IxWdbeVLocale)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeJMCoreversionState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMCoreversion BIGINT UNSIGNED,
	x1Start INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refWdbeMCoreversion),
	INDEX (x1Start)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeJMPersonLastname(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMPerson BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	Lastname VARCHAR(50),
	INDEX (refWdbeMPerson),
	INDEX (x1Startd),
	INDEX (Lastname)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeJMPinSref(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMPin BIGINT UNSIGNED,
	x1RefWdbeMPeripheral BIGINT UNSIGNED,
	sref VARCHAR(50),
	INDEX (refWdbeMPin),
	INDEX (x1RefWdbeMPeripheral),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeJMUserState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUser BIGINT UNSIGNED,
	x1Start INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refWdbeMUser),
	INDEX (x1Start)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeJMVersionState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMVersion BIGINT UNSIGNED,
	x1Start INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refWdbeMVersion),
	INDEX (x1Start)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMBank(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUnit BIGINT UNSIGNED,
	sref VARCHAR(50),
	srefKVoltstd VARCHAR(50),
	INDEX (refWdbeMUnit),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMCommand(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	sref VARCHAR(50),
	Fullsref VARCHAR(50),
	ixVRettype INT UNSIGNED,
	ivrRefWdbeMSignal BIGINT UNSIGNED,
	rvrRefWdbeMSignal BIGINT UNSIGNED,
	rerRefWdbeMSignal BIGINT UNSIGNED,
	Comment TEXT,
	INDEX (refIxVTbl),
	INDEX (refUref),
	INDEX (refNum),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMController(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMModule BIGINT UNSIGNED,
	fwdRefWdbeMUnit BIGINT UNSIGNED,
	Fullsref VARCHAR(50),
	clrRefWdbeMSignal BIGINT UNSIGNED,
	INDEX (refWdbeMModule),
	INDEX (fwdRefWdbeMUnit)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMCoreproject(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	ixVBasetype INT UNSIGNED,
	refWdbeMCoreversion BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(50),
	Giturl VARCHAR(192),
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (ixVBasetype),
	INDEX (refWdbeMCoreversion),
	INDEX (sref),
	INDEX (Title)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMCoreversion(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refWdbeMCoreproject BIGINT UNSIGNED,
	bcvRefWdbeMCoreversion BIGINT UNSIGNED,
	refWdbeMModule BIGINT UNSIGNED,
	Major SMALLINT UNSIGNED,
	Minor SMALLINT UNSIGNED,
	Sub SMALLINT UNSIGNED,
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	ixWSpectype INT UNSIGNED,
	INDEX (grp),
	INDEX (own),
	INDEX (refWdbeMCoreproject),
	INDEX (bcvRefWdbeMCoreversion),
	INDEX (refWdbeMModule),
	INDEX (ixVState)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMError(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	sref VARCHAR(50),
	Fullsref VARCHAR(50),
	traRefWdbeMSignal BIGINT UNSIGNED,
	Comment TEXT,
	INDEX (refIxVTbl),
	INDEX (refUref),
	INDEX (refNum),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMFamily(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	srefKVendor VARCHAR(50),
	Title VARCHAR(50),
	Comment TEXT,
	INDEX (srefKVendor),
	INDEX (Title)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMFile(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refWdbeCFile BIGINT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	osrefKContent VARCHAR(50),
	Archived INT UNSIGNED,
	Filename VARCHAR(50),
	Archivename VARCHAR(30),
	srefKMimetype VARCHAR(50),
	Size SMALLINT UNSIGNED,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refWdbeCFile),
	INDEX (refIxVTbl),
	INDEX (refUref),
	INDEX (Filename)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMFsm(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMProcess BIGINT UNSIGNED,
	INDEX (refWdbeMProcess)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMFsmstate(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeCFsmstate BIGINT UNSIGNED,
	fsmRefWdbeMFsm BIGINT UNSIGNED,
	fsmNum INT UNSIGNED,
	sref VARCHAR(50),
	Extip TINYINT,
	Comment TEXT,
	INDEX (refWdbeCFsmstate),
	INDEX (fsmRefWdbeMFsm),
	INDEX (fsmNum),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMGeneric(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeCGeneric BIGINT UNSIGNED,
	mdlRefWdbeMModule BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	sref VARCHAR(50),
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	Defval TEXT,
	srcSrefWdbeMGeneric VARCHAR(50),
	Comment TEXT,
	INDEX (refWdbeCGeneric),
	INDEX (mdlRefWdbeMModule),
	INDEX (mdlNum),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMImbuf(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMModule BIGINT UNSIGNED,
	corRefWdbeMModule BIGINT UNSIGNED,
	sref VARCHAR(50),
	ixVDir INT UNSIGNED,
	Prio TINYINT UNSIGNED,
	INDEX (refWdbeMModule),
	INDEX (corRefWdbeMModule),
	INDEX (sref),
	INDEX (Prio)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMLibrary(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	sref VARCHAR(50),
	Title VARCHAR(50),
	Version VARCHAR(30),
	depSrefsWdbeMLibrary VARCHAR(192),
	Comment TEXT,
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMMachine(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	srefKPlatform VARCHAR(50),
	sref VARCHAR(50),
	cchRefWdbeMMachine BIGINT UNSIGNED,
	Comment TEXT,
	INDEX (srefKPlatform),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMModule(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixVBasetype INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	hkNum INT UNSIGNED,
	supRefWdbeMModule BIGINT UNSIGNED,
	tplRefWdbeMModule BIGINT UNSIGNED,
	refWdbeMController BIGINT UNSIGNED,
	refWdbeMImbuf BIGINT UNSIGNED,
	sref VARCHAR(50),
	Srefrule VARCHAR(192),
	Comment TEXT,
	INDEX (ixVBasetype),
	INDEX (hkIxVTbl),
	INDEX (hkUref),
	INDEX (hkNum),
	INDEX (supRefWdbeMModule),
	INDEX (tplRefWdbeMModule),
	INDEX (refWdbeMController),
	INDEX (refWdbeMImbuf),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMPeripheral(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUnit BIGINT UNSIGNED,
	refWdbeMModule BIGINT UNSIGNED,
	sref VARCHAR(50),
	Comment TEXT,
	INDEX (refWdbeMUnit),
	INDEX (refWdbeMModule),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMPerson(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	ixWDerivate INT UNSIGNED,
	ixVSex INT UNSIGNED,
	Title VARCHAR(30),
	Firstname VARCHAR(30),
	refJLastname BIGINT UNSIGNED,
	Lastname VARCHAR(50),
	telRefADetail BIGINT UNSIGNED,
	telVal VARCHAR(192),
	emlRefADetail BIGINT UNSIGNED,
	emlVal VARCHAR(192),
	Salutation VARCHAR(100),
	INDEX (grp),
	INDEX (own),
	INDEX (ixWDerivate),
	INDEX (Lastname)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMPin(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeCPin BIGINT UNSIGNED,
	refWdbeMBank BIGINT UNSIGNED,
	refJSref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Location VARCHAR(5),
	INDEX (refWdbeCPin),
	INDEX (refWdbeMBank),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMPort(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeCPort BIGINT UNSIGNED,
	mdlRefWdbeMModule BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	mdlIxVCat INT UNSIGNED,
	sref VARCHAR(50),
	ixVDir INT UNSIGNED,
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	Defval TEXT,
	cpiSrefWdbeMPin VARCHAR(50),
	cprSrefWdbeMPort VARCHAR(50),
	csiSrefWdbeMSignal VARCHAR(50),
	Comment TEXT,
	INDEX (refWdbeCPort),
	INDEX (mdlRefWdbeMModule),
	INDEX (mdlNum),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMProcess(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMModule BIGINT UNSIGNED,
	refWdbeMFsm BIGINT UNSIGNED,
	sref VARCHAR(50),
	clkSrefWdbeMSignal VARCHAR(50),
	asrSrefWdbeMSignal VARCHAR(50),
	Falling TINYINT,
	Syncrst VARCHAR(192),
	Extip TINYINT,
	Comment TEXT,
	INDEX (refWdbeMModule),
	INDEX (refWdbeMFsm),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMProject(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refWdbeMVersion BIGINT UNSIGNED,
	Short VARCHAR(5),
	Title VARCHAR(50),
	Easy TINYINT,
	Giturl VARCHAR(192),
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refWdbeMVersion),
	INDEX (Short),
	INDEX (Title)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMRelease(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixVBasetype INT UNSIGNED,
	refWdbeMVersion BIGINT UNSIGNED,
	refWdbeMMachine BIGINT UNSIGNED,
	sref VARCHAR(50),
	srefsKOption VARCHAR(192),
	Comment TEXT,
	INDEX (ixVBasetype),
	INDEX (refWdbeMVersion),
	INDEX (refWdbeMMachine),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMSession(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUser BIGINT UNSIGNED,
	start INT UNSIGNED,
	stop INT UNSIGNED,
	Ip VARCHAR(30),
	INDEX (refWdbeMUser),
	INDEX (start)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMSignal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixVBasetype INT UNSIGNED,
	refWdbeCSignal BIGINT UNSIGNED,
	mdlRefWdbeMModule BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	mgeIxVTbl INT UNSIGNED,
	mgeUref BIGINT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	sref VARCHAR(50),
	Const TINYINT,
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	Comb VARCHAR(192),
	Onval TEXT,
	Offval TEXT,
	Defon TINYINT,
	drvRefWdbeMPort BIGINT UNSIGNED,
	Comment TEXT,
	INDEX (ixVBasetype),
	INDEX (refWdbeCSignal),
	INDEX (mdlRefWdbeMModule),
	INDEX (mdlNum),
	INDEX (mgeIxVTbl),
	INDEX (mgeUref),
	INDEX (refWdbeMVector),
	INDEX (sref),
	INDEX (Const)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMSystem(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMVersion BIGINT UNSIGNED,
	refWdbeMUnit BIGINT UNSIGNED,
	sref VARCHAR(50),
	Comment TEXT,
	INDEX (refWdbeMVersion),
	INDEX (refWdbeMUnit),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMTarget(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	sysRefWdbeMSystem BIGINT UNSIGNED,
	sysNum INT UNSIGNED,
	refWdbeMUnit BIGINT UNSIGNED,
	sref VARCHAR(50),
	rteSrefsWdbeMModule VARCHAR(192),
	Comment TEXT,
	INDEX (sysRefWdbeMSystem),
	INDEX (sysNum),
	INDEX (refWdbeMUnit),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMUnit(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixVBasetype INT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	silRefWdbeMUnit BIGINT UNSIGNED,
	refWdbeMSystem BIGINT UNSIGNED,
	refWdbeMModule BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(192),
	Fullsref VARCHAR(50),
	srefKPackage VARCHAR(50),
	Easy TINYINT,
	srefKToolch VARCHAR(50),
	Comment TEXT,
	INDEX (ixVBasetype),
	INDEX (refIxVTbl),
	INDEX (refUref),
	INDEX (silRefWdbeMUnit),
	INDEX (refWdbeMSystem),
	INDEX (refWdbeMModule),
	INDEX (sref),
	INDEX (Title)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMUser(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refRUsergroup BIGINT UNSIGNED,
	refWdbeMUsergroup BIGINT UNSIGNED,
	refWdbeMPerson BIGINT UNSIGNED,
	sref VARCHAR(50),
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	ixWdbeVLocale INT UNSIGNED,
	ixWdbeVUserlevel INT UNSIGNED,
	Password VARCHAR(30),
	Fullkey TEXT,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refWdbeMUsergroup),
	INDEX (refWdbeMPerson),
	INDEX (sref),
	INDEX (refJState),
	INDEX (ixVState)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMUsergroup(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	sref VARCHAR(50),
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMVariable(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeCVariable BIGINT UNSIGNED,
	prcRefWdbeMProcess BIGINT UNSIGNED,
	prcNum INT UNSIGNED,
	sref VARCHAR(50),
	Const TINYINT,
	Falling TINYINT,
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	Onval TEXT,
	Offval TEXT,
	Defon TINYINT,
	Comment TEXT,
	INDEX (refWdbeCVariable),
	INDEX (prcRefWdbeMProcess),
	INDEX (prcNum),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMVector(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixVBasetype INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	sref VARCHAR(50),
	srefsKOption VARCHAR(192),
	INDEX (ixVBasetype),
	INDEX (hkIxVTbl),
	INDEX (hkUref),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMVectoritem(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	vecRefWdbeMVector BIGINT UNSIGNED,
	vecNum INT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (vecRefWdbeMVector),
	INDEX (vecNum),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeMVersion(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refWdbeMProject BIGINT UNSIGNED,
	bvrRefWdbeMVersion BIGINT UNSIGNED,
	Major SMALLINT UNSIGNED,
	Minor SMALLINT UNSIGNED,
	Sub SMALLINT UNSIGNED,
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	About TEXT,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refWdbeMProject),
	INDEX (bvrRefWdbeMVersion),
	INDEX (ixVState)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeRMCommandMController(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMCommand BIGINT UNSIGNED,
	refWdbeMController BIGINT UNSIGNED,
	ivrRefWdbeMSignal BIGINT UNSIGNED,
	rvrRefWdbeMSignal BIGINT UNSIGNED,
	INDEX (refWdbeMCommand),
	INDEX (refWdbeMController)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeRMCoreprojectMPerson(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	x1Startd INT UNSIGNED,
	x1Stopd INT UNSIGNED,
	refWdbeMCoreproject BIGINT UNSIGNED,
	refWdbeMPerson BIGINT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (x1Startd),
	INDEX (x1Stopd),
	INDEX (refWdbeMCoreproject),
	INDEX (refWdbeMPerson)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeRMLibraryMVersion(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMLibrary BIGINT UNSIGNED,
	refWdbeMVersion BIGINT UNSIGNED,
	INDEX (refWdbeMLibrary),
	INDEX (refWdbeMVersion)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeRMPersonMProject(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	x1Startd INT UNSIGNED,
	x1Stopd INT UNSIGNED,
	refWdbeMPerson BIGINT UNSIGNED,
	refWdbeMProject BIGINT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (x1Startd),
	INDEX (x1Stopd),
	INDEX (refWdbeMPerson),
	INDEX (refWdbeMProject)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeRMUsergroupUniversal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUsergroup BIGINT UNSIGNED,
	unvIxWdbeVMaintable INT UNSIGNED,
	unvUref BIGINT UNSIGNED,
	ixWdbeVRecaccess INT UNSIGNED,
	INDEX (refWdbeMUsergroup),
	INDEX (unvIxWdbeVMaintable),
	INDEX (unvUref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeRMUserMUsergroup(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWdbeMUser BIGINT UNSIGNED,
	refWdbeMUsergroup BIGINT UNSIGNED,
	ixWdbeVUserlevel INT UNSIGNED,
	INDEX (refWdbeMUser),
	INDEX (refWdbeMUsergroup)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQBnk1NPin(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQBnkList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	refWdbeMUnit BIGINT UNSIGNED,
	srefKVoltstd VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQCmdAInvpar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	cmdNum INT UNSIGNED,
	sref VARCHAR(50),
	ixWdbeVPartype INT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	Length TINYINT UNSIGNED,
	Defval TEXT,
	refWdbeMVectoritem BIGINT UNSIGNED,
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQCmdARetpar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	cmdNum INT UNSIGNED,
	sref VARCHAR(50),
	ixWdbeVPartype INT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	Length TINYINT UNSIGNED,
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQCmdList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Fullsref VARCHAR(50),
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	ixVRettype INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQCmdMNController(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ivrRefWdbeMSignal BIGINT UNSIGNED,
	rvrRefWdbeMSignal BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQCpr1NCoreversion(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQCprList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	refWdbeMCoreversion BIGINT UNSIGNED,
	Giturl VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQCprMNPerson(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	x1Stopd INT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQCvrAIp(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	cvrNum INT UNSIGNED,
	sref VARCHAR(50),
	ixVTagtype INT UNSIGNED,
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQCvrAPlh(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	cvrNum INT UNSIGNED,
	sref VARCHAR(50),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQCvrBcv1NCoreversion(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQCvrHk1NModule(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	hkNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQCvrList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refWdbeMCoreproject BIGINT UNSIGNED,
	Major SMALLINT UNSIGNED,
	Minor SMALLINT UNSIGNED,
	Sub SMALLINT UNSIGNED,
	bcvRefWdbeMCoreversion BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQErrAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	errNum INT UNSIGNED,
	sref VARCHAR(50),
	ixWdbeVPartype INT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	Length TINYINT UNSIGNED,
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQErrList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Fullsref VARCHAR(50),
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQFam1NUnit(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQFamList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	srefKVendor VARCHAR(50),
	Title VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQFilList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	Filename VARCHAR(50),
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	osrefKContent VARCHAR(50),
	srefKMimetype VARCHAR(50),
	Size SMALLINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQFstAStep(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	fstNum INT UNSIGNED,
	fnxRefWdbeMFsmstate BIGINT UNSIGNED,
	Cond1 TEXT,
	Ip1 VARCHAR(50),
	Cond2 TEXT,
	Ip2 VARCHAR(50),
	Cond3 TEXT,
	Ip3 VARCHAR(50),
	Cond4 TEXT,
	Ip4 VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQFstList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	fsmRefWdbeMFsm BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQGenList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	mdlRefWdbeMModule BIGINT UNSIGNED,
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQLibAMakefile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1RefWdbeMMachine BIGINT UNSIGNED,
	x2SrefKTag VARCHAR(50),
	Val TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQLibList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(50),
	Version VARCHAR(30),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQLibMNVersion(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMch1NRelease(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMchAMakefile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKTag VARCHAR(50),
	Val TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMchAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMchList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	srefKPlatform VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMod1NPeripheral(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMod1NProcess(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQModAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQModCor1NImbuf(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQModCtrHk1NVector(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQModCtrMNCommand(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ivrRefWdbeMSignal BIGINT UNSIGNED,
	rvrRefWdbeMSignal BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQModCtrRef1NCommand(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQModCtrRef1NError(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQModKHdltype(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(1024),
	Implied VARCHAR(1024),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQModList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	supRefWdbeMModule BIGINT UNSIGNED,
	tplRefWdbeMModule BIGINT UNSIGNED,
	Srefrule VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQModMdl1NGeneric(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQModMdl1NPort(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQModMdl1NSignal(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQModMge1NSignal(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQModSup1NModule(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMtpAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMtpKHdltype(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(1024),
	Implied VARCHAR(1024),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMtpKParKey(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(1024),
	Implied VARCHAR(1024),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMtpList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	Srefrule VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMtpMdl1NGeneric(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMtpMdl1NPort(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	mdlNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMtpMge1NSignal(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMtpRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMtpSup1NModule(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQMtpTpl1NModule(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPinAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPinList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	refWdbeMBank BIGINT UNSIGNED,
	Location VARCHAR(5),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPphAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPphList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	refWdbeMUnit BIGINT UNSIGNED,
	refWdbeMModule BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPrcFsmFsm1NFsmstate(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	fsmNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPrcKHdltype(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(1024),
	Implied VARCHAR(1024),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPrcList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	refWdbeMModule BIGINT UNSIGNED,
	Falling TINYINT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPrcMge1NSignal(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPrcPrc1NVariable(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	prcNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPreselect(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPrj1NVersion(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPrjList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	Short VARCHAR(5),
	Title VARCHAR(50),
	refWdbeMVersion BIGINT UNSIGNED,
	Easy TINYINT,
	Giturl VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPrjMNPerson(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	x1Stopd INT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPrsADetail(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKType VARCHAR(50),
	Val VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPrsList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	Title VARCHAR(30),
	Firstname VARCHAR(30),
	Lastname VARCHAR(50),
	ixVSex INT UNSIGNED,
	telVal VARCHAR(192),
	emlVal VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPrsMNCoreproject(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	x1Stopd INT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPrsMNProject(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	x1Stopd INT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQPrtList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	mdlRefWdbeMModule BIGINT UNSIGNED,
	mdlIxVCat INT UNSIGNED,
	ixVDir INT UNSIGNED,
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQRlsList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	refWdbeMVersion BIGINT UNSIGNED,
	refWdbeMMachine BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQSelect(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ix INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (ix)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQSigList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	mdlRefWdbeMModule BIGINT UNSIGNED,
	mgeIxVTbl INT UNSIGNED,
	mgeUref BIGINT UNSIGNED,
	refWdbeMVector BIGINT UNSIGNED,
	Const TINYINT,
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQSil1NBank(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQSil1NPeripheral(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQSil1NTarget(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQSilFwd1NController(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQSilHk1NModule(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	hkNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQSilHk1NVector(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQSilList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(192),
	Fullsref VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	refWdbeMSystem BIGINT UNSIGNED,
	refWdbeMModule BIGINT UNSIGNED,
	srefKPackage VARCHAR(50),
	Easy TINYINT,
	srefKToolch VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQSilRef1NCommand(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQSilRef1NError(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQSilSil1NUnit(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQSysHk1NVector(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQSysList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	refWdbeMVersion BIGINT UNSIGNED,
	refWdbeMUnit BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQSysSys1NTarget(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sysNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQTrgList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	sysRefWdbeMSystem BIGINT UNSIGNED,
	refWdbeMUnit BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUnt1NBank(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUnt1NPeripheral(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUnt1NTarget(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUntFwd1NController(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUntHk1NModule(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	hkNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUntHk1NVector(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUntList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(192),
	Fullsref VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	refWdbeMSystem BIGINT UNSIGNED,
	refWdbeMModule BIGINT UNSIGNED,
	srefKPackage VARCHAR(50),
	Easy TINYINT,
	srefKToolch VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUntRef1NCommand(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUntRef1NError(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUntSil1NUnit(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUsgAAccess(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1IxWdbeVFeatgroup INT UNSIGNED,
	x2FeaSrefUix VARCHAR(50),
	ixWdbeWAccess INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUsgList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	sref VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUsgMNUser(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ixWdbeVUserlevel INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUsr1NSession(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUsrAAccess(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1IxWdbeVFeatgroup INT UNSIGNED,
	x2FeaSrefUix VARCHAR(50),
	ixWdbeWAccess INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUsrList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refWdbeMPerson BIGINT UNSIGNED,
	sref VARCHAR(50),
	refWdbeMUsergroup BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	ixWdbeVLocale INT UNSIGNED,
	ixWdbeVUserlevel INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQUsrMNUsergroup(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ixWdbeVUserlevel INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQVarList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	prcRefWdbeMProcess BIGINT UNSIGNED,
	Const TINYINT,
	Falling TINYINT,
	srefWdbeKHdltype VARCHAR(50),
	Width SMALLINT UNSIGNED,
	Minmax VARCHAR(30),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQVecList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	ixVBasetype INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQVecVec1NVectoritem(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	vecNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQVer1NRelease(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQVer1NSystem(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQVer1NUnit(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQVerBvr1NVersion(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQVerList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refWdbeMProject BIGINT UNSIGNED,
	Major SMALLINT UNSIGNED,
	Minor SMALLINT UNSIGNED,
	Sub SMALLINT UNSIGNED,
	bvrRefWdbeMVersion BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQVerMNLibrary(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQVerRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblWdbeQVitList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(192),
	vecRefWdbeMVector BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

