# file Makefile.inc
# make file paths for Wdbe daemon, release wdbed_awsubt
# author Alexander Wirthmueller
# date created: 23 Aug 2020
# modified: 23 Aug 2020

SRCROOT = /home/ubuntu/src
LIBROOT = /home/ubuntu/lib
BINROOT = /home/ubuntu/bin

