# file Makefile.inc
# make file paths for Wdbe operation daemon, release wdbeopd1_mac
# copyright: (C) 2016-2020 MPSI Technologies GmbH
# author: Alexander Wirthmueller (auto-generation)
# date created: 3 Mar 2025
# IP header --- ABOVE

BUILDROOT = ${WHIZSDKROOT}/build
LIBROOT = ${WHIZSDKROOT}/lib
BINROOT = ${WHIZROOT}/bin
