# file Makefile.inc
# make file paths for Wdbe operation daemon, release wdbeopd1_ungenio
# author Alexander Wirthmueller
# date created: 11 Jul 2020
# modified: 11 Jul 2020

SRCROOT = /Users/mpsitech/src
LIBROOT = /Users/mpsitech/lib
BINROOT = /Users/mpsitech/bin

