# file Makefile.inc
# make file paths for Wdbe combined daemon, release wdbecmbd_jack
# author Alexander Wirthmueller
# date created: 23 Aug 2020
# modified: 23 Aug 2020

SRCROOT = /home/mpsitech/src
LIBROOT = /home/mpsitech/lib
BINROOT = /home/mpsitech/bin

