/**
	* \file VecWdbeVDpch.h
	* vector VecWdbeVDpch (implementation)
	* \author Alexander Wirthmueller
	* \date created: 11 Jul 2020
	* \date modified: 11 Jul 2020
	*/

#include "VecWdbeVDpch.h"

using namespace std;
using namespace Sbecore;

/******************************************************************************
 namespace VecWdbeVDpch
 ******************************************************************************/

uint VecWdbeVDpch::getIx(
			const string& sref
		) {
	string s = StrMod::lc(sref);

	if (s == "dpchengdlgwdbecprnewdata") return DPCHENGDLGWDBECPRNEWDATA;
	if (s == "dpchengdlgwdbecvrbsccddata") return DPCHENGDLGWDBECVRBSCCDDATA;
	if (s == "dpchengdlgwdbecvrdetcddata") return DPCHENGDLGWDBECVRDETCDDATA;
	if (s == "dpchengdlgwdbecvrnewdata") return DPCHENGDLGWDBECVRNEWDATA;
	if (s == "dpchengdlgwdbecvrwritedata") return DPCHENGDLGWDBECVRWRITEDATA;
	if (s == "dpchengdlgwdbefildownloaddata") return DPCHENGDLGWDBEFILDOWNLOADDATA;
	if (s == "dpchengdlgwdbefilnewdata") return DPCHENGDLGWDBEFILNEWDATA;
	if (s == "dpchengdlgwdbenavloainidata") return DPCHENGDLGWDBENAVLOAINIDATA;
	if (s == "dpchengdlgwdbenavmnglicdata") return DPCHENGDLGWDBENAVMNGLICDATA;
	if (s == "dpchengdlgwdbeprjimpexdata") return DPCHENGDLGWDBEPRJIMPEXDATA;
	if (s == "dpchengdlgwdbeprjnewdata") return DPCHENGDLGWDBEPRJNEWDATA;
	if (s == "dpchengdlgwdberlsfinreptrdata") return DPCHENGDLGWDBERLSFINREPTRDATA;
	if (s == "dpchengdlgwdberlsnewdata") return DPCHENGDLGWDBERLSNEWDATA;
	if (s == "dpchengdlgwdberlsstareptrdata") return DPCHENGDLGWDBERLSSTAREPTRDATA;
	if (s == "dpchengdlgwdberlswritedata") return DPCHENGDLGWDBERLSWRITEDATA;
	if (s == "dpchengdlgwdbeusrmngkeypairdata") return DPCHENGDLGWDBEUSRMNGKEYPAIRDATA;
	if (s == "dpchengdlgwdbeutlextripdata") return DPCHENGDLGWDBEUTLEXTRIPDATA;
	if (s == "dpchengdlgwdbeutliexconvdata") return DPCHENGDLGWDBEUTLIEXCONVDATA;
	if (s == "dpchengdlgwdbeutlmrgipdata") return DPCHENGDLGWDBEUTLMRGIPDATA;
	if (s == "dpchengdlgwdbeverbscdddata") return DPCHENGDLGWDBEVERBSCDDDATA;
	if (s == "dpchengdlgwdbeverdetdddata") return DPCHENGDLGWDBEVERDETDDDATA;
	if (s == "dpchengdlgwdbevernewdata") return DPCHENGDLGWDBEVERNEWDATA;
	if (s == "dpchengrootwdbedata") return DPCHENGROOTWDBEDATA;
	if (s == "dpchengsesswdbedata") return DPCHENGSESSWDBEDATA;
	if (s == "dpchengwdbeack") return DPCHENGWDBEACK;
	if (s == "dpchengwdbealert") return DPCHENGWDBEALERT;
	if (s == "dpchengwdbebnk1npindata") return DPCHENGWDBEBNK1NPINDATA;
	if (s == "dpchengwdbebnkdata") return DPCHENGWDBEBNKDATA;
	if (s == "dpchengwdbebnkdetaildata") return DPCHENGWDBEBNKDETAILDATA;
	if (s == "dpchengwdbebnkheadbardata") return DPCHENGWDBEBNKHEADBARDATA;
	if (s == "dpchengwdbebnklistdata") return DPCHENGWDBEBNKLISTDATA;
	if (s == "dpchengwdbebnkrecdata") return DPCHENGWDBEBNKRECDATA;
	if (s == "dpchengwdbecmdainvpardata") return DPCHENGWDBECMDAINVPARDATA;
	if (s == "dpchengwdbecmdaretpardata") return DPCHENGWDBECMDARETPARDATA;
	if (s == "dpchengwdbecmddata") return DPCHENGWDBECMDDATA;
	if (s == "dpchengwdbecmddetaildata") return DPCHENGWDBECMDDETAILDATA;
	if (s == "dpchengwdbecmdheadbardata") return DPCHENGWDBECMDHEADBARDATA;
	if (s == "dpchengwdbecmdlistdata") return DPCHENGWDBECMDLISTDATA;
	if (s == "dpchengwdbecmdmncontrollerdata") return DPCHENGWDBECMDMNCONTROLLERDATA;
	if (s == "dpchengwdbecmdrecdata") return DPCHENGWDBECMDRECDATA;
	if (s == "dpchengwdbeconfirm") return DPCHENGWDBECONFIRM;
	if (s == "dpchengwdbecpr1ncoreversiondata") return DPCHENGWDBECPR1NCOREVERSIONDATA;
	if (s == "dpchengwdbecprdata") return DPCHENGWDBECPRDATA;
	if (s == "dpchengwdbecprdetaildata") return DPCHENGWDBECPRDETAILDATA;
	if (s == "dpchengwdbecprheadbardata") return DPCHENGWDBECPRHEADBARDATA;
	if (s == "dpchengwdbecprlistdata") return DPCHENGWDBECPRLISTDATA;
	if (s == "dpchengwdbecprmnpersondata") return DPCHENGWDBECPRMNPERSONDATA;
	if (s == "dpchengwdbecprrecdata") return DPCHENGWDBECPRRECDATA;
	if (s == "dpchengwdbecvraipdata") return DPCHENGWDBECVRAIPDATA;
	if (s == "dpchengwdbecvraplhdata") return DPCHENGWDBECVRAPLHDATA;
	if (s == "dpchengwdbecvrbcv1ncoreversiondata") return DPCHENGWDBECVRBCV1NCOREVERSIONDATA;
	if (s == "dpchengwdbecvrdata") return DPCHENGWDBECVRDATA;
	if (s == "dpchengwdbecvrdetaildata") return DPCHENGWDBECVRDETAILDATA;
	if (s == "dpchengwdbecvrheadbardata") return DPCHENGWDBECVRHEADBARDATA;
	if (s == "dpchengwdbecvrhk1nmoduledata") return DPCHENGWDBECVRHK1NMODULEDATA;
	if (s == "dpchengwdbecvrlistdata") return DPCHENGWDBECVRLISTDATA;
	if (s == "dpchengwdbecvrrecdata") return DPCHENGWDBECVRRECDATA;
	if (s == "dpchengwdbeerrapardata") return DPCHENGWDBEERRAPARDATA;
	if (s == "dpchengwdbeerrdata") return DPCHENGWDBEERRDATA;
	if (s == "dpchengwdbeerrdetaildata") return DPCHENGWDBEERRDETAILDATA;
	if (s == "dpchengwdbeerrheadbardata") return DPCHENGWDBEERRHEADBARDATA;
	if (s == "dpchengwdbeerrlistdata") return DPCHENGWDBEERRLISTDATA;
	if (s == "dpchengwdbeerrrecdata") return DPCHENGWDBEERRRECDATA;
	if (s == "dpchengwdbefam1nunitdata") return DPCHENGWDBEFAM1NUNITDATA;
	if (s == "dpchengwdbefamdata") return DPCHENGWDBEFAMDATA;
	if (s == "dpchengwdbefamdetaildata") return DPCHENGWDBEFAMDETAILDATA;
	if (s == "dpchengwdbefamheadbardata") return DPCHENGWDBEFAMHEADBARDATA;
	if (s == "dpchengwdbefamlistdata") return DPCHENGWDBEFAMLISTDATA;
	if (s == "dpchengwdbefamrecdata") return DPCHENGWDBEFAMRECDATA;
	if (s == "dpchengwdbefildata") return DPCHENGWDBEFILDATA;
	if (s == "dpchengwdbefildetaildata") return DPCHENGWDBEFILDETAILDATA;
	if (s == "dpchengwdbefilheadbardata") return DPCHENGWDBEFILHEADBARDATA;
	if (s == "dpchengwdbefillistdata") return DPCHENGWDBEFILLISTDATA;
	if (s == "dpchengwdbefilrecdata") return DPCHENGWDBEFILRECDATA;
	if (s == "dpchengwdbefstastepdata") return DPCHENGWDBEFSTASTEPDATA;
	if (s == "dpchengwdbefstdata") return DPCHENGWDBEFSTDATA;
	if (s == "dpchengwdbefstdetaildata") return DPCHENGWDBEFSTDETAILDATA;
	if (s == "dpchengwdbefstheadbardata") return DPCHENGWDBEFSTHEADBARDATA;
	if (s == "dpchengwdbefstlistdata") return DPCHENGWDBEFSTLISTDATA;
	if (s == "dpchengwdbefstrecdata") return DPCHENGWDBEFSTRECDATA;
	if (s == "dpchengwdbegendata") return DPCHENGWDBEGENDATA;
	if (s == "dpchengwdbegendetaildata") return DPCHENGWDBEGENDETAILDATA;
	if (s == "dpchengwdbegenheadbardata") return DPCHENGWDBEGENHEADBARDATA;
	if (s == "dpchengwdbegenlistdata") return DPCHENGWDBEGENLISTDATA;
	if (s == "dpchengwdbegenrecdata") return DPCHENGWDBEGENRECDATA;
	if (s == "dpchengwdbelibamakefiledata") return DPCHENGWDBELIBAMAKEFILEDATA;
	if (s == "dpchengwdbelibdata") return DPCHENGWDBELIBDATA;
	if (s == "dpchengwdbelibdetaildata") return DPCHENGWDBELIBDETAILDATA;
	if (s == "dpchengwdbelibheadbardata") return DPCHENGWDBELIBHEADBARDATA;
	if (s == "dpchengwdbeliblistdata") return DPCHENGWDBELIBLISTDATA;
	if (s == "dpchengwdbelibmnversiondata") return DPCHENGWDBELIBMNVERSIONDATA;
	if (s == "dpchengwdbelibrecdata") return DPCHENGWDBELIBRECDATA;
	if (s == "dpchengwdbemch1nreleasedata") return DPCHENGWDBEMCH1NRELEASEDATA;
	if (s == "dpchengwdbemchamakefiledata") return DPCHENGWDBEMCHAMAKEFILEDATA;
	if (s == "dpchengwdbemchapardata") return DPCHENGWDBEMCHAPARDATA;
	if (s == "dpchengwdbemchdata") return DPCHENGWDBEMCHDATA;
	if (s == "dpchengwdbemchdetaildata") return DPCHENGWDBEMCHDETAILDATA;
	if (s == "dpchengwdbemchheadbardata") return DPCHENGWDBEMCHHEADBARDATA;
	if (s == "dpchengwdbemchlistdata") return DPCHENGWDBEMCHLISTDATA;
	if (s == "dpchengwdbemchrecdata") return DPCHENGWDBEMCHRECDATA;
	if (s == "dpchengwdbemod1nperipheraldata") return DPCHENGWDBEMOD1NPERIPHERALDATA;
	if (s == "dpchengwdbemod1nprocessdata") return DPCHENGWDBEMOD1NPROCESSDATA;
	if (s == "dpchengwdbemodapardata") return DPCHENGWDBEMODAPARDATA;
	if (s == "dpchengwdbemodcor1nimbufdata") return DPCHENGWDBEMODCOR1NIMBUFDATA;
	if (s == "dpchengwdbemodctrhk1nvectordata") return DPCHENGWDBEMODCTRHK1NVECTORDATA;
	if (s == "dpchengwdbemodctrmncommanddata") return DPCHENGWDBEMODCTRMNCOMMANDDATA;
	if (s == "dpchengwdbemodctrref1ncommanddata") return DPCHENGWDBEMODCTRREF1NCOMMANDDATA;
	if (s == "dpchengwdbemodctrref1nerrordata") return DPCHENGWDBEMODCTRREF1NERRORDATA;
	if (s == "dpchengwdbemoddata") return DPCHENGWDBEMODDATA;
	if (s == "dpchengwdbemoddetaildata") return DPCHENGWDBEMODDETAILDATA;
	if (s == "dpchengwdbemodheadbardata") return DPCHENGWDBEMODHEADBARDATA;
	if (s == "dpchengwdbemodkhdltypedata") return DPCHENGWDBEMODKHDLTYPEDATA;
	if (s == "dpchengwdbemodlistdata") return DPCHENGWDBEMODLISTDATA;
	if (s == "dpchengwdbemodmdl1ngenericdata") return DPCHENGWDBEMODMDL1NGENERICDATA;
	if (s == "dpchengwdbemodmdl1nportdata") return DPCHENGWDBEMODMDL1NPORTDATA;
	if (s == "dpchengwdbemodmdl1nsignaldata") return DPCHENGWDBEMODMDL1NSIGNALDATA;
	if (s == "dpchengwdbemodmge1nsignaldata") return DPCHENGWDBEMODMGE1NSIGNALDATA;
	if (s == "dpchengwdbemodrecdata") return DPCHENGWDBEMODRECDATA;
	if (s == "dpchengwdbemodsup1nmoduledata") return DPCHENGWDBEMODSUP1NMODULEDATA;
	if (s == "dpchengwdbemtpapardata") return DPCHENGWDBEMTPAPARDATA;
	if (s == "dpchengwdbemtpdata") return DPCHENGWDBEMTPDATA;
	if (s == "dpchengwdbemtpdetaildata") return DPCHENGWDBEMTPDETAILDATA;
	if (s == "dpchengwdbemtpheadbardata") return DPCHENGWDBEMTPHEADBARDATA;
	if (s == "dpchengwdbemtpkhdltypedata") return DPCHENGWDBEMTPKHDLTYPEDATA;
	if (s == "dpchengwdbemtpkparkeydata") return DPCHENGWDBEMTPKPARKEYDATA;
	if (s == "dpchengwdbemtplistdata") return DPCHENGWDBEMTPLISTDATA;
	if (s == "dpchengwdbemtpmdl1ngenericdata") return DPCHENGWDBEMTPMDL1NGENERICDATA;
	if (s == "dpchengwdbemtpmdl1nportdata") return DPCHENGWDBEMTPMDL1NPORTDATA;
	if (s == "dpchengwdbemtpmge1nsignaldata") return DPCHENGWDBEMTPMGE1NSIGNALDATA;
	if (s == "dpchengwdbemtprecdata") return DPCHENGWDBEMTPRECDATA;
	if (s == "dpchengwdbemtpref1nfiledata") return DPCHENGWDBEMTPREF1NFILEDATA;
	if (s == "dpchengwdbemtpsup1nmoduledata") return DPCHENGWDBEMTPSUP1NMODULEDATA;
	if (s == "dpchengwdbemtptpl1nmoduledata") return DPCHENGWDBEMTPTPL1NMODULEDATA;
	if (s == "dpchengwdbenavadmindata") return DPCHENGWDBENAVADMINDATA;
	if (s == "dpchengwdbenavauxfctdata") return DPCHENGWDBENAVAUXFCTDATA;
	if (s == "dpchengwdbenavcoredevdata") return DPCHENGWDBENAVCOREDEVDATA;
	if (s == "dpchengwdbenavdata") return DPCHENGWDBENAVDATA;
	if (s == "dpchengwdbenavdescrdata") return DPCHENGWDBENAVDESCRDATA;
	if (s == "dpchengwdbenavdevdevdata") return DPCHENGWDBENAVDEVDEVDATA;
	if (s == "dpchengwdbenavglobaldata") return DPCHENGWDBENAVGLOBALDATA;
	if (s == "dpchengwdbenavheadbardata") return DPCHENGWDBENAVHEADBARDATA;
	if (s == "dpchengwdbenavpredata") return DPCHENGWDBENAVPREDATA;
	if (s == "dpchengwdbepinapardata") return DPCHENGWDBEPINAPARDATA;
	if (s == "dpchengwdbepindata") return DPCHENGWDBEPINDATA;
	if (s == "dpchengwdbepindetaildata") return DPCHENGWDBEPINDETAILDATA;
	if (s == "dpchengwdbepinheadbardata") return DPCHENGWDBEPINHEADBARDATA;
	if (s == "dpchengwdbepinlistdata") return DPCHENGWDBEPINLISTDATA;
	if (s == "dpchengwdbepinrecdata") return DPCHENGWDBEPINRECDATA;
	if (s == "dpchengwdbepphapardata") return DPCHENGWDBEPPHAPARDATA;
	if (s == "dpchengwdbepphdata") return DPCHENGWDBEPPHDATA;
	if (s == "dpchengwdbepphdetaildata") return DPCHENGWDBEPPHDETAILDATA;
	if (s == "dpchengwdbepphheadbardata") return DPCHENGWDBEPPHHEADBARDATA;
	if (s == "dpchengwdbepphlistdata") return DPCHENGWDBEPPHLISTDATA;
	if (s == "dpchengwdbepphrecdata") return DPCHENGWDBEPPHRECDATA;
	if (s == "dpchengwdbeprcdata") return DPCHENGWDBEPRCDATA;
	if (s == "dpchengwdbeprcdetaildata") return DPCHENGWDBEPRCDETAILDATA;
	if (s == "dpchengwdbeprcfsmfsm1nfsmstatedata") return DPCHENGWDBEPRCFSMFSM1NFSMSTATEDATA;
	if (s == "dpchengwdbeprcheadbardata") return DPCHENGWDBEPRCHEADBARDATA;
	if (s == "dpchengwdbeprckhdltypedata") return DPCHENGWDBEPRCKHDLTYPEDATA;
	if (s == "dpchengwdbeprclistdata") return DPCHENGWDBEPRCLISTDATA;
	if (s == "dpchengwdbeprcmge1nsignaldata") return DPCHENGWDBEPRCMGE1NSIGNALDATA;
	if (s == "dpchengwdbeprcprc1nvariabledata") return DPCHENGWDBEPRCPRC1NVARIABLEDATA;
	if (s == "dpchengwdbeprcrecdata") return DPCHENGWDBEPRCRECDATA;
	if (s == "dpchengwdbeprj1nversiondata") return DPCHENGWDBEPRJ1NVERSIONDATA;
	if (s == "dpchengwdbeprjdata") return DPCHENGWDBEPRJDATA;
	if (s == "dpchengwdbeprjdetaildata") return DPCHENGWDBEPRJDETAILDATA;
	if (s == "dpchengwdbeprjheadbardata") return DPCHENGWDBEPRJHEADBARDATA;
	if (s == "dpchengwdbeprjlistdata") return DPCHENGWDBEPRJLISTDATA;
	if (s == "dpchengwdbeprjmnpersondata") return DPCHENGWDBEPRJMNPERSONDATA;
	if (s == "dpchengwdbeprjrecdata") return DPCHENGWDBEPRJRECDATA;
	if (s == "dpchengwdbeprsadetaildata") return DPCHENGWDBEPRSADETAILDATA;
	if (s == "dpchengwdbeprsdata") return DPCHENGWDBEPRSDATA;
	if (s == "dpchengwdbeprsdetaildata") return DPCHENGWDBEPRSDETAILDATA;
	if (s == "dpchengwdbeprsheadbardata") return DPCHENGWDBEPRSHEADBARDATA;
	if (s == "dpchengwdbeprslistdata") return DPCHENGWDBEPRSLISTDATA;
	if (s == "dpchengwdbeprsmncoreprojectdata") return DPCHENGWDBEPRSMNCOREPROJECTDATA;
	if (s == "dpchengwdbeprsmnprojectdata") return DPCHENGWDBEPRSMNPROJECTDATA;
	if (s == "dpchengwdbeprsrecdata") return DPCHENGWDBEPRSRECDATA;
	if (s == "dpchengwdbeprtdata") return DPCHENGWDBEPRTDATA;
	if (s == "dpchengwdbeprtdetaildata") return DPCHENGWDBEPRTDETAILDATA;
	if (s == "dpchengwdbeprtheadbardata") return DPCHENGWDBEPRTHEADBARDATA;
	if (s == "dpchengwdbeprtlistdata") return DPCHENGWDBEPRTLISTDATA;
	if (s == "dpchengwdbeprtrecdata") return DPCHENGWDBEPRTRECDATA;
	if (s == "dpchengwdberlsdata") return DPCHENGWDBERLSDATA;
	if (s == "dpchengwdberlsdetaildata") return DPCHENGWDBERLSDETAILDATA;
	if (s == "dpchengwdberlsheadbardata") return DPCHENGWDBERLSHEADBARDATA;
	if (s == "dpchengwdberlslistdata") return DPCHENGWDBERLSLISTDATA;
	if (s == "dpchengwdberlsrecdata") return DPCHENGWDBERLSRECDATA;
	if (s == "dpchengwdbesigdata") return DPCHENGWDBESIGDATA;
	if (s == "dpchengwdbesigdetaildata") return DPCHENGWDBESIGDETAILDATA;
	if (s == "dpchengwdbesigheadbardata") return DPCHENGWDBESIGHEADBARDATA;
	if (s == "dpchengwdbesiglistdata") return DPCHENGWDBESIGLISTDATA;
	if (s == "dpchengwdbesigrecdata") return DPCHENGWDBESIGRECDATA;
	if (s == "dpchengwdbesil1nbankdata") return DPCHENGWDBESIL1NBANKDATA;
	if (s == "dpchengwdbesil1nperipheraldata") return DPCHENGWDBESIL1NPERIPHERALDATA;
	if (s == "dpchengwdbesil1ntargetdata") return DPCHENGWDBESIL1NTARGETDATA;
	if (s == "dpchengwdbesildata") return DPCHENGWDBESILDATA;
	if (s == "dpchengwdbesildetaildata") return DPCHENGWDBESILDETAILDATA;
	if (s == "dpchengwdbesilfwd1ncontrollerdata") return DPCHENGWDBESILFWD1NCONTROLLERDATA;
	if (s == "dpchengwdbesilheadbardata") return DPCHENGWDBESILHEADBARDATA;
	if (s == "dpchengwdbesilhk1nmoduledata") return DPCHENGWDBESILHK1NMODULEDATA;
	if (s == "dpchengwdbesilhk1nvectordata") return DPCHENGWDBESILHK1NVECTORDATA;
	if (s == "dpchengwdbesillistdata") return DPCHENGWDBESILLISTDATA;
	if (s == "dpchengwdbesilrecdata") return DPCHENGWDBESILRECDATA;
	if (s == "dpchengwdbesilref1ncommanddata") return DPCHENGWDBESILREF1NCOMMANDDATA;
	if (s == "dpchengwdbesilref1nerrordata") return DPCHENGWDBESILREF1NERRORDATA;
	if (s == "dpchengwdbesilsil1nunitdata") return DPCHENGWDBESILSIL1NUNITDATA;
	if (s == "dpchengwdbesuspend") return DPCHENGWDBESUSPEND;
	if (s == "dpchengwdbesysdata") return DPCHENGWDBESYSDATA;
	if (s == "dpchengwdbesysdetaildata") return DPCHENGWDBESYSDETAILDATA;
	if (s == "dpchengwdbesysheadbardata") return DPCHENGWDBESYSHEADBARDATA;
	if (s == "dpchengwdbesyshk1nvectordata") return DPCHENGWDBESYSHK1NVECTORDATA;
	if (s == "dpchengwdbesyslistdata") return DPCHENGWDBESYSLISTDATA;
	if (s == "dpchengwdbesysrecdata") return DPCHENGWDBESYSRECDATA;
	if (s == "dpchengwdbesyssys1ntargetdata") return DPCHENGWDBESYSSYS1NTARGETDATA;
	if (s == "dpchengwdbetrgdata") return DPCHENGWDBETRGDATA;
	if (s == "dpchengwdbetrgdetaildata") return DPCHENGWDBETRGDETAILDATA;
	if (s == "dpchengwdbetrgheadbardata") return DPCHENGWDBETRGHEADBARDATA;
	if (s == "dpchengwdbetrglistdata") return DPCHENGWDBETRGLISTDATA;
	if (s == "dpchengwdbetrgrecdata") return DPCHENGWDBETRGRECDATA;
	if (s == "dpchengwdbeunt1nbankdata") return DPCHENGWDBEUNT1NBANKDATA;
	if (s == "dpchengwdbeunt1nperipheraldata") return DPCHENGWDBEUNT1NPERIPHERALDATA;
	if (s == "dpchengwdbeunt1ntargetdata") return DPCHENGWDBEUNT1NTARGETDATA;
	if (s == "dpchengwdbeuntdata") return DPCHENGWDBEUNTDATA;
	if (s == "dpchengwdbeuntdetaildata") return DPCHENGWDBEUNTDETAILDATA;
	if (s == "dpchengwdbeuntfwd1ncontrollerdata") return DPCHENGWDBEUNTFWD1NCONTROLLERDATA;
	if (s == "dpchengwdbeuntheadbardata") return DPCHENGWDBEUNTHEADBARDATA;
	if (s == "dpchengwdbeunthk1nmoduledata") return DPCHENGWDBEUNTHK1NMODULEDATA;
	if (s == "dpchengwdbeunthk1nvectordata") return DPCHENGWDBEUNTHK1NVECTORDATA;
	if (s == "dpchengwdbeuntlistdata") return DPCHENGWDBEUNTLISTDATA;
	if (s == "dpchengwdbeuntrecdata") return DPCHENGWDBEUNTRECDATA;
	if (s == "dpchengwdbeuntref1ncommanddata") return DPCHENGWDBEUNTREF1NCOMMANDDATA;
	if (s == "dpchengwdbeuntref1nerrordata") return DPCHENGWDBEUNTREF1NERRORDATA;
	if (s == "dpchengwdbeuntsil1nunitdata") return DPCHENGWDBEUNTSIL1NUNITDATA;
	if (s == "dpchengwdbeusgaaccessdata") return DPCHENGWDBEUSGAACCESSDATA;
	if (s == "dpchengwdbeusgdata") return DPCHENGWDBEUSGDATA;
	if (s == "dpchengwdbeusgdetaildata") return DPCHENGWDBEUSGDETAILDATA;
	if (s == "dpchengwdbeusgheadbardata") return DPCHENGWDBEUSGHEADBARDATA;
	if (s == "dpchengwdbeusglistdata") return DPCHENGWDBEUSGLISTDATA;
	if (s == "dpchengwdbeusgmnuserdata") return DPCHENGWDBEUSGMNUSERDATA;
	if (s == "dpchengwdbeusgrecdata") return DPCHENGWDBEUSGRECDATA;
	if (s == "dpchengwdbeusr1nsessiondata") return DPCHENGWDBEUSR1NSESSIONDATA;
	if (s == "dpchengwdbeusraaccessdata") return DPCHENGWDBEUSRAACCESSDATA;
	if (s == "dpchengwdbeusrdata") return DPCHENGWDBEUSRDATA;
	if (s == "dpchengwdbeusrdetaildata") return DPCHENGWDBEUSRDETAILDATA;
	if (s == "dpchengwdbeusrheadbardata") return DPCHENGWDBEUSRHEADBARDATA;
	if (s == "dpchengwdbeusrlistdata") return DPCHENGWDBEUSRLISTDATA;
	if (s == "dpchengwdbeusrmnusergroupdata") return DPCHENGWDBEUSRMNUSERGROUPDATA;
	if (s == "dpchengwdbeusrrecdata") return DPCHENGWDBEUSRRECDATA;
	if (s == "dpchengwdbeutldata") return DPCHENGWDBEUTLDATA;
	if (s == "dpchengwdbeutlheadbardata") return DPCHENGWDBEUTLHEADBARDATA;
	if (s == "dpchengwdbevardata") return DPCHENGWDBEVARDATA;
	if (s == "dpchengwdbevardetaildata") return DPCHENGWDBEVARDETAILDATA;
	if (s == "dpchengwdbevarheadbardata") return DPCHENGWDBEVARHEADBARDATA;
	if (s == "dpchengwdbevarlistdata") return DPCHENGWDBEVARLISTDATA;
	if (s == "dpchengwdbevarrecdata") return DPCHENGWDBEVARRECDATA;
	if (s == "dpchengwdbevecdata") return DPCHENGWDBEVECDATA;
	if (s == "dpchengwdbevecdetaildata") return DPCHENGWDBEVECDETAILDATA;
	if (s == "dpchengwdbevecheadbardata") return DPCHENGWDBEVECHEADBARDATA;
	if (s == "dpchengwdbeveclistdata") return DPCHENGWDBEVECLISTDATA;
	if (s == "dpchengwdbevecrecdata") return DPCHENGWDBEVECRECDATA;
	if (s == "dpchengwdbevecvec1nvectoritemdata") return DPCHENGWDBEVECVEC1NVECTORITEMDATA;
	if (s == "dpchengwdbever1nreleasedata") return DPCHENGWDBEVER1NRELEASEDATA;
	if (s == "dpchengwdbever1nsystemdata") return DPCHENGWDBEVER1NSYSTEMDATA;
	if (s == "dpchengwdbever1nunitdata") return DPCHENGWDBEVER1NUNITDATA;
	if (s == "dpchengwdbeverbvr1nversiondata") return DPCHENGWDBEVERBVR1NVERSIONDATA;
	if (s == "dpchengwdbeverdata") return DPCHENGWDBEVERDATA;
	if (s == "dpchengwdbeverdetaildata") return DPCHENGWDBEVERDETAILDATA;
	if (s == "dpchengwdbeverheadbardata") return DPCHENGWDBEVERHEADBARDATA;
	if (s == "dpchengwdbeverlistdata") return DPCHENGWDBEVERLISTDATA;
	if (s == "dpchengwdbevermnlibrarydata") return DPCHENGWDBEVERMNLIBRARYDATA;
	if (s == "dpchengwdbeverrecdata") return DPCHENGWDBEVERRECDATA;
	if (s == "dpchengwdbeverref1nfiledata") return DPCHENGWDBEVERREF1NFILEDATA;
	if (s == "dpchengwdbevitdata") return DPCHENGWDBEVITDATA;
	if (s == "dpchengwdbevitdetaildata") return DPCHENGWDBEVITDETAILDATA;
	if (s == "dpchengwdbevitheadbardata") return DPCHENGWDBEVITHEADBARDATA;
	if (s == "dpchengwdbevitlistdata") return DPCHENGWDBEVITLISTDATA;
	if (s == "dpchengwdbevitrecdata") return DPCHENGWDBEVITRECDATA;
	if (s == "dpchappdlgwdbecprnewdata") return DPCHAPPDLGWDBECPRNEWDATA;
	if (s == "dpchappdlgwdbecprnewdo") return DPCHAPPDLGWDBECPRNEWDO;
	if (s == "dpchappdlgwdbecvrbsccddata") return DPCHAPPDLGWDBECVRBSCCDDATA;
	if (s == "dpchappdlgwdbecvrbsccddo") return DPCHAPPDLGWDBECVRBSCCDDO;
	if (s == "dpchappdlgwdbecvrdetcddata") return DPCHAPPDLGWDBECVRDETCDDATA;
	if (s == "dpchappdlgwdbecvrdetcddo") return DPCHAPPDLGWDBECVRDETCDDO;
	if (s == "dpchappdlgwdbecvrnewdata") return DPCHAPPDLGWDBECVRNEWDATA;
	if (s == "dpchappdlgwdbecvrnewdo") return DPCHAPPDLGWDBECVRNEWDO;
	if (s == "dpchappdlgwdbecvrwritedata") return DPCHAPPDLGWDBECVRWRITEDATA;
	if (s == "dpchappdlgwdbecvrwritedo") return DPCHAPPDLGWDBECVRWRITEDO;
	if (s == "dpchappdlgwdbefildownloaddo") return DPCHAPPDLGWDBEFILDOWNLOADDO;
	if (s == "dpchappdlgwdbefilnewdata") return DPCHAPPDLGWDBEFILNEWDATA;
	if (s == "dpchappdlgwdbefilnewdo") return DPCHAPPDLGWDBEFILNEWDO;
	if (s == "dpchappdlgwdbenavloainidata") return DPCHAPPDLGWDBENAVLOAINIDATA;
	if (s == "dpchappdlgwdbenavloainido") return DPCHAPPDLGWDBENAVLOAINIDO;
	if (s == "dpchappdlgwdbenavmnglicdata") return DPCHAPPDLGWDBENAVMNGLICDATA;
	if (s == "dpchappdlgwdbenavmnglicdo") return DPCHAPPDLGWDBENAVMNGLICDO;
	if (s == "dpchappdlgwdbeprjimpexdata") return DPCHAPPDLGWDBEPRJIMPEXDATA;
	if (s == "dpchappdlgwdbeprjimpexdo") return DPCHAPPDLGWDBEPRJIMPEXDO;
	if (s == "dpchappdlgwdbeprjnewdata") return DPCHAPPDLGWDBEPRJNEWDATA;
	if (s == "dpchappdlgwdbeprjnewdo") return DPCHAPPDLGWDBEPRJNEWDO;
	if (s == "dpchappdlgwdberlsfinreptrdata") return DPCHAPPDLGWDBERLSFINREPTRDATA;
	if (s == "dpchappdlgwdberlsfinreptrdo") return DPCHAPPDLGWDBERLSFINREPTRDO;
	if (s == "dpchappdlgwdberlsnewdata") return DPCHAPPDLGWDBERLSNEWDATA;
	if (s == "dpchappdlgwdberlsnewdo") return DPCHAPPDLGWDBERLSNEWDO;
	if (s == "dpchappdlgwdberlsstareptrdata") return DPCHAPPDLGWDBERLSSTAREPTRDATA;
	if (s == "dpchappdlgwdberlsstareptrdo") return DPCHAPPDLGWDBERLSSTAREPTRDO;
	if (s == "dpchappdlgwdberlswritedata") return DPCHAPPDLGWDBERLSWRITEDATA;
	if (s == "dpchappdlgwdberlswritedo") return DPCHAPPDLGWDBERLSWRITEDO;
	if (s == "dpchappdlgwdbeusrmngkeypairdo") return DPCHAPPDLGWDBEUSRMNGKEYPAIRDO;
	if (s == "dpchappdlgwdbeutlextripdata") return DPCHAPPDLGWDBEUTLEXTRIPDATA;
	if (s == "dpchappdlgwdbeutlextripdo") return DPCHAPPDLGWDBEUTLEXTRIPDO;
	if (s == "dpchappdlgwdbeutliexconvdata") return DPCHAPPDLGWDBEUTLIEXCONVDATA;
	if (s == "dpchappdlgwdbeutliexconvdo") return DPCHAPPDLGWDBEUTLIEXCONVDO;
	if (s == "dpchappdlgwdbeutlmrgipdata") return DPCHAPPDLGWDBEUTLMRGIPDATA;
	if (s == "dpchappdlgwdbeutlmrgipdo") return DPCHAPPDLGWDBEUTLMRGIPDO;
	if (s == "dpchappdlgwdbeverbscdddata") return DPCHAPPDLGWDBEVERBSCDDDATA;
	if (s == "dpchappdlgwdbeverbscdddo") return DPCHAPPDLGWDBEVERBSCDDDO;
	if (s == "dpchappdlgwdbeverdetdddata") return DPCHAPPDLGWDBEVERDETDDDATA;
	if (s == "dpchappdlgwdbeverdetdddo") return DPCHAPPDLGWDBEVERDETDDDO;
	if (s == "dpchappdlgwdbevernewdata") return DPCHAPPDLGWDBEVERNEWDATA;
	if (s == "dpchappdlgwdbevernewdo") return DPCHAPPDLGWDBEVERNEWDO;
	if (s == "dpchapprootwdbelogin") return DPCHAPPROOTWDBELOGIN;
	if (s == "dpchappwdbealert") return DPCHAPPWDBEALERT;
	if (s == "dpchappwdbebnk1npindata") return DPCHAPPWDBEBNK1NPINDATA;
	if (s == "dpchappwdbebnk1npindo") return DPCHAPPWDBEBNK1NPINDO;
	if (s == "dpchappwdbebnkdetaildata") return DPCHAPPWDBEBNKDETAILDATA;
	if (s == "dpchappwdbebnkdetaildo") return DPCHAPPWDBEBNKDETAILDO;
	if (s == "dpchappwdbebnkdo") return DPCHAPPWDBEBNKDO;
	if (s == "dpchappwdbebnklistdata") return DPCHAPPWDBEBNKLISTDATA;
	if (s == "dpchappwdbebnklistdo") return DPCHAPPWDBEBNKLISTDO;
	if (s == "dpchappwdbebnkrecdo") return DPCHAPPWDBEBNKRECDO;
	if (s == "dpchappwdbecmdainvpardata") return DPCHAPPWDBECMDAINVPARDATA;
	if (s == "dpchappwdbecmdainvpardo") return DPCHAPPWDBECMDAINVPARDO;
	if (s == "dpchappwdbecmdaretpardata") return DPCHAPPWDBECMDARETPARDATA;
	if (s == "dpchappwdbecmdaretpardo") return DPCHAPPWDBECMDARETPARDO;
	if (s == "dpchappwdbecmddetaildata") return DPCHAPPWDBECMDDETAILDATA;
	if (s == "dpchappwdbecmddetaildo") return DPCHAPPWDBECMDDETAILDO;
	if (s == "dpchappwdbecmddo") return DPCHAPPWDBECMDDO;
	if (s == "dpchappwdbecmdlistdata") return DPCHAPPWDBECMDLISTDATA;
	if (s == "dpchappwdbecmdlistdo") return DPCHAPPWDBECMDLISTDO;
	if (s == "dpchappwdbecmdmncontrollerdata") return DPCHAPPWDBECMDMNCONTROLLERDATA;
	if (s == "dpchappwdbecmdmncontrollerdo") return DPCHAPPWDBECMDMNCONTROLLERDO;
	if (s == "dpchappwdbecmdrecdo") return DPCHAPPWDBECMDRECDO;
	if (s == "dpchappwdbecpr1ncoreversiondata") return DPCHAPPWDBECPR1NCOREVERSIONDATA;
	if (s == "dpchappwdbecpr1ncoreversiondo") return DPCHAPPWDBECPR1NCOREVERSIONDO;
	if (s == "dpchappwdbecprdetaildata") return DPCHAPPWDBECPRDETAILDATA;
	if (s == "dpchappwdbecprdetaildo") return DPCHAPPWDBECPRDETAILDO;
	if (s == "dpchappwdbecprdo") return DPCHAPPWDBECPRDO;
	if (s == "dpchappwdbecprlistdata") return DPCHAPPWDBECPRLISTDATA;
	if (s == "dpchappwdbecprlistdo") return DPCHAPPWDBECPRLISTDO;
	if (s == "dpchappwdbecprmnpersondata") return DPCHAPPWDBECPRMNPERSONDATA;
	if (s == "dpchappwdbecprmnpersondo") return DPCHAPPWDBECPRMNPERSONDO;
	if (s == "dpchappwdbecprrecdo") return DPCHAPPWDBECPRRECDO;
	if (s == "dpchappwdbecvraipdata") return DPCHAPPWDBECVRAIPDATA;
	if (s == "dpchappwdbecvraipdo") return DPCHAPPWDBECVRAIPDO;
	if (s == "dpchappwdbecvraplhdata") return DPCHAPPWDBECVRAPLHDATA;
	if (s == "dpchappwdbecvraplhdo") return DPCHAPPWDBECVRAPLHDO;
	if (s == "dpchappwdbecvrbcv1ncoreversiondata") return DPCHAPPWDBECVRBCV1NCOREVERSIONDATA;
	if (s == "dpchappwdbecvrbcv1ncoreversiondo") return DPCHAPPWDBECVRBCV1NCOREVERSIONDO;
	if (s == "dpchappwdbecvrdetaildata") return DPCHAPPWDBECVRDETAILDATA;
	if (s == "dpchappwdbecvrdetaildo") return DPCHAPPWDBECVRDETAILDO;
	if (s == "dpchappwdbecvrdo") return DPCHAPPWDBECVRDO;
	if (s == "dpchappwdbecvrhk1nmoduledata") return DPCHAPPWDBECVRHK1NMODULEDATA;
	if (s == "dpchappwdbecvrhk1nmoduledo") return DPCHAPPWDBECVRHK1NMODULEDO;
	if (s == "dpchappwdbecvrlistdata") return DPCHAPPWDBECVRLISTDATA;
	if (s == "dpchappwdbecvrlistdo") return DPCHAPPWDBECVRLISTDO;
	if (s == "dpchappwdbecvrrecdo") return DPCHAPPWDBECVRRECDO;
	if (s == "dpchappwdbeerrapardata") return DPCHAPPWDBEERRAPARDATA;
	if (s == "dpchappwdbeerrapardo") return DPCHAPPWDBEERRAPARDO;
	if (s == "dpchappwdbeerrdetaildata") return DPCHAPPWDBEERRDETAILDATA;
	if (s == "dpchappwdbeerrdetaildo") return DPCHAPPWDBEERRDETAILDO;
	if (s == "dpchappwdbeerrdo") return DPCHAPPWDBEERRDO;
	if (s == "dpchappwdbeerrlistdata") return DPCHAPPWDBEERRLISTDATA;
	if (s == "dpchappwdbeerrlistdo") return DPCHAPPWDBEERRLISTDO;
	if (s == "dpchappwdbeerrrecdo") return DPCHAPPWDBEERRRECDO;
	if (s == "dpchappwdbefam1nunitdata") return DPCHAPPWDBEFAM1NUNITDATA;
	if (s == "dpchappwdbefam1nunitdo") return DPCHAPPWDBEFAM1NUNITDO;
	if (s == "dpchappwdbefamdetaildata") return DPCHAPPWDBEFAMDETAILDATA;
	if (s == "dpchappwdbefamdetaildo") return DPCHAPPWDBEFAMDETAILDO;
	if (s == "dpchappwdbefamdo") return DPCHAPPWDBEFAMDO;
	if (s == "dpchappwdbefamlistdata") return DPCHAPPWDBEFAMLISTDATA;
	if (s == "dpchappwdbefamlistdo") return DPCHAPPWDBEFAMLISTDO;
	if (s == "dpchappwdbefamrecdo") return DPCHAPPWDBEFAMRECDO;
	if (s == "dpchappwdbefildetaildata") return DPCHAPPWDBEFILDETAILDATA;
	if (s == "dpchappwdbefildetaildo") return DPCHAPPWDBEFILDETAILDO;
	if (s == "dpchappwdbefildo") return DPCHAPPWDBEFILDO;
	if (s == "dpchappwdbefillistdata") return DPCHAPPWDBEFILLISTDATA;
	if (s == "dpchappwdbefillistdo") return DPCHAPPWDBEFILLISTDO;
	if (s == "dpchappwdbefilrecdo") return DPCHAPPWDBEFILRECDO;
	if (s == "dpchappwdbefstastepdata") return DPCHAPPWDBEFSTASTEPDATA;
	if (s == "dpchappwdbefstastepdo") return DPCHAPPWDBEFSTASTEPDO;
	if (s == "dpchappwdbefstdetaildata") return DPCHAPPWDBEFSTDETAILDATA;
	if (s == "dpchappwdbefstdetaildo") return DPCHAPPWDBEFSTDETAILDO;
	if (s == "dpchappwdbefstdo") return DPCHAPPWDBEFSTDO;
	if (s == "dpchappwdbefstlistdata") return DPCHAPPWDBEFSTLISTDATA;
	if (s == "dpchappwdbefstlistdo") return DPCHAPPWDBEFSTLISTDO;
	if (s == "dpchappwdbefstrecdo") return DPCHAPPWDBEFSTRECDO;
	if (s == "dpchappwdbegendetaildata") return DPCHAPPWDBEGENDETAILDATA;
	if (s == "dpchappwdbegendetaildo") return DPCHAPPWDBEGENDETAILDO;
	if (s == "dpchappwdbegendo") return DPCHAPPWDBEGENDO;
	if (s == "dpchappwdbegenlistdata") return DPCHAPPWDBEGENLISTDATA;
	if (s == "dpchappwdbegenlistdo") return DPCHAPPWDBEGENLISTDO;
	if (s == "dpchappwdbegenrecdo") return DPCHAPPWDBEGENRECDO;
	if (s == "dpchappwdbeinit") return DPCHAPPWDBEINIT;
	if (s == "dpchappwdbelibamakefiledata") return DPCHAPPWDBELIBAMAKEFILEDATA;
	if (s == "dpchappwdbelibamakefiledo") return DPCHAPPWDBELIBAMAKEFILEDO;
	if (s == "dpchappwdbelibdetaildata") return DPCHAPPWDBELIBDETAILDATA;
	if (s == "dpchappwdbelibdetaildo") return DPCHAPPWDBELIBDETAILDO;
	if (s == "dpchappwdbelibdo") return DPCHAPPWDBELIBDO;
	if (s == "dpchappwdbeliblistdata") return DPCHAPPWDBELIBLISTDATA;
	if (s == "dpchappwdbeliblistdo") return DPCHAPPWDBELIBLISTDO;
	if (s == "dpchappwdbelibmnversiondata") return DPCHAPPWDBELIBMNVERSIONDATA;
	if (s == "dpchappwdbelibmnversiondo") return DPCHAPPWDBELIBMNVERSIONDO;
	if (s == "dpchappwdbelibrecdo") return DPCHAPPWDBELIBRECDO;
	if (s == "dpchappwdbemch1nreleasedata") return DPCHAPPWDBEMCH1NRELEASEDATA;
	if (s == "dpchappwdbemch1nreleasedo") return DPCHAPPWDBEMCH1NRELEASEDO;
	if (s == "dpchappwdbemchamakefiledata") return DPCHAPPWDBEMCHAMAKEFILEDATA;
	if (s == "dpchappwdbemchamakefiledo") return DPCHAPPWDBEMCHAMAKEFILEDO;
	if (s == "dpchappwdbemchapardata") return DPCHAPPWDBEMCHAPARDATA;
	if (s == "dpchappwdbemchapardo") return DPCHAPPWDBEMCHAPARDO;
	if (s == "dpchappwdbemchdetaildata") return DPCHAPPWDBEMCHDETAILDATA;
	if (s == "dpchappwdbemchdetaildo") return DPCHAPPWDBEMCHDETAILDO;
	if (s == "dpchappwdbemchdo") return DPCHAPPWDBEMCHDO;
	if (s == "dpchappwdbemchlistdata") return DPCHAPPWDBEMCHLISTDATA;
	if (s == "dpchappwdbemchlistdo") return DPCHAPPWDBEMCHLISTDO;
	if (s == "dpchappwdbemchrecdo") return DPCHAPPWDBEMCHRECDO;
	if (s == "dpchappwdbemod1nperipheraldata") return DPCHAPPWDBEMOD1NPERIPHERALDATA;
	if (s == "dpchappwdbemod1nperipheraldo") return DPCHAPPWDBEMOD1NPERIPHERALDO;
	if (s == "dpchappwdbemod1nprocessdata") return DPCHAPPWDBEMOD1NPROCESSDATA;
	if (s == "dpchappwdbemod1nprocessdo") return DPCHAPPWDBEMOD1NPROCESSDO;
	if (s == "dpchappwdbemodapardata") return DPCHAPPWDBEMODAPARDATA;
	if (s == "dpchappwdbemodapardo") return DPCHAPPWDBEMODAPARDO;
	if (s == "dpchappwdbemodcor1nimbufdata") return DPCHAPPWDBEMODCOR1NIMBUFDATA;
	if (s == "dpchappwdbemodcor1nimbufdo") return DPCHAPPWDBEMODCOR1NIMBUFDO;
	if (s == "dpchappwdbemodctrhk1nvectordata") return DPCHAPPWDBEMODCTRHK1NVECTORDATA;
	if (s == "dpchappwdbemodctrhk1nvectordo") return DPCHAPPWDBEMODCTRHK1NVECTORDO;
	if (s == "dpchappwdbemodctrmncommanddata") return DPCHAPPWDBEMODCTRMNCOMMANDDATA;
	if (s == "dpchappwdbemodctrmncommanddo") return DPCHAPPWDBEMODCTRMNCOMMANDDO;
	if (s == "dpchappwdbemodctrref1ncommanddata") return DPCHAPPWDBEMODCTRREF1NCOMMANDDATA;
	if (s == "dpchappwdbemodctrref1ncommanddo") return DPCHAPPWDBEMODCTRREF1NCOMMANDDO;
	if (s == "dpchappwdbemodctrref1nerrordata") return DPCHAPPWDBEMODCTRREF1NERRORDATA;
	if (s == "dpchappwdbemodctrref1nerrordo") return DPCHAPPWDBEMODCTRREF1NERRORDO;
	if (s == "dpchappwdbemoddetaildata") return DPCHAPPWDBEMODDETAILDATA;
	if (s == "dpchappwdbemoddetaildo") return DPCHAPPWDBEMODDETAILDO;
	if (s == "dpchappwdbemoddo") return DPCHAPPWDBEMODDO;
	if (s == "dpchappwdbemodkhdltypedata") return DPCHAPPWDBEMODKHDLTYPEDATA;
	if (s == "dpchappwdbemodkhdltypedo") return DPCHAPPWDBEMODKHDLTYPEDO;
	if (s == "dpchappwdbemodlistdata") return DPCHAPPWDBEMODLISTDATA;
	if (s == "dpchappwdbemodlistdo") return DPCHAPPWDBEMODLISTDO;
	if (s == "dpchappwdbemodmdl1ngenericdata") return DPCHAPPWDBEMODMDL1NGENERICDATA;
	if (s == "dpchappwdbemodmdl1ngenericdo") return DPCHAPPWDBEMODMDL1NGENERICDO;
	if (s == "dpchappwdbemodmdl1nportdata") return DPCHAPPWDBEMODMDL1NPORTDATA;
	if (s == "dpchappwdbemodmdl1nportdo") return DPCHAPPWDBEMODMDL1NPORTDO;
	if (s == "dpchappwdbemodmdl1nsignaldata") return DPCHAPPWDBEMODMDL1NSIGNALDATA;
	if (s == "dpchappwdbemodmdl1nsignaldo") return DPCHAPPWDBEMODMDL1NSIGNALDO;
	if (s == "dpchappwdbemodmge1nsignaldata") return DPCHAPPWDBEMODMGE1NSIGNALDATA;
	if (s == "dpchappwdbemodmge1nsignaldo") return DPCHAPPWDBEMODMGE1NSIGNALDO;
	if (s == "dpchappwdbemodrecdo") return DPCHAPPWDBEMODRECDO;
	if (s == "dpchappwdbemodsup1nmoduledata") return DPCHAPPWDBEMODSUP1NMODULEDATA;
	if (s == "dpchappwdbemodsup1nmoduledo") return DPCHAPPWDBEMODSUP1NMODULEDO;
	if (s == "dpchappwdbemtpapardata") return DPCHAPPWDBEMTPAPARDATA;
	if (s == "dpchappwdbemtpapardo") return DPCHAPPWDBEMTPAPARDO;
	if (s == "dpchappwdbemtpdetaildata") return DPCHAPPWDBEMTPDETAILDATA;
	if (s == "dpchappwdbemtpdetaildo") return DPCHAPPWDBEMTPDETAILDO;
	if (s == "dpchappwdbemtpdo") return DPCHAPPWDBEMTPDO;
	if (s == "dpchappwdbemtpkhdltypedata") return DPCHAPPWDBEMTPKHDLTYPEDATA;
	if (s == "dpchappwdbemtpkhdltypedo") return DPCHAPPWDBEMTPKHDLTYPEDO;
	if (s == "dpchappwdbemtpkparkeydata") return DPCHAPPWDBEMTPKPARKEYDATA;
	if (s == "dpchappwdbemtpkparkeydo") return DPCHAPPWDBEMTPKPARKEYDO;
	if (s == "dpchappwdbemtplistdata") return DPCHAPPWDBEMTPLISTDATA;
	if (s == "dpchappwdbemtplistdo") return DPCHAPPWDBEMTPLISTDO;
	if (s == "dpchappwdbemtpmdl1ngenericdata") return DPCHAPPWDBEMTPMDL1NGENERICDATA;
	if (s == "dpchappwdbemtpmdl1ngenericdo") return DPCHAPPWDBEMTPMDL1NGENERICDO;
	if (s == "dpchappwdbemtpmdl1nportdata") return DPCHAPPWDBEMTPMDL1NPORTDATA;
	if (s == "dpchappwdbemtpmdl1nportdo") return DPCHAPPWDBEMTPMDL1NPORTDO;
	if (s == "dpchappwdbemtpmge1nsignaldata") return DPCHAPPWDBEMTPMGE1NSIGNALDATA;
	if (s == "dpchappwdbemtpmge1nsignaldo") return DPCHAPPWDBEMTPMGE1NSIGNALDO;
	if (s == "dpchappwdbemtprecdo") return DPCHAPPWDBEMTPRECDO;
	if (s == "dpchappwdbemtpref1nfiledata") return DPCHAPPWDBEMTPREF1NFILEDATA;
	if (s == "dpchappwdbemtpref1nfiledo") return DPCHAPPWDBEMTPREF1NFILEDO;
	if (s == "dpchappwdbemtpsup1nmoduledata") return DPCHAPPWDBEMTPSUP1NMODULEDATA;
	if (s == "dpchappwdbemtpsup1nmoduledo") return DPCHAPPWDBEMTPSUP1NMODULEDO;
	if (s == "dpchappwdbemtptpl1nmoduledata") return DPCHAPPWDBEMTPTPL1NMODULEDATA;
	if (s == "dpchappwdbemtptpl1nmoduledo") return DPCHAPPWDBEMTPTPL1NMODULEDO;
	if (s == "dpchappwdbenavadmindata") return DPCHAPPWDBENAVADMINDATA;
	if (s == "dpchappwdbenavadmindo") return DPCHAPPWDBENAVADMINDO;
	if (s == "dpchappwdbenavauxfctdo") return DPCHAPPWDBENAVAUXFCTDO;
	if (s == "dpchappwdbenavcoredevdata") return DPCHAPPWDBENAVCOREDEVDATA;
	if (s == "dpchappwdbenavcoredevdo") return DPCHAPPWDBENAVCOREDEVDO;
	if (s == "dpchappwdbenavdescrdata") return DPCHAPPWDBENAVDESCRDATA;
	if (s == "dpchappwdbenavdescrdo") return DPCHAPPWDBENAVDESCRDO;
	if (s == "dpchappwdbenavdevdevdata") return DPCHAPPWDBENAVDEVDEVDATA;
	if (s == "dpchappwdbenavdevdevdo") return DPCHAPPWDBENAVDEVDEVDO;
	if (s == "dpchappwdbenavdo") return DPCHAPPWDBENAVDO;
	if (s == "dpchappwdbenavglobaldata") return DPCHAPPWDBENAVGLOBALDATA;
	if (s == "dpchappwdbenavglobaldo") return DPCHAPPWDBENAVGLOBALDO;
	if (s == "dpchappwdbenavpredo") return DPCHAPPWDBENAVPREDO;
	if (s == "dpchappwdbepinapardata") return DPCHAPPWDBEPINAPARDATA;
	if (s == "dpchappwdbepinapardo") return DPCHAPPWDBEPINAPARDO;
	if (s == "dpchappwdbepindetaildata") return DPCHAPPWDBEPINDETAILDATA;
	if (s == "dpchappwdbepindetaildo") return DPCHAPPWDBEPINDETAILDO;
	if (s == "dpchappwdbepindo") return DPCHAPPWDBEPINDO;
	if (s == "dpchappwdbepinlistdata") return DPCHAPPWDBEPINLISTDATA;
	if (s == "dpchappwdbepinlistdo") return DPCHAPPWDBEPINLISTDO;
	if (s == "dpchappwdbepinrecdo") return DPCHAPPWDBEPINRECDO;
	if (s == "dpchappwdbepphapardata") return DPCHAPPWDBEPPHAPARDATA;
	if (s == "dpchappwdbepphapardo") return DPCHAPPWDBEPPHAPARDO;
	if (s == "dpchappwdbepphdetaildata") return DPCHAPPWDBEPPHDETAILDATA;
	if (s == "dpchappwdbepphdetaildo") return DPCHAPPWDBEPPHDETAILDO;
	if (s == "dpchappwdbepphdo") return DPCHAPPWDBEPPHDO;
	if (s == "dpchappwdbepphlistdata") return DPCHAPPWDBEPPHLISTDATA;
	if (s == "dpchappwdbepphlistdo") return DPCHAPPWDBEPPHLISTDO;
	if (s == "dpchappwdbepphrecdo") return DPCHAPPWDBEPPHRECDO;
	if (s == "dpchappwdbeprcdetaildata") return DPCHAPPWDBEPRCDETAILDATA;
	if (s == "dpchappwdbeprcdetaildo") return DPCHAPPWDBEPRCDETAILDO;
	if (s == "dpchappwdbeprcdo") return DPCHAPPWDBEPRCDO;
	if (s == "dpchappwdbeprcfsmfsm1nfsmstatedata") return DPCHAPPWDBEPRCFSMFSM1NFSMSTATEDATA;
	if (s == "dpchappwdbeprcfsmfsm1nfsmstatedo") return DPCHAPPWDBEPRCFSMFSM1NFSMSTATEDO;
	if (s == "dpchappwdbeprckhdltypedata") return DPCHAPPWDBEPRCKHDLTYPEDATA;
	if (s == "dpchappwdbeprckhdltypedo") return DPCHAPPWDBEPRCKHDLTYPEDO;
	if (s == "dpchappwdbeprclistdata") return DPCHAPPWDBEPRCLISTDATA;
	if (s == "dpchappwdbeprclistdo") return DPCHAPPWDBEPRCLISTDO;
	if (s == "dpchappwdbeprcmge1nsignaldata") return DPCHAPPWDBEPRCMGE1NSIGNALDATA;
	if (s == "dpchappwdbeprcmge1nsignaldo") return DPCHAPPWDBEPRCMGE1NSIGNALDO;
	if (s == "dpchappwdbeprcprc1nvariabledata") return DPCHAPPWDBEPRCPRC1NVARIABLEDATA;
	if (s == "dpchappwdbeprcprc1nvariabledo") return DPCHAPPWDBEPRCPRC1NVARIABLEDO;
	if (s == "dpchappwdbeprcrecdo") return DPCHAPPWDBEPRCRECDO;
	if (s == "dpchappwdbeprj1nversiondata") return DPCHAPPWDBEPRJ1NVERSIONDATA;
	if (s == "dpchappwdbeprj1nversiondo") return DPCHAPPWDBEPRJ1NVERSIONDO;
	if (s == "dpchappwdbeprjdetaildata") return DPCHAPPWDBEPRJDETAILDATA;
	if (s == "dpchappwdbeprjdetaildo") return DPCHAPPWDBEPRJDETAILDO;
	if (s == "dpchappwdbeprjdo") return DPCHAPPWDBEPRJDO;
	if (s == "dpchappwdbeprjlistdata") return DPCHAPPWDBEPRJLISTDATA;
	if (s == "dpchappwdbeprjlistdo") return DPCHAPPWDBEPRJLISTDO;
	if (s == "dpchappwdbeprjmnpersondata") return DPCHAPPWDBEPRJMNPERSONDATA;
	if (s == "dpchappwdbeprjmnpersondo") return DPCHAPPWDBEPRJMNPERSONDO;
	if (s == "dpchappwdbeprjrecdo") return DPCHAPPWDBEPRJRECDO;
	if (s == "dpchappwdbeprsadetaildata") return DPCHAPPWDBEPRSADETAILDATA;
	if (s == "dpchappwdbeprsadetaildo") return DPCHAPPWDBEPRSADETAILDO;
	if (s == "dpchappwdbeprsdetaildata") return DPCHAPPWDBEPRSDETAILDATA;
	if (s == "dpchappwdbeprsdetaildo") return DPCHAPPWDBEPRSDETAILDO;
	if (s == "dpchappwdbeprsdo") return DPCHAPPWDBEPRSDO;
	if (s == "dpchappwdbeprslistdata") return DPCHAPPWDBEPRSLISTDATA;
	if (s == "dpchappwdbeprslistdo") return DPCHAPPWDBEPRSLISTDO;
	if (s == "dpchappwdbeprsmncoreprojectdata") return DPCHAPPWDBEPRSMNCOREPROJECTDATA;
	if (s == "dpchappwdbeprsmncoreprojectdo") return DPCHAPPWDBEPRSMNCOREPROJECTDO;
	if (s == "dpchappwdbeprsmnprojectdata") return DPCHAPPWDBEPRSMNPROJECTDATA;
	if (s == "dpchappwdbeprsmnprojectdo") return DPCHAPPWDBEPRSMNPROJECTDO;
	if (s == "dpchappwdbeprsrecdo") return DPCHAPPWDBEPRSRECDO;
	if (s == "dpchappwdbeprtdetaildata") return DPCHAPPWDBEPRTDETAILDATA;
	if (s == "dpchappwdbeprtdetaildo") return DPCHAPPWDBEPRTDETAILDO;
	if (s == "dpchappwdbeprtdo") return DPCHAPPWDBEPRTDO;
	if (s == "dpchappwdbeprtlistdata") return DPCHAPPWDBEPRTLISTDATA;
	if (s == "dpchappwdbeprtlistdo") return DPCHAPPWDBEPRTLISTDO;
	if (s == "dpchappwdbeprtrecdo") return DPCHAPPWDBEPRTRECDO;
	if (s == "dpchappwdberesume") return DPCHAPPWDBERESUME;
	if (s == "dpchappwdberlsdetaildata") return DPCHAPPWDBERLSDETAILDATA;
	if (s == "dpchappwdberlsdetaildo") return DPCHAPPWDBERLSDETAILDO;
	if (s == "dpchappwdberlsdo") return DPCHAPPWDBERLSDO;
	if (s == "dpchappwdberlslistdata") return DPCHAPPWDBERLSLISTDATA;
	if (s == "dpchappwdberlslistdo") return DPCHAPPWDBERLSLISTDO;
	if (s == "dpchappwdberlsrecdo") return DPCHAPPWDBERLSRECDO;
	if (s == "dpchappwdbesigdetaildata") return DPCHAPPWDBESIGDETAILDATA;
	if (s == "dpchappwdbesigdetaildo") return DPCHAPPWDBESIGDETAILDO;
	if (s == "dpchappwdbesigdo") return DPCHAPPWDBESIGDO;
	if (s == "dpchappwdbesiglistdata") return DPCHAPPWDBESIGLISTDATA;
	if (s == "dpchappwdbesiglistdo") return DPCHAPPWDBESIGLISTDO;
	if (s == "dpchappwdbesigrecdo") return DPCHAPPWDBESIGRECDO;
	if (s == "dpchappwdbesil1nbankdata") return DPCHAPPWDBESIL1NBANKDATA;
	if (s == "dpchappwdbesil1nbankdo") return DPCHAPPWDBESIL1NBANKDO;
	if (s == "dpchappwdbesil1nperipheraldata") return DPCHAPPWDBESIL1NPERIPHERALDATA;
	if (s == "dpchappwdbesil1nperipheraldo") return DPCHAPPWDBESIL1NPERIPHERALDO;
	if (s == "dpchappwdbesil1ntargetdata") return DPCHAPPWDBESIL1NTARGETDATA;
	if (s == "dpchappwdbesil1ntargetdo") return DPCHAPPWDBESIL1NTARGETDO;
	if (s == "dpchappwdbesildetaildata") return DPCHAPPWDBESILDETAILDATA;
	if (s == "dpchappwdbesildetaildo") return DPCHAPPWDBESILDETAILDO;
	if (s == "dpchappwdbesildo") return DPCHAPPWDBESILDO;
	if (s == "dpchappwdbesilfwd1ncontrollerdata") return DPCHAPPWDBESILFWD1NCONTROLLERDATA;
	if (s == "dpchappwdbesilfwd1ncontrollerdo") return DPCHAPPWDBESILFWD1NCONTROLLERDO;
	if (s == "dpchappwdbesilhk1nmoduledata") return DPCHAPPWDBESILHK1NMODULEDATA;
	if (s == "dpchappwdbesilhk1nmoduledo") return DPCHAPPWDBESILHK1NMODULEDO;
	if (s == "dpchappwdbesilhk1nvectordata") return DPCHAPPWDBESILHK1NVECTORDATA;
	if (s == "dpchappwdbesilhk1nvectordo") return DPCHAPPWDBESILHK1NVECTORDO;
	if (s == "dpchappwdbesillistdata") return DPCHAPPWDBESILLISTDATA;
	if (s == "dpchappwdbesillistdo") return DPCHAPPWDBESILLISTDO;
	if (s == "dpchappwdbesilrecdo") return DPCHAPPWDBESILRECDO;
	if (s == "dpchappwdbesilref1ncommanddata") return DPCHAPPWDBESILREF1NCOMMANDDATA;
	if (s == "dpchappwdbesilref1ncommanddo") return DPCHAPPWDBESILREF1NCOMMANDDO;
	if (s == "dpchappwdbesilref1nerrordata") return DPCHAPPWDBESILREF1NERRORDATA;
	if (s == "dpchappwdbesilref1nerrordo") return DPCHAPPWDBESILREF1NERRORDO;
	if (s == "dpchappwdbesilsil1nunitdata") return DPCHAPPWDBESILSIL1NUNITDATA;
	if (s == "dpchappwdbesilsil1nunitdo") return DPCHAPPWDBESILSIL1NUNITDO;
	if (s == "dpchappwdbesysdetaildata") return DPCHAPPWDBESYSDETAILDATA;
	if (s == "dpchappwdbesysdetaildo") return DPCHAPPWDBESYSDETAILDO;
	if (s == "dpchappwdbesysdo") return DPCHAPPWDBESYSDO;
	if (s == "dpchappwdbesyshk1nvectordata") return DPCHAPPWDBESYSHK1NVECTORDATA;
	if (s == "dpchappwdbesyshk1nvectordo") return DPCHAPPWDBESYSHK1NVECTORDO;
	if (s == "dpchappwdbesyslistdata") return DPCHAPPWDBESYSLISTDATA;
	if (s == "dpchappwdbesyslistdo") return DPCHAPPWDBESYSLISTDO;
	if (s == "dpchappwdbesysrecdo") return DPCHAPPWDBESYSRECDO;
	if (s == "dpchappwdbesyssys1ntargetdata") return DPCHAPPWDBESYSSYS1NTARGETDATA;
	if (s == "dpchappwdbesyssys1ntargetdo") return DPCHAPPWDBESYSSYS1NTARGETDO;
	if (s == "dpchappwdbetrgdetaildata") return DPCHAPPWDBETRGDETAILDATA;
	if (s == "dpchappwdbetrgdetaildo") return DPCHAPPWDBETRGDETAILDO;
	if (s == "dpchappwdbetrgdo") return DPCHAPPWDBETRGDO;
	if (s == "dpchappwdbetrglistdata") return DPCHAPPWDBETRGLISTDATA;
	if (s == "dpchappwdbetrglistdo") return DPCHAPPWDBETRGLISTDO;
	if (s == "dpchappwdbetrgrecdo") return DPCHAPPWDBETRGRECDO;
	if (s == "dpchappwdbeunt1nbankdata") return DPCHAPPWDBEUNT1NBANKDATA;
	if (s == "dpchappwdbeunt1nbankdo") return DPCHAPPWDBEUNT1NBANKDO;
	if (s == "dpchappwdbeunt1nperipheraldata") return DPCHAPPWDBEUNT1NPERIPHERALDATA;
	if (s == "dpchappwdbeunt1nperipheraldo") return DPCHAPPWDBEUNT1NPERIPHERALDO;
	if (s == "dpchappwdbeunt1ntargetdata") return DPCHAPPWDBEUNT1NTARGETDATA;
	if (s == "dpchappwdbeunt1ntargetdo") return DPCHAPPWDBEUNT1NTARGETDO;
	if (s == "dpchappwdbeuntdetaildata") return DPCHAPPWDBEUNTDETAILDATA;
	if (s == "dpchappwdbeuntdetaildo") return DPCHAPPWDBEUNTDETAILDO;
	if (s == "dpchappwdbeuntdo") return DPCHAPPWDBEUNTDO;
	if (s == "dpchappwdbeuntfwd1ncontrollerdata") return DPCHAPPWDBEUNTFWD1NCONTROLLERDATA;
	if (s == "dpchappwdbeuntfwd1ncontrollerdo") return DPCHAPPWDBEUNTFWD1NCONTROLLERDO;
	if (s == "dpchappwdbeunthk1nmoduledata") return DPCHAPPWDBEUNTHK1NMODULEDATA;
	if (s == "dpchappwdbeunthk1nmoduledo") return DPCHAPPWDBEUNTHK1NMODULEDO;
	if (s == "dpchappwdbeunthk1nvectordata") return DPCHAPPWDBEUNTHK1NVECTORDATA;
	if (s == "dpchappwdbeunthk1nvectordo") return DPCHAPPWDBEUNTHK1NVECTORDO;
	if (s == "dpchappwdbeuntlistdata") return DPCHAPPWDBEUNTLISTDATA;
	if (s == "dpchappwdbeuntlistdo") return DPCHAPPWDBEUNTLISTDO;
	if (s == "dpchappwdbeuntrecdo") return DPCHAPPWDBEUNTRECDO;
	if (s == "dpchappwdbeuntref1ncommanddata") return DPCHAPPWDBEUNTREF1NCOMMANDDATA;
	if (s == "dpchappwdbeuntref1ncommanddo") return DPCHAPPWDBEUNTREF1NCOMMANDDO;
	if (s == "dpchappwdbeuntref1nerrordata") return DPCHAPPWDBEUNTREF1NERRORDATA;
	if (s == "dpchappwdbeuntref1nerrordo") return DPCHAPPWDBEUNTREF1NERRORDO;
	if (s == "dpchappwdbeuntsil1nunitdata") return DPCHAPPWDBEUNTSIL1NUNITDATA;
	if (s == "dpchappwdbeuntsil1nunitdo") return DPCHAPPWDBEUNTSIL1NUNITDO;
	if (s == "dpchappwdbeusgaaccessdata") return DPCHAPPWDBEUSGAACCESSDATA;
	if (s == "dpchappwdbeusgaaccessdo") return DPCHAPPWDBEUSGAACCESSDO;
	if (s == "dpchappwdbeusgdetaildata") return DPCHAPPWDBEUSGDETAILDATA;
	if (s == "dpchappwdbeusgdetaildo") return DPCHAPPWDBEUSGDETAILDO;
	if (s == "dpchappwdbeusgdo") return DPCHAPPWDBEUSGDO;
	if (s == "dpchappwdbeusglistdata") return DPCHAPPWDBEUSGLISTDATA;
	if (s == "dpchappwdbeusglistdo") return DPCHAPPWDBEUSGLISTDO;
	if (s == "dpchappwdbeusgmnuserdata") return DPCHAPPWDBEUSGMNUSERDATA;
	if (s == "dpchappwdbeusgmnuserdo") return DPCHAPPWDBEUSGMNUSERDO;
	if (s == "dpchappwdbeusgrecdo") return DPCHAPPWDBEUSGRECDO;
	if (s == "dpchappwdbeusr1nsessiondata") return DPCHAPPWDBEUSR1NSESSIONDATA;
	if (s == "dpchappwdbeusr1nsessiondo") return DPCHAPPWDBEUSR1NSESSIONDO;
	if (s == "dpchappwdbeusraaccessdata") return DPCHAPPWDBEUSRAACCESSDATA;
	if (s == "dpchappwdbeusraaccessdo") return DPCHAPPWDBEUSRAACCESSDO;
	if (s == "dpchappwdbeusrdetaildata") return DPCHAPPWDBEUSRDETAILDATA;
	if (s == "dpchappwdbeusrdetaildo") return DPCHAPPWDBEUSRDETAILDO;
	if (s == "dpchappwdbeusrdo") return DPCHAPPWDBEUSRDO;
	if (s == "dpchappwdbeusrlistdata") return DPCHAPPWDBEUSRLISTDATA;
	if (s == "dpchappwdbeusrlistdo") return DPCHAPPWDBEUSRLISTDO;
	if (s == "dpchappwdbeusrmnusergroupdata") return DPCHAPPWDBEUSRMNUSERGROUPDATA;
	if (s == "dpchappwdbeusrmnusergroupdo") return DPCHAPPWDBEUSRMNUSERGROUPDO;
	if (s == "dpchappwdbeusrrecdo") return DPCHAPPWDBEUSRRECDO;
	if (s == "dpchappwdbeutldo") return DPCHAPPWDBEUTLDO;
	if (s == "dpchappwdbevardetaildata") return DPCHAPPWDBEVARDETAILDATA;
	if (s == "dpchappwdbevardetaildo") return DPCHAPPWDBEVARDETAILDO;
	if (s == "dpchappwdbevardo") return DPCHAPPWDBEVARDO;
	if (s == "dpchappwdbevarlistdata") return DPCHAPPWDBEVARLISTDATA;
	if (s == "dpchappwdbevarlistdo") return DPCHAPPWDBEVARLISTDO;
	if (s == "dpchappwdbevarrecdo") return DPCHAPPWDBEVARRECDO;
	if (s == "dpchappwdbevecdetaildata") return DPCHAPPWDBEVECDETAILDATA;
	if (s == "dpchappwdbevecdetaildo") return DPCHAPPWDBEVECDETAILDO;
	if (s == "dpchappwdbevecdo") return DPCHAPPWDBEVECDO;
	if (s == "dpchappwdbeveclistdata") return DPCHAPPWDBEVECLISTDATA;
	if (s == "dpchappwdbeveclistdo") return DPCHAPPWDBEVECLISTDO;
	if (s == "dpchappwdbevecrecdo") return DPCHAPPWDBEVECRECDO;
	if (s == "dpchappwdbevecvec1nvectoritemdata") return DPCHAPPWDBEVECVEC1NVECTORITEMDATA;
	if (s == "dpchappwdbevecvec1nvectoritemdo") return DPCHAPPWDBEVECVEC1NVECTORITEMDO;
	if (s == "dpchappwdbever1nreleasedata") return DPCHAPPWDBEVER1NRELEASEDATA;
	if (s == "dpchappwdbever1nreleasedo") return DPCHAPPWDBEVER1NRELEASEDO;
	if (s == "dpchappwdbever1nsystemdata") return DPCHAPPWDBEVER1NSYSTEMDATA;
	if (s == "dpchappwdbever1nsystemdo") return DPCHAPPWDBEVER1NSYSTEMDO;
	if (s == "dpchappwdbever1nunitdata") return DPCHAPPWDBEVER1NUNITDATA;
	if (s == "dpchappwdbever1nunitdo") return DPCHAPPWDBEVER1NUNITDO;
	if (s == "dpchappwdbeverbvr1nversiondata") return DPCHAPPWDBEVERBVR1NVERSIONDATA;
	if (s == "dpchappwdbeverbvr1nversiondo") return DPCHAPPWDBEVERBVR1NVERSIONDO;
	if (s == "dpchappwdbeverdetaildata") return DPCHAPPWDBEVERDETAILDATA;
	if (s == "dpchappwdbeverdetaildo") return DPCHAPPWDBEVERDETAILDO;
	if (s == "dpchappwdbeverdo") return DPCHAPPWDBEVERDO;
	if (s == "dpchappwdbeverlistdata") return DPCHAPPWDBEVERLISTDATA;
	if (s == "dpchappwdbeverlistdo") return DPCHAPPWDBEVERLISTDO;
	if (s == "dpchappwdbevermnlibrarydata") return DPCHAPPWDBEVERMNLIBRARYDATA;
	if (s == "dpchappwdbevermnlibrarydo") return DPCHAPPWDBEVERMNLIBRARYDO;
	if (s == "dpchappwdbeverrecdo") return DPCHAPPWDBEVERRECDO;
	if (s == "dpchappwdbeverref1nfiledata") return DPCHAPPWDBEVERREF1NFILEDATA;
	if (s == "dpchappwdbeverref1nfiledo") return DPCHAPPWDBEVERREF1NFILEDO;
	if (s == "dpchappwdbevitdetaildata") return DPCHAPPWDBEVITDETAILDATA;
	if (s == "dpchappwdbevitdetaildo") return DPCHAPPWDBEVITDETAILDO;
	if (s == "dpchappwdbevitdo") return DPCHAPPWDBEVITDO;
	if (s == "dpchappwdbevitlistdata") return DPCHAPPWDBEVITLISTDATA;
	if (s == "dpchappwdbevitlistdo") return DPCHAPPWDBEVITLISTDO;
	if (s == "dpchappwdbevitrecdo") return DPCHAPPWDBEVITRECDO;

	return(0);
};

string VecWdbeVDpch::getSref(
			const uint ix
		) {
	if (ix == DPCHENGDLGWDBECPRNEWDATA) return("DpchEngDlgWdbeCprNewData");
	if (ix == DPCHENGDLGWDBECVRBSCCDDATA) return("DpchEngDlgWdbeCvrBsccdData");
	if (ix == DPCHENGDLGWDBECVRDETCDDATA) return("DpchEngDlgWdbeCvrDetcdData");
	if (ix == DPCHENGDLGWDBECVRNEWDATA) return("DpchEngDlgWdbeCvrNewData");
	if (ix == DPCHENGDLGWDBECVRWRITEDATA) return("DpchEngDlgWdbeCvrWriteData");
	if (ix == DPCHENGDLGWDBEFILDOWNLOADDATA) return("DpchEngDlgWdbeFilDownloadData");
	if (ix == DPCHENGDLGWDBEFILNEWDATA) return("DpchEngDlgWdbeFilNewData");
	if (ix == DPCHENGDLGWDBENAVLOAINIDATA) return("DpchEngDlgWdbeNavLoainiData");
	if (ix == DPCHENGDLGWDBENAVMNGLICDATA) return("DpchEngDlgWdbeNavMnglicData");
	if (ix == DPCHENGDLGWDBEPRJIMPEXDATA) return("DpchEngDlgWdbePrjImpexData");
	if (ix == DPCHENGDLGWDBEPRJNEWDATA) return("DpchEngDlgWdbePrjNewData");
	if (ix == DPCHENGDLGWDBERLSFINREPTRDATA) return("DpchEngDlgWdbeRlsFinreptrData");
	if (ix == DPCHENGDLGWDBERLSNEWDATA) return("DpchEngDlgWdbeRlsNewData");
	if (ix == DPCHENGDLGWDBERLSSTAREPTRDATA) return("DpchEngDlgWdbeRlsStareptrData");
	if (ix == DPCHENGDLGWDBERLSWRITEDATA) return("DpchEngDlgWdbeRlsWriteData");
	if (ix == DPCHENGDLGWDBEUSRMNGKEYPAIRDATA) return("DpchEngDlgWdbeUsrMngkeypairData");
	if (ix == DPCHENGDLGWDBEUTLEXTRIPDATA) return("DpchEngDlgWdbeUtlExtripData");
	if (ix == DPCHENGDLGWDBEUTLIEXCONVDATA) return("DpchEngDlgWdbeUtlIexconvData");
	if (ix == DPCHENGDLGWDBEUTLMRGIPDATA) return("DpchEngDlgWdbeUtlMrgipData");
	if (ix == DPCHENGDLGWDBEVERBSCDDDATA) return("DpchEngDlgWdbeVerBscddData");
	if (ix == DPCHENGDLGWDBEVERDETDDDATA) return("DpchEngDlgWdbeVerDetddData");
	if (ix == DPCHENGDLGWDBEVERNEWDATA) return("DpchEngDlgWdbeVerNewData");
	if (ix == DPCHENGROOTWDBEDATA) return("DpchEngRootWdbeData");
	if (ix == DPCHENGSESSWDBEDATA) return("DpchEngSessWdbeData");
	if (ix == DPCHENGWDBEACK) return("DpchEngWdbeAck");
	if (ix == DPCHENGWDBEALERT) return("DpchEngWdbeAlert");
	if (ix == DPCHENGWDBEBNK1NPINDATA) return("DpchEngWdbeBnk1NPinData");
	if (ix == DPCHENGWDBEBNKDATA) return("DpchEngWdbeBnkData");
	if (ix == DPCHENGWDBEBNKDETAILDATA) return("DpchEngWdbeBnkDetailData");
	if (ix == DPCHENGWDBEBNKHEADBARDATA) return("DpchEngWdbeBnkHeadbarData");
	if (ix == DPCHENGWDBEBNKLISTDATA) return("DpchEngWdbeBnkListData");
	if (ix == DPCHENGWDBEBNKRECDATA) return("DpchEngWdbeBnkRecData");
	if (ix == DPCHENGWDBECMDAINVPARDATA) return("DpchEngWdbeCmdAInvparData");
	if (ix == DPCHENGWDBECMDARETPARDATA) return("DpchEngWdbeCmdARetparData");
	if (ix == DPCHENGWDBECMDDATA) return("DpchEngWdbeCmdData");
	if (ix == DPCHENGWDBECMDDETAILDATA) return("DpchEngWdbeCmdDetailData");
	if (ix == DPCHENGWDBECMDHEADBARDATA) return("DpchEngWdbeCmdHeadbarData");
	if (ix == DPCHENGWDBECMDLISTDATA) return("DpchEngWdbeCmdListData");
	if (ix == DPCHENGWDBECMDMNCONTROLLERDATA) return("DpchEngWdbeCmdMNControllerData");
	if (ix == DPCHENGWDBECMDRECDATA) return("DpchEngWdbeCmdRecData");
	if (ix == DPCHENGWDBECONFIRM) return("DpchEngWdbeConfirm");
	if (ix == DPCHENGWDBECPR1NCOREVERSIONDATA) return("DpchEngWdbeCpr1NCoreversionData");
	if (ix == DPCHENGWDBECPRDATA) return("DpchEngWdbeCprData");
	if (ix == DPCHENGWDBECPRDETAILDATA) return("DpchEngWdbeCprDetailData");
	if (ix == DPCHENGWDBECPRHEADBARDATA) return("DpchEngWdbeCprHeadbarData");
	if (ix == DPCHENGWDBECPRLISTDATA) return("DpchEngWdbeCprListData");
	if (ix == DPCHENGWDBECPRMNPERSONDATA) return("DpchEngWdbeCprMNPersonData");
	if (ix == DPCHENGWDBECPRRECDATA) return("DpchEngWdbeCprRecData");
	if (ix == DPCHENGWDBECVRAIPDATA) return("DpchEngWdbeCvrAIpData");
	if (ix == DPCHENGWDBECVRAPLHDATA) return("DpchEngWdbeCvrAPlhData");
	if (ix == DPCHENGWDBECVRBCV1NCOREVERSIONDATA) return("DpchEngWdbeCvrBcv1NCoreversionData");
	if (ix == DPCHENGWDBECVRDATA) return("DpchEngWdbeCvrData");
	if (ix == DPCHENGWDBECVRDETAILDATA) return("DpchEngWdbeCvrDetailData");
	if (ix == DPCHENGWDBECVRHEADBARDATA) return("DpchEngWdbeCvrHeadbarData");
	if (ix == DPCHENGWDBECVRHK1NMODULEDATA) return("DpchEngWdbeCvrHk1NModuleData");
	if (ix == DPCHENGWDBECVRLISTDATA) return("DpchEngWdbeCvrListData");
	if (ix == DPCHENGWDBECVRRECDATA) return("DpchEngWdbeCvrRecData");
	if (ix == DPCHENGWDBEERRAPARDATA) return("DpchEngWdbeErrAParData");
	if (ix == DPCHENGWDBEERRDATA) return("DpchEngWdbeErrData");
	if (ix == DPCHENGWDBEERRDETAILDATA) return("DpchEngWdbeErrDetailData");
	if (ix == DPCHENGWDBEERRHEADBARDATA) return("DpchEngWdbeErrHeadbarData");
	if (ix == DPCHENGWDBEERRLISTDATA) return("DpchEngWdbeErrListData");
	if (ix == DPCHENGWDBEERRRECDATA) return("DpchEngWdbeErrRecData");
	if (ix == DPCHENGWDBEFAM1NUNITDATA) return("DpchEngWdbeFam1NUnitData");
	if (ix == DPCHENGWDBEFAMDATA) return("DpchEngWdbeFamData");
	if (ix == DPCHENGWDBEFAMDETAILDATA) return("DpchEngWdbeFamDetailData");
	if (ix == DPCHENGWDBEFAMHEADBARDATA) return("DpchEngWdbeFamHeadbarData");
	if (ix == DPCHENGWDBEFAMLISTDATA) return("DpchEngWdbeFamListData");
	if (ix == DPCHENGWDBEFAMRECDATA) return("DpchEngWdbeFamRecData");
	if (ix == DPCHENGWDBEFILDATA) return("DpchEngWdbeFilData");
	if (ix == DPCHENGWDBEFILDETAILDATA) return("DpchEngWdbeFilDetailData");
	if (ix == DPCHENGWDBEFILHEADBARDATA) return("DpchEngWdbeFilHeadbarData");
	if (ix == DPCHENGWDBEFILLISTDATA) return("DpchEngWdbeFilListData");
	if (ix == DPCHENGWDBEFILRECDATA) return("DpchEngWdbeFilRecData");
	if (ix == DPCHENGWDBEFSTASTEPDATA) return("DpchEngWdbeFstAStepData");
	if (ix == DPCHENGWDBEFSTDATA) return("DpchEngWdbeFstData");
	if (ix == DPCHENGWDBEFSTDETAILDATA) return("DpchEngWdbeFstDetailData");
	if (ix == DPCHENGWDBEFSTHEADBARDATA) return("DpchEngWdbeFstHeadbarData");
	if (ix == DPCHENGWDBEFSTLISTDATA) return("DpchEngWdbeFstListData");
	if (ix == DPCHENGWDBEFSTRECDATA) return("DpchEngWdbeFstRecData");
	if (ix == DPCHENGWDBEGENDATA) return("DpchEngWdbeGenData");
	if (ix == DPCHENGWDBEGENDETAILDATA) return("DpchEngWdbeGenDetailData");
	if (ix == DPCHENGWDBEGENHEADBARDATA) return("DpchEngWdbeGenHeadbarData");
	if (ix == DPCHENGWDBEGENLISTDATA) return("DpchEngWdbeGenListData");
	if (ix == DPCHENGWDBEGENRECDATA) return("DpchEngWdbeGenRecData");
	if (ix == DPCHENGWDBELIBAMAKEFILEDATA) return("DpchEngWdbeLibAMakefileData");
	if (ix == DPCHENGWDBELIBDATA) return("DpchEngWdbeLibData");
	if (ix == DPCHENGWDBELIBDETAILDATA) return("DpchEngWdbeLibDetailData");
	if (ix == DPCHENGWDBELIBHEADBARDATA) return("DpchEngWdbeLibHeadbarData");
	if (ix == DPCHENGWDBELIBLISTDATA) return("DpchEngWdbeLibListData");
	if (ix == DPCHENGWDBELIBMNVERSIONDATA) return("DpchEngWdbeLibMNVersionData");
	if (ix == DPCHENGWDBELIBRECDATA) return("DpchEngWdbeLibRecData");
	if (ix == DPCHENGWDBEMCH1NRELEASEDATA) return("DpchEngWdbeMch1NReleaseData");
	if (ix == DPCHENGWDBEMCHAMAKEFILEDATA) return("DpchEngWdbeMchAMakefileData");
	if (ix == DPCHENGWDBEMCHAPARDATA) return("DpchEngWdbeMchAParData");
	if (ix == DPCHENGWDBEMCHDATA) return("DpchEngWdbeMchData");
	if (ix == DPCHENGWDBEMCHDETAILDATA) return("DpchEngWdbeMchDetailData");
	if (ix == DPCHENGWDBEMCHHEADBARDATA) return("DpchEngWdbeMchHeadbarData");
	if (ix == DPCHENGWDBEMCHLISTDATA) return("DpchEngWdbeMchListData");
	if (ix == DPCHENGWDBEMCHRECDATA) return("DpchEngWdbeMchRecData");
	if (ix == DPCHENGWDBEMOD1NPERIPHERALDATA) return("DpchEngWdbeMod1NPeripheralData");
	if (ix == DPCHENGWDBEMOD1NPROCESSDATA) return("DpchEngWdbeMod1NProcessData");
	if (ix == DPCHENGWDBEMODAPARDATA) return("DpchEngWdbeModAParData");
	if (ix == DPCHENGWDBEMODCOR1NIMBUFDATA) return("DpchEngWdbeModCor1NImbufData");
	if (ix == DPCHENGWDBEMODCTRHK1NVECTORDATA) return("DpchEngWdbeModCtrHk1NVectorData");
	if (ix == DPCHENGWDBEMODCTRMNCOMMANDDATA) return("DpchEngWdbeModCtrMNCommandData");
	if (ix == DPCHENGWDBEMODCTRREF1NCOMMANDDATA) return("DpchEngWdbeModCtrRef1NCommandData");
	if (ix == DPCHENGWDBEMODCTRREF1NERRORDATA) return("DpchEngWdbeModCtrRef1NErrorData");
	if (ix == DPCHENGWDBEMODDATA) return("DpchEngWdbeModData");
	if (ix == DPCHENGWDBEMODDETAILDATA) return("DpchEngWdbeModDetailData");
	if (ix == DPCHENGWDBEMODHEADBARDATA) return("DpchEngWdbeModHeadbarData");
	if (ix == DPCHENGWDBEMODKHDLTYPEDATA) return("DpchEngWdbeModKHdltypeData");
	if (ix == DPCHENGWDBEMODLISTDATA) return("DpchEngWdbeModListData");
	if (ix == DPCHENGWDBEMODMDL1NGENERICDATA) return("DpchEngWdbeModMdl1NGenericData");
	if (ix == DPCHENGWDBEMODMDL1NPORTDATA) return("DpchEngWdbeModMdl1NPortData");
	if (ix == DPCHENGWDBEMODMDL1NSIGNALDATA) return("DpchEngWdbeModMdl1NSignalData");
	if (ix == DPCHENGWDBEMODMGE1NSIGNALDATA) return("DpchEngWdbeModMge1NSignalData");
	if (ix == DPCHENGWDBEMODRECDATA) return("DpchEngWdbeModRecData");
	if (ix == DPCHENGWDBEMODSUP1NMODULEDATA) return("DpchEngWdbeModSup1NModuleData");
	if (ix == DPCHENGWDBEMTPAPARDATA) return("DpchEngWdbeMtpAParData");
	if (ix == DPCHENGWDBEMTPDATA) return("DpchEngWdbeMtpData");
	if (ix == DPCHENGWDBEMTPDETAILDATA) return("DpchEngWdbeMtpDetailData");
	if (ix == DPCHENGWDBEMTPHEADBARDATA) return("DpchEngWdbeMtpHeadbarData");
	if (ix == DPCHENGWDBEMTPKHDLTYPEDATA) return("DpchEngWdbeMtpKHdltypeData");
	if (ix == DPCHENGWDBEMTPKPARKEYDATA) return("DpchEngWdbeMtpKParKeyData");
	if (ix == DPCHENGWDBEMTPLISTDATA) return("DpchEngWdbeMtpListData");
	if (ix == DPCHENGWDBEMTPMDL1NGENERICDATA) return("DpchEngWdbeMtpMdl1NGenericData");
	if (ix == DPCHENGWDBEMTPMDL1NPORTDATA) return("DpchEngWdbeMtpMdl1NPortData");
	if (ix == DPCHENGWDBEMTPMGE1NSIGNALDATA) return("DpchEngWdbeMtpMge1NSignalData");
	if (ix == DPCHENGWDBEMTPRECDATA) return("DpchEngWdbeMtpRecData");
	if (ix == DPCHENGWDBEMTPREF1NFILEDATA) return("DpchEngWdbeMtpRef1NFileData");
	if (ix == DPCHENGWDBEMTPSUP1NMODULEDATA) return("DpchEngWdbeMtpSup1NModuleData");
	if (ix == DPCHENGWDBEMTPTPL1NMODULEDATA) return("DpchEngWdbeMtpTpl1NModuleData");
	if (ix == DPCHENGWDBENAVADMINDATA) return("DpchEngWdbeNavAdminData");
	if (ix == DPCHENGWDBENAVAUXFCTDATA) return("DpchEngWdbeNavAuxfctData");
	if (ix == DPCHENGWDBENAVCOREDEVDATA) return("DpchEngWdbeNavCoredevData");
	if (ix == DPCHENGWDBENAVDATA) return("DpchEngWdbeNavData");
	if (ix == DPCHENGWDBENAVDESCRDATA) return("DpchEngWdbeNavDescrData");
	if (ix == DPCHENGWDBENAVDEVDEVDATA) return("DpchEngWdbeNavDevdevData");
	if (ix == DPCHENGWDBENAVGLOBALDATA) return("DpchEngWdbeNavGlobalData");
	if (ix == DPCHENGWDBENAVHEADBARDATA) return("DpchEngWdbeNavHeadbarData");
	if (ix == DPCHENGWDBENAVPREDATA) return("DpchEngWdbeNavPreData");
	if (ix == DPCHENGWDBEPINAPARDATA) return("DpchEngWdbePinAParData");
	if (ix == DPCHENGWDBEPINDATA) return("DpchEngWdbePinData");
	if (ix == DPCHENGWDBEPINDETAILDATA) return("DpchEngWdbePinDetailData");
	if (ix == DPCHENGWDBEPINHEADBARDATA) return("DpchEngWdbePinHeadbarData");
	if (ix == DPCHENGWDBEPINLISTDATA) return("DpchEngWdbePinListData");
	if (ix == DPCHENGWDBEPINRECDATA) return("DpchEngWdbePinRecData");
	if (ix == DPCHENGWDBEPPHAPARDATA) return("DpchEngWdbePphAParData");
	if (ix == DPCHENGWDBEPPHDATA) return("DpchEngWdbePphData");
	if (ix == DPCHENGWDBEPPHDETAILDATA) return("DpchEngWdbePphDetailData");
	if (ix == DPCHENGWDBEPPHHEADBARDATA) return("DpchEngWdbePphHeadbarData");
	if (ix == DPCHENGWDBEPPHLISTDATA) return("DpchEngWdbePphListData");
	if (ix == DPCHENGWDBEPPHRECDATA) return("DpchEngWdbePphRecData");
	if (ix == DPCHENGWDBEPRCDATA) return("DpchEngWdbePrcData");
	if (ix == DPCHENGWDBEPRCDETAILDATA) return("DpchEngWdbePrcDetailData");
	if (ix == DPCHENGWDBEPRCFSMFSM1NFSMSTATEDATA) return("DpchEngWdbePrcFsmFsm1NFsmstateData");
	if (ix == DPCHENGWDBEPRCHEADBARDATA) return("DpchEngWdbePrcHeadbarData");
	if (ix == DPCHENGWDBEPRCKHDLTYPEDATA) return("DpchEngWdbePrcKHdltypeData");
	if (ix == DPCHENGWDBEPRCLISTDATA) return("DpchEngWdbePrcListData");
	if (ix == DPCHENGWDBEPRCMGE1NSIGNALDATA) return("DpchEngWdbePrcMge1NSignalData");
	if (ix == DPCHENGWDBEPRCPRC1NVARIABLEDATA) return("DpchEngWdbePrcPrc1NVariableData");
	if (ix == DPCHENGWDBEPRCRECDATA) return("DpchEngWdbePrcRecData");
	if (ix == DPCHENGWDBEPRJ1NVERSIONDATA) return("DpchEngWdbePrj1NVersionData");
	if (ix == DPCHENGWDBEPRJDATA) return("DpchEngWdbePrjData");
	if (ix == DPCHENGWDBEPRJDETAILDATA) return("DpchEngWdbePrjDetailData");
	if (ix == DPCHENGWDBEPRJHEADBARDATA) return("DpchEngWdbePrjHeadbarData");
	if (ix == DPCHENGWDBEPRJLISTDATA) return("DpchEngWdbePrjListData");
	if (ix == DPCHENGWDBEPRJMNPERSONDATA) return("DpchEngWdbePrjMNPersonData");
	if (ix == DPCHENGWDBEPRJRECDATA) return("DpchEngWdbePrjRecData");
	if (ix == DPCHENGWDBEPRSADETAILDATA) return("DpchEngWdbePrsADetailData");
	if (ix == DPCHENGWDBEPRSDATA) return("DpchEngWdbePrsData");
	if (ix == DPCHENGWDBEPRSDETAILDATA) return("DpchEngWdbePrsDetailData");
	if (ix == DPCHENGWDBEPRSHEADBARDATA) return("DpchEngWdbePrsHeadbarData");
	if (ix == DPCHENGWDBEPRSLISTDATA) return("DpchEngWdbePrsListData");
	if (ix == DPCHENGWDBEPRSMNCOREPROJECTDATA) return("DpchEngWdbePrsMNCoreprojectData");
	if (ix == DPCHENGWDBEPRSMNPROJECTDATA) return("DpchEngWdbePrsMNProjectData");
	if (ix == DPCHENGWDBEPRSRECDATA) return("DpchEngWdbePrsRecData");
	if (ix == DPCHENGWDBEPRTDATA) return("DpchEngWdbePrtData");
	if (ix == DPCHENGWDBEPRTDETAILDATA) return("DpchEngWdbePrtDetailData");
	if (ix == DPCHENGWDBEPRTHEADBARDATA) return("DpchEngWdbePrtHeadbarData");
	if (ix == DPCHENGWDBEPRTLISTDATA) return("DpchEngWdbePrtListData");
	if (ix == DPCHENGWDBEPRTRECDATA) return("DpchEngWdbePrtRecData");
	if (ix == DPCHENGWDBERLSDATA) return("DpchEngWdbeRlsData");
	if (ix == DPCHENGWDBERLSDETAILDATA) return("DpchEngWdbeRlsDetailData");
	if (ix == DPCHENGWDBERLSHEADBARDATA) return("DpchEngWdbeRlsHeadbarData");
	if (ix == DPCHENGWDBERLSLISTDATA) return("DpchEngWdbeRlsListData");
	if (ix == DPCHENGWDBERLSRECDATA) return("DpchEngWdbeRlsRecData");
	if (ix == DPCHENGWDBESIGDATA) return("DpchEngWdbeSigData");
	if (ix == DPCHENGWDBESIGDETAILDATA) return("DpchEngWdbeSigDetailData");
	if (ix == DPCHENGWDBESIGHEADBARDATA) return("DpchEngWdbeSigHeadbarData");
	if (ix == DPCHENGWDBESIGLISTDATA) return("DpchEngWdbeSigListData");
	if (ix == DPCHENGWDBESIGRECDATA) return("DpchEngWdbeSigRecData");
	if (ix == DPCHENGWDBESIL1NBANKDATA) return("DpchEngWdbeSil1NBankData");
	if (ix == DPCHENGWDBESIL1NPERIPHERALDATA) return("DpchEngWdbeSil1NPeripheralData");
	if (ix == DPCHENGWDBESIL1NTARGETDATA) return("DpchEngWdbeSil1NTargetData");
	if (ix == DPCHENGWDBESILDATA) return("DpchEngWdbeSilData");
	if (ix == DPCHENGWDBESILDETAILDATA) return("DpchEngWdbeSilDetailData");
	if (ix == DPCHENGWDBESILFWD1NCONTROLLERDATA) return("DpchEngWdbeSilFwd1NControllerData");
	if (ix == DPCHENGWDBESILHEADBARDATA) return("DpchEngWdbeSilHeadbarData");
	if (ix == DPCHENGWDBESILHK1NMODULEDATA) return("DpchEngWdbeSilHk1NModuleData");
	if (ix == DPCHENGWDBESILHK1NVECTORDATA) return("DpchEngWdbeSilHk1NVectorData");
	if (ix == DPCHENGWDBESILLISTDATA) return("DpchEngWdbeSilListData");
	if (ix == DPCHENGWDBESILRECDATA) return("DpchEngWdbeSilRecData");
	if (ix == DPCHENGWDBESILREF1NCOMMANDDATA) return("DpchEngWdbeSilRef1NCommandData");
	if (ix == DPCHENGWDBESILREF1NERRORDATA) return("DpchEngWdbeSilRef1NErrorData");
	if (ix == DPCHENGWDBESILSIL1NUNITDATA) return("DpchEngWdbeSilSil1NUnitData");
	if (ix == DPCHENGWDBESUSPEND) return("DpchEngWdbeSuspend");
	if (ix == DPCHENGWDBESYSDATA) return("DpchEngWdbeSysData");
	if (ix == DPCHENGWDBESYSDETAILDATA) return("DpchEngWdbeSysDetailData");
	if (ix == DPCHENGWDBESYSHEADBARDATA) return("DpchEngWdbeSysHeadbarData");
	if (ix == DPCHENGWDBESYSHK1NVECTORDATA) return("DpchEngWdbeSysHk1NVectorData");
	if (ix == DPCHENGWDBESYSLISTDATA) return("DpchEngWdbeSysListData");
	if (ix == DPCHENGWDBESYSRECDATA) return("DpchEngWdbeSysRecData");
	if (ix == DPCHENGWDBESYSSYS1NTARGETDATA) return("DpchEngWdbeSysSys1NTargetData");
	if (ix == DPCHENGWDBETRGDATA) return("DpchEngWdbeTrgData");
	if (ix == DPCHENGWDBETRGDETAILDATA) return("DpchEngWdbeTrgDetailData");
	if (ix == DPCHENGWDBETRGHEADBARDATA) return("DpchEngWdbeTrgHeadbarData");
	if (ix == DPCHENGWDBETRGLISTDATA) return("DpchEngWdbeTrgListData");
	if (ix == DPCHENGWDBETRGRECDATA) return("DpchEngWdbeTrgRecData");
	if (ix == DPCHENGWDBEUNT1NBANKDATA) return("DpchEngWdbeUnt1NBankData");
	if (ix == DPCHENGWDBEUNT1NPERIPHERALDATA) return("DpchEngWdbeUnt1NPeripheralData");
	if (ix == DPCHENGWDBEUNT1NTARGETDATA) return("DpchEngWdbeUnt1NTargetData");
	if (ix == DPCHENGWDBEUNTDATA) return("DpchEngWdbeUntData");
	if (ix == DPCHENGWDBEUNTDETAILDATA) return("DpchEngWdbeUntDetailData");
	if (ix == DPCHENGWDBEUNTFWD1NCONTROLLERDATA) return("DpchEngWdbeUntFwd1NControllerData");
	if (ix == DPCHENGWDBEUNTHEADBARDATA) return("DpchEngWdbeUntHeadbarData");
	if (ix == DPCHENGWDBEUNTHK1NMODULEDATA) return("DpchEngWdbeUntHk1NModuleData");
	if (ix == DPCHENGWDBEUNTHK1NVECTORDATA) return("DpchEngWdbeUntHk1NVectorData");
	if (ix == DPCHENGWDBEUNTLISTDATA) return("DpchEngWdbeUntListData");
	if (ix == DPCHENGWDBEUNTRECDATA) return("DpchEngWdbeUntRecData");
	if (ix == DPCHENGWDBEUNTREF1NCOMMANDDATA) return("DpchEngWdbeUntRef1NCommandData");
	if (ix == DPCHENGWDBEUNTREF1NERRORDATA) return("DpchEngWdbeUntRef1NErrorData");
	if (ix == DPCHENGWDBEUNTSIL1NUNITDATA) return("DpchEngWdbeUntSil1NUnitData");
	if (ix == DPCHENGWDBEUSGAACCESSDATA) return("DpchEngWdbeUsgAAccessData");
	if (ix == DPCHENGWDBEUSGDATA) return("DpchEngWdbeUsgData");
	if (ix == DPCHENGWDBEUSGDETAILDATA) return("DpchEngWdbeUsgDetailData");
	if (ix == DPCHENGWDBEUSGHEADBARDATA) return("DpchEngWdbeUsgHeadbarData");
	if (ix == DPCHENGWDBEUSGLISTDATA) return("DpchEngWdbeUsgListData");
	if (ix == DPCHENGWDBEUSGMNUSERDATA) return("DpchEngWdbeUsgMNUserData");
	if (ix == DPCHENGWDBEUSGRECDATA) return("DpchEngWdbeUsgRecData");
	if (ix == DPCHENGWDBEUSR1NSESSIONDATA) return("DpchEngWdbeUsr1NSessionData");
	if (ix == DPCHENGWDBEUSRAACCESSDATA) return("DpchEngWdbeUsrAAccessData");
	if (ix == DPCHENGWDBEUSRDATA) return("DpchEngWdbeUsrData");
	if (ix == DPCHENGWDBEUSRDETAILDATA) return("DpchEngWdbeUsrDetailData");
	if (ix == DPCHENGWDBEUSRHEADBARDATA) return("DpchEngWdbeUsrHeadbarData");
	if (ix == DPCHENGWDBEUSRLISTDATA) return("DpchEngWdbeUsrListData");
	if (ix == DPCHENGWDBEUSRMNUSERGROUPDATA) return("DpchEngWdbeUsrMNUsergroupData");
	if (ix == DPCHENGWDBEUSRRECDATA) return("DpchEngWdbeUsrRecData");
	if (ix == DPCHENGWDBEUTLDATA) return("DpchEngWdbeUtlData");
	if (ix == DPCHENGWDBEUTLHEADBARDATA) return("DpchEngWdbeUtlHeadbarData");
	if (ix == DPCHENGWDBEVARDATA) return("DpchEngWdbeVarData");
	if (ix == DPCHENGWDBEVARDETAILDATA) return("DpchEngWdbeVarDetailData");
	if (ix == DPCHENGWDBEVARHEADBARDATA) return("DpchEngWdbeVarHeadbarData");
	if (ix == DPCHENGWDBEVARLISTDATA) return("DpchEngWdbeVarListData");
	if (ix == DPCHENGWDBEVARRECDATA) return("DpchEngWdbeVarRecData");
	if (ix == DPCHENGWDBEVECDATA) return("DpchEngWdbeVecData");
	if (ix == DPCHENGWDBEVECDETAILDATA) return("DpchEngWdbeVecDetailData");
	if (ix == DPCHENGWDBEVECHEADBARDATA) return("DpchEngWdbeVecHeadbarData");
	if (ix == DPCHENGWDBEVECLISTDATA) return("DpchEngWdbeVecListData");
	if (ix == DPCHENGWDBEVECRECDATA) return("DpchEngWdbeVecRecData");
	if (ix == DPCHENGWDBEVECVEC1NVECTORITEMDATA) return("DpchEngWdbeVecVec1NVectoritemData");
	if (ix == DPCHENGWDBEVER1NRELEASEDATA) return("DpchEngWdbeVer1NReleaseData");
	if (ix == DPCHENGWDBEVER1NSYSTEMDATA) return("DpchEngWdbeVer1NSystemData");
	if (ix == DPCHENGWDBEVER1NUNITDATA) return("DpchEngWdbeVer1NUnitData");
	if (ix == DPCHENGWDBEVERBVR1NVERSIONDATA) return("DpchEngWdbeVerBvr1NVersionData");
	if (ix == DPCHENGWDBEVERDATA) return("DpchEngWdbeVerData");
	if (ix == DPCHENGWDBEVERDETAILDATA) return("DpchEngWdbeVerDetailData");
	if (ix == DPCHENGWDBEVERHEADBARDATA) return("DpchEngWdbeVerHeadbarData");
	if (ix == DPCHENGWDBEVERLISTDATA) return("DpchEngWdbeVerListData");
	if (ix == DPCHENGWDBEVERMNLIBRARYDATA) return("DpchEngWdbeVerMNLibraryData");
	if (ix == DPCHENGWDBEVERRECDATA) return("DpchEngWdbeVerRecData");
	if (ix == DPCHENGWDBEVERREF1NFILEDATA) return("DpchEngWdbeVerRef1NFileData");
	if (ix == DPCHENGWDBEVITDATA) return("DpchEngWdbeVitData");
	if (ix == DPCHENGWDBEVITDETAILDATA) return("DpchEngWdbeVitDetailData");
	if (ix == DPCHENGWDBEVITHEADBARDATA) return("DpchEngWdbeVitHeadbarData");
	if (ix == DPCHENGWDBEVITLISTDATA) return("DpchEngWdbeVitListData");
	if (ix == DPCHENGWDBEVITRECDATA) return("DpchEngWdbeVitRecData");
	if (ix == DPCHAPPDLGWDBECPRNEWDATA) return("DpchAppDlgWdbeCprNewData");
	if (ix == DPCHAPPDLGWDBECPRNEWDO) return("DpchAppDlgWdbeCprNewDo");
	if (ix == DPCHAPPDLGWDBECVRBSCCDDATA) return("DpchAppDlgWdbeCvrBsccdData");
	if (ix == DPCHAPPDLGWDBECVRBSCCDDO) return("DpchAppDlgWdbeCvrBsccdDo");
	if (ix == DPCHAPPDLGWDBECVRDETCDDATA) return("DpchAppDlgWdbeCvrDetcdData");
	if (ix == DPCHAPPDLGWDBECVRDETCDDO) return("DpchAppDlgWdbeCvrDetcdDo");
	if (ix == DPCHAPPDLGWDBECVRNEWDATA) return("DpchAppDlgWdbeCvrNewData");
	if (ix == DPCHAPPDLGWDBECVRNEWDO) return("DpchAppDlgWdbeCvrNewDo");
	if (ix == DPCHAPPDLGWDBECVRWRITEDATA) return("DpchAppDlgWdbeCvrWriteData");
	if (ix == DPCHAPPDLGWDBECVRWRITEDO) return("DpchAppDlgWdbeCvrWriteDo");
	if (ix == DPCHAPPDLGWDBEFILDOWNLOADDO) return("DpchAppDlgWdbeFilDownloadDo");
	if (ix == DPCHAPPDLGWDBEFILNEWDATA) return("DpchAppDlgWdbeFilNewData");
	if (ix == DPCHAPPDLGWDBEFILNEWDO) return("DpchAppDlgWdbeFilNewDo");
	if (ix == DPCHAPPDLGWDBENAVLOAINIDATA) return("DpchAppDlgWdbeNavLoainiData");
	if (ix == DPCHAPPDLGWDBENAVLOAINIDO) return("DpchAppDlgWdbeNavLoainiDo");
	if (ix == DPCHAPPDLGWDBENAVMNGLICDATA) return("DpchAppDlgWdbeNavMnglicData");
	if (ix == DPCHAPPDLGWDBENAVMNGLICDO) return("DpchAppDlgWdbeNavMnglicDo");
	if (ix == DPCHAPPDLGWDBEPRJIMPEXDATA) return("DpchAppDlgWdbePrjImpexData");
	if (ix == DPCHAPPDLGWDBEPRJIMPEXDO) return("DpchAppDlgWdbePrjImpexDo");
	if (ix == DPCHAPPDLGWDBEPRJNEWDATA) return("DpchAppDlgWdbePrjNewData");
	if (ix == DPCHAPPDLGWDBEPRJNEWDO) return("DpchAppDlgWdbePrjNewDo");
	if (ix == DPCHAPPDLGWDBERLSFINREPTRDATA) return("DpchAppDlgWdbeRlsFinreptrData");
	if (ix == DPCHAPPDLGWDBERLSFINREPTRDO) return("DpchAppDlgWdbeRlsFinreptrDo");
	if (ix == DPCHAPPDLGWDBERLSNEWDATA) return("DpchAppDlgWdbeRlsNewData");
	if (ix == DPCHAPPDLGWDBERLSNEWDO) return("DpchAppDlgWdbeRlsNewDo");
	if (ix == DPCHAPPDLGWDBERLSSTAREPTRDATA) return("DpchAppDlgWdbeRlsStareptrData");
	if (ix == DPCHAPPDLGWDBERLSSTAREPTRDO) return("DpchAppDlgWdbeRlsStareptrDo");
	if (ix == DPCHAPPDLGWDBERLSWRITEDATA) return("DpchAppDlgWdbeRlsWriteData");
	if (ix == DPCHAPPDLGWDBERLSWRITEDO) return("DpchAppDlgWdbeRlsWriteDo");
	if (ix == DPCHAPPDLGWDBEUSRMNGKEYPAIRDO) return("DpchAppDlgWdbeUsrMngkeypairDo");
	if (ix == DPCHAPPDLGWDBEUTLEXTRIPDATA) return("DpchAppDlgWdbeUtlExtripData");
	if (ix == DPCHAPPDLGWDBEUTLEXTRIPDO) return("DpchAppDlgWdbeUtlExtripDo");
	if (ix == DPCHAPPDLGWDBEUTLIEXCONVDATA) return("DpchAppDlgWdbeUtlIexconvData");
	if (ix == DPCHAPPDLGWDBEUTLIEXCONVDO) return("DpchAppDlgWdbeUtlIexconvDo");
	if (ix == DPCHAPPDLGWDBEUTLMRGIPDATA) return("DpchAppDlgWdbeUtlMrgipData");
	if (ix == DPCHAPPDLGWDBEUTLMRGIPDO) return("DpchAppDlgWdbeUtlMrgipDo");
	if (ix == DPCHAPPDLGWDBEVERBSCDDDATA) return("DpchAppDlgWdbeVerBscddData");
	if (ix == DPCHAPPDLGWDBEVERBSCDDDO) return("DpchAppDlgWdbeVerBscddDo");
	if (ix == DPCHAPPDLGWDBEVERDETDDDATA) return("DpchAppDlgWdbeVerDetddData");
	if (ix == DPCHAPPDLGWDBEVERDETDDDO) return("DpchAppDlgWdbeVerDetddDo");
	if (ix == DPCHAPPDLGWDBEVERNEWDATA) return("DpchAppDlgWdbeVerNewData");
	if (ix == DPCHAPPDLGWDBEVERNEWDO) return("DpchAppDlgWdbeVerNewDo");
	if (ix == DPCHAPPROOTWDBELOGIN) return("DpchAppRootWdbeLogin");
	if (ix == DPCHAPPWDBEALERT) return("DpchAppWdbeAlert");
	if (ix == DPCHAPPWDBEBNK1NPINDATA) return("DpchAppWdbeBnk1NPinData");
	if (ix == DPCHAPPWDBEBNK1NPINDO) return("DpchAppWdbeBnk1NPinDo");
	if (ix == DPCHAPPWDBEBNKDETAILDATA) return("DpchAppWdbeBnkDetailData");
	if (ix == DPCHAPPWDBEBNKDETAILDO) return("DpchAppWdbeBnkDetailDo");
	if (ix == DPCHAPPWDBEBNKDO) return("DpchAppWdbeBnkDo");
	if (ix == DPCHAPPWDBEBNKLISTDATA) return("DpchAppWdbeBnkListData");
	if (ix == DPCHAPPWDBEBNKLISTDO) return("DpchAppWdbeBnkListDo");
	if (ix == DPCHAPPWDBEBNKRECDO) return("DpchAppWdbeBnkRecDo");
	if (ix == DPCHAPPWDBECMDAINVPARDATA) return("DpchAppWdbeCmdAInvparData");
	if (ix == DPCHAPPWDBECMDAINVPARDO) return("DpchAppWdbeCmdAInvparDo");
	if (ix == DPCHAPPWDBECMDARETPARDATA) return("DpchAppWdbeCmdARetparData");
	if (ix == DPCHAPPWDBECMDARETPARDO) return("DpchAppWdbeCmdARetparDo");
	if (ix == DPCHAPPWDBECMDDETAILDATA) return("DpchAppWdbeCmdDetailData");
	if (ix == DPCHAPPWDBECMDDETAILDO) return("DpchAppWdbeCmdDetailDo");
	if (ix == DPCHAPPWDBECMDDO) return("DpchAppWdbeCmdDo");
	if (ix == DPCHAPPWDBECMDLISTDATA) return("DpchAppWdbeCmdListData");
	if (ix == DPCHAPPWDBECMDLISTDO) return("DpchAppWdbeCmdListDo");
	if (ix == DPCHAPPWDBECMDMNCONTROLLERDATA) return("DpchAppWdbeCmdMNControllerData");
	if (ix == DPCHAPPWDBECMDMNCONTROLLERDO) return("DpchAppWdbeCmdMNControllerDo");
	if (ix == DPCHAPPWDBECMDRECDO) return("DpchAppWdbeCmdRecDo");
	if (ix == DPCHAPPWDBECPR1NCOREVERSIONDATA) return("DpchAppWdbeCpr1NCoreversionData");
	if (ix == DPCHAPPWDBECPR1NCOREVERSIONDO) return("DpchAppWdbeCpr1NCoreversionDo");
	if (ix == DPCHAPPWDBECPRDETAILDATA) return("DpchAppWdbeCprDetailData");
	if (ix == DPCHAPPWDBECPRDETAILDO) return("DpchAppWdbeCprDetailDo");
	if (ix == DPCHAPPWDBECPRDO) return("DpchAppWdbeCprDo");
	if (ix == DPCHAPPWDBECPRLISTDATA) return("DpchAppWdbeCprListData");
	if (ix == DPCHAPPWDBECPRLISTDO) return("DpchAppWdbeCprListDo");
	if (ix == DPCHAPPWDBECPRMNPERSONDATA) return("DpchAppWdbeCprMNPersonData");
	if (ix == DPCHAPPWDBECPRMNPERSONDO) return("DpchAppWdbeCprMNPersonDo");
	if (ix == DPCHAPPWDBECPRRECDO) return("DpchAppWdbeCprRecDo");
	if (ix == DPCHAPPWDBECVRAIPDATA) return("DpchAppWdbeCvrAIpData");
	if (ix == DPCHAPPWDBECVRAIPDO) return("DpchAppWdbeCvrAIpDo");
	if (ix == DPCHAPPWDBECVRAPLHDATA) return("DpchAppWdbeCvrAPlhData");
	if (ix == DPCHAPPWDBECVRAPLHDO) return("DpchAppWdbeCvrAPlhDo");
	if (ix == DPCHAPPWDBECVRBCV1NCOREVERSIONDATA) return("DpchAppWdbeCvrBcv1NCoreversionData");
	if (ix == DPCHAPPWDBECVRBCV1NCOREVERSIONDO) return("DpchAppWdbeCvrBcv1NCoreversionDo");
	if (ix == DPCHAPPWDBECVRDETAILDATA) return("DpchAppWdbeCvrDetailData");
	if (ix == DPCHAPPWDBECVRDETAILDO) return("DpchAppWdbeCvrDetailDo");
	if (ix == DPCHAPPWDBECVRDO) return("DpchAppWdbeCvrDo");
	if (ix == DPCHAPPWDBECVRHK1NMODULEDATA) return("DpchAppWdbeCvrHk1NModuleData");
	if (ix == DPCHAPPWDBECVRHK1NMODULEDO) return("DpchAppWdbeCvrHk1NModuleDo");
	if (ix == DPCHAPPWDBECVRLISTDATA) return("DpchAppWdbeCvrListData");
	if (ix == DPCHAPPWDBECVRLISTDO) return("DpchAppWdbeCvrListDo");
	if (ix == DPCHAPPWDBECVRRECDO) return("DpchAppWdbeCvrRecDo");
	if (ix == DPCHAPPWDBEERRAPARDATA) return("DpchAppWdbeErrAParData");
	if (ix == DPCHAPPWDBEERRAPARDO) return("DpchAppWdbeErrAParDo");
	if (ix == DPCHAPPWDBEERRDETAILDATA) return("DpchAppWdbeErrDetailData");
	if (ix == DPCHAPPWDBEERRDETAILDO) return("DpchAppWdbeErrDetailDo");
	if (ix == DPCHAPPWDBEERRDO) return("DpchAppWdbeErrDo");
	if (ix == DPCHAPPWDBEERRLISTDATA) return("DpchAppWdbeErrListData");
	if (ix == DPCHAPPWDBEERRLISTDO) return("DpchAppWdbeErrListDo");
	if (ix == DPCHAPPWDBEERRRECDO) return("DpchAppWdbeErrRecDo");
	if (ix == DPCHAPPWDBEFAM1NUNITDATA) return("DpchAppWdbeFam1NUnitData");
	if (ix == DPCHAPPWDBEFAM1NUNITDO) return("DpchAppWdbeFam1NUnitDo");
	if (ix == DPCHAPPWDBEFAMDETAILDATA) return("DpchAppWdbeFamDetailData");
	if (ix == DPCHAPPWDBEFAMDETAILDO) return("DpchAppWdbeFamDetailDo");
	if (ix == DPCHAPPWDBEFAMDO) return("DpchAppWdbeFamDo");
	if (ix == DPCHAPPWDBEFAMLISTDATA) return("DpchAppWdbeFamListData");
	if (ix == DPCHAPPWDBEFAMLISTDO) return("DpchAppWdbeFamListDo");
	if (ix == DPCHAPPWDBEFAMRECDO) return("DpchAppWdbeFamRecDo");
	if (ix == DPCHAPPWDBEFILDETAILDATA) return("DpchAppWdbeFilDetailData");
	if (ix == DPCHAPPWDBEFILDETAILDO) return("DpchAppWdbeFilDetailDo");
	if (ix == DPCHAPPWDBEFILDO) return("DpchAppWdbeFilDo");
	if (ix == DPCHAPPWDBEFILLISTDATA) return("DpchAppWdbeFilListData");
	if (ix == DPCHAPPWDBEFILLISTDO) return("DpchAppWdbeFilListDo");
	if (ix == DPCHAPPWDBEFILRECDO) return("DpchAppWdbeFilRecDo");
	if (ix == DPCHAPPWDBEFSTASTEPDATA) return("DpchAppWdbeFstAStepData");
	if (ix == DPCHAPPWDBEFSTASTEPDO) return("DpchAppWdbeFstAStepDo");
	if (ix == DPCHAPPWDBEFSTDETAILDATA) return("DpchAppWdbeFstDetailData");
	if (ix == DPCHAPPWDBEFSTDETAILDO) return("DpchAppWdbeFstDetailDo");
	if (ix == DPCHAPPWDBEFSTDO) return("DpchAppWdbeFstDo");
	if (ix == DPCHAPPWDBEFSTLISTDATA) return("DpchAppWdbeFstListData");
	if (ix == DPCHAPPWDBEFSTLISTDO) return("DpchAppWdbeFstListDo");
	if (ix == DPCHAPPWDBEFSTRECDO) return("DpchAppWdbeFstRecDo");
	if (ix == DPCHAPPWDBEGENDETAILDATA) return("DpchAppWdbeGenDetailData");
	if (ix == DPCHAPPWDBEGENDETAILDO) return("DpchAppWdbeGenDetailDo");
	if (ix == DPCHAPPWDBEGENDO) return("DpchAppWdbeGenDo");
	if (ix == DPCHAPPWDBEGENLISTDATA) return("DpchAppWdbeGenListData");
	if (ix == DPCHAPPWDBEGENLISTDO) return("DpchAppWdbeGenListDo");
	if (ix == DPCHAPPWDBEGENRECDO) return("DpchAppWdbeGenRecDo");
	if (ix == DPCHAPPWDBEINIT) return("DpchAppWdbeInit");
	if (ix == DPCHAPPWDBELIBAMAKEFILEDATA) return("DpchAppWdbeLibAMakefileData");
	if (ix == DPCHAPPWDBELIBAMAKEFILEDO) return("DpchAppWdbeLibAMakefileDo");
	if (ix == DPCHAPPWDBELIBDETAILDATA) return("DpchAppWdbeLibDetailData");
	if (ix == DPCHAPPWDBELIBDETAILDO) return("DpchAppWdbeLibDetailDo");
	if (ix == DPCHAPPWDBELIBDO) return("DpchAppWdbeLibDo");
	if (ix == DPCHAPPWDBELIBLISTDATA) return("DpchAppWdbeLibListData");
	if (ix == DPCHAPPWDBELIBLISTDO) return("DpchAppWdbeLibListDo");
	if (ix == DPCHAPPWDBELIBMNVERSIONDATA) return("DpchAppWdbeLibMNVersionData");
	if (ix == DPCHAPPWDBELIBMNVERSIONDO) return("DpchAppWdbeLibMNVersionDo");
	if (ix == DPCHAPPWDBELIBRECDO) return("DpchAppWdbeLibRecDo");
	if (ix == DPCHAPPWDBEMCH1NRELEASEDATA) return("DpchAppWdbeMch1NReleaseData");
	if (ix == DPCHAPPWDBEMCH1NRELEASEDO) return("DpchAppWdbeMch1NReleaseDo");
	if (ix == DPCHAPPWDBEMCHAMAKEFILEDATA) return("DpchAppWdbeMchAMakefileData");
	if (ix == DPCHAPPWDBEMCHAMAKEFILEDO) return("DpchAppWdbeMchAMakefileDo");
	if (ix == DPCHAPPWDBEMCHAPARDATA) return("DpchAppWdbeMchAParData");
	if (ix == DPCHAPPWDBEMCHAPARDO) return("DpchAppWdbeMchAParDo");
	if (ix == DPCHAPPWDBEMCHDETAILDATA) return("DpchAppWdbeMchDetailData");
	if (ix == DPCHAPPWDBEMCHDETAILDO) return("DpchAppWdbeMchDetailDo");
	if (ix == DPCHAPPWDBEMCHDO) return("DpchAppWdbeMchDo");
	if (ix == DPCHAPPWDBEMCHLISTDATA) return("DpchAppWdbeMchListData");
	if (ix == DPCHAPPWDBEMCHLISTDO) return("DpchAppWdbeMchListDo");
	if (ix == DPCHAPPWDBEMCHRECDO) return("DpchAppWdbeMchRecDo");
	if (ix == DPCHAPPWDBEMOD1NPERIPHERALDATA) return("DpchAppWdbeMod1NPeripheralData");
	if (ix == DPCHAPPWDBEMOD1NPERIPHERALDO) return("DpchAppWdbeMod1NPeripheralDo");
	if (ix == DPCHAPPWDBEMOD1NPROCESSDATA) return("DpchAppWdbeMod1NProcessData");
	if (ix == DPCHAPPWDBEMOD1NPROCESSDO) return("DpchAppWdbeMod1NProcessDo");
	if (ix == DPCHAPPWDBEMODAPARDATA) return("DpchAppWdbeModAParData");
	if (ix == DPCHAPPWDBEMODAPARDO) return("DpchAppWdbeModAParDo");
	if (ix == DPCHAPPWDBEMODCOR1NIMBUFDATA) return("DpchAppWdbeModCor1NImbufData");
	if (ix == DPCHAPPWDBEMODCOR1NIMBUFDO) return("DpchAppWdbeModCor1NImbufDo");
	if (ix == DPCHAPPWDBEMODCTRHK1NVECTORDATA) return("DpchAppWdbeModCtrHk1NVectorData");
	if (ix == DPCHAPPWDBEMODCTRHK1NVECTORDO) return("DpchAppWdbeModCtrHk1NVectorDo");
	if (ix == DPCHAPPWDBEMODCTRMNCOMMANDDATA) return("DpchAppWdbeModCtrMNCommandData");
	if (ix == DPCHAPPWDBEMODCTRMNCOMMANDDO) return("DpchAppWdbeModCtrMNCommandDo");
	if (ix == DPCHAPPWDBEMODCTRREF1NCOMMANDDATA) return("DpchAppWdbeModCtrRef1NCommandData");
	if (ix == DPCHAPPWDBEMODCTRREF1NCOMMANDDO) return("DpchAppWdbeModCtrRef1NCommandDo");
	if (ix == DPCHAPPWDBEMODCTRREF1NERRORDATA) return("DpchAppWdbeModCtrRef1NErrorData");
	if (ix == DPCHAPPWDBEMODCTRREF1NERRORDO) return("DpchAppWdbeModCtrRef1NErrorDo");
	if (ix == DPCHAPPWDBEMODDETAILDATA) return("DpchAppWdbeModDetailData");
	if (ix == DPCHAPPWDBEMODDETAILDO) return("DpchAppWdbeModDetailDo");
	if (ix == DPCHAPPWDBEMODDO) return("DpchAppWdbeModDo");
	if (ix == DPCHAPPWDBEMODKHDLTYPEDATA) return("DpchAppWdbeModKHdltypeData");
	if (ix == DPCHAPPWDBEMODKHDLTYPEDO) return("DpchAppWdbeModKHdltypeDo");
	if (ix == DPCHAPPWDBEMODLISTDATA) return("DpchAppWdbeModListData");
	if (ix == DPCHAPPWDBEMODLISTDO) return("DpchAppWdbeModListDo");
	if (ix == DPCHAPPWDBEMODMDL1NGENERICDATA) return("DpchAppWdbeModMdl1NGenericData");
	if (ix == DPCHAPPWDBEMODMDL1NGENERICDO) return("DpchAppWdbeModMdl1NGenericDo");
	if (ix == DPCHAPPWDBEMODMDL1NPORTDATA) return("DpchAppWdbeModMdl1NPortData");
	if (ix == DPCHAPPWDBEMODMDL1NPORTDO) return("DpchAppWdbeModMdl1NPortDo");
	if (ix == DPCHAPPWDBEMODMDL1NSIGNALDATA) return("DpchAppWdbeModMdl1NSignalData");
	if (ix == DPCHAPPWDBEMODMDL1NSIGNALDO) return("DpchAppWdbeModMdl1NSignalDo");
	if (ix == DPCHAPPWDBEMODMGE1NSIGNALDATA) return("DpchAppWdbeModMge1NSignalData");
	if (ix == DPCHAPPWDBEMODMGE1NSIGNALDO) return("DpchAppWdbeModMge1NSignalDo");
	if (ix == DPCHAPPWDBEMODRECDO) return("DpchAppWdbeModRecDo");
	if (ix == DPCHAPPWDBEMODSUP1NMODULEDATA) return("DpchAppWdbeModSup1NModuleData");
	if (ix == DPCHAPPWDBEMODSUP1NMODULEDO) return("DpchAppWdbeModSup1NModuleDo");
	if (ix == DPCHAPPWDBEMTPAPARDATA) return("DpchAppWdbeMtpAParData");
	if (ix == DPCHAPPWDBEMTPAPARDO) return("DpchAppWdbeMtpAParDo");
	if (ix == DPCHAPPWDBEMTPDETAILDATA) return("DpchAppWdbeMtpDetailData");
	if (ix == DPCHAPPWDBEMTPDETAILDO) return("DpchAppWdbeMtpDetailDo");
	if (ix == DPCHAPPWDBEMTPDO) return("DpchAppWdbeMtpDo");
	if (ix == DPCHAPPWDBEMTPKHDLTYPEDATA) return("DpchAppWdbeMtpKHdltypeData");
	if (ix == DPCHAPPWDBEMTPKHDLTYPEDO) return("DpchAppWdbeMtpKHdltypeDo");
	if (ix == DPCHAPPWDBEMTPKPARKEYDATA) return("DpchAppWdbeMtpKParKeyData");
	if (ix == DPCHAPPWDBEMTPKPARKEYDO) return("DpchAppWdbeMtpKParKeyDo");
	if (ix == DPCHAPPWDBEMTPLISTDATA) return("DpchAppWdbeMtpListData");
	if (ix == DPCHAPPWDBEMTPLISTDO) return("DpchAppWdbeMtpListDo");
	if (ix == DPCHAPPWDBEMTPMDL1NGENERICDATA) return("DpchAppWdbeMtpMdl1NGenericData");
	if (ix == DPCHAPPWDBEMTPMDL1NGENERICDO) return("DpchAppWdbeMtpMdl1NGenericDo");
	if (ix == DPCHAPPWDBEMTPMDL1NPORTDATA) return("DpchAppWdbeMtpMdl1NPortData");
	if (ix == DPCHAPPWDBEMTPMDL1NPORTDO) return("DpchAppWdbeMtpMdl1NPortDo");
	if (ix == DPCHAPPWDBEMTPMGE1NSIGNALDATA) return("DpchAppWdbeMtpMge1NSignalData");
	if (ix == DPCHAPPWDBEMTPMGE1NSIGNALDO) return("DpchAppWdbeMtpMge1NSignalDo");
	if (ix == DPCHAPPWDBEMTPRECDO) return("DpchAppWdbeMtpRecDo");
	if (ix == DPCHAPPWDBEMTPREF1NFILEDATA) return("DpchAppWdbeMtpRef1NFileData");
	if (ix == DPCHAPPWDBEMTPREF1NFILEDO) return("DpchAppWdbeMtpRef1NFileDo");
	if (ix == DPCHAPPWDBEMTPSUP1NMODULEDATA) return("DpchAppWdbeMtpSup1NModuleData");
	if (ix == DPCHAPPWDBEMTPSUP1NMODULEDO) return("DpchAppWdbeMtpSup1NModuleDo");
	if (ix == DPCHAPPWDBEMTPTPL1NMODULEDATA) return("DpchAppWdbeMtpTpl1NModuleData");
	if (ix == DPCHAPPWDBEMTPTPL1NMODULEDO) return("DpchAppWdbeMtpTpl1NModuleDo");
	if (ix == DPCHAPPWDBENAVADMINDATA) return("DpchAppWdbeNavAdminData");
	if (ix == DPCHAPPWDBENAVADMINDO) return("DpchAppWdbeNavAdminDo");
	if (ix == DPCHAPPWDBENAVAUXFCTDO) return("DpchAppWdbeNavAuxfctDo");
	if (ix == DPCHAPPWDBENAVCOREDEVDATA) return("DpchAppWdbeNavCoredevData");
	if (ix == DPCHAPPWDBENAVCOREDEVDO) return("DpchAppWdbeNavCoredevDo");
	if (ix == DPCHAPPWDBENAVDESCRDATA) return("DpchAppWdbeNavDescrData");
	if (ix == DPCHAPPWDBENAVDESCRDO) return("DpchAppWdbeNavDescrDo");
	if (ix == DPCHAPPWDBENAVDEVDEVDATA) return("DpchAppWdbeNavDevdevData");
	if (ix == DPCHAPPWDBENAVDEVDEVDO) return("DpchAppWdbeNavDevdevDo");
	if (ix == DPCHAPPWDBENAVDO) return("DpchAppWdbeNavDo");
	if (ix == DPCHAPPWDBENAVGLOBALDATA) return("DpchAppWdbeNavGlobalData");
	if (ix == DPCHAPPWDBENAVGLOBALDO) return("DpchAppWdbeNavGlobalDo");
	if (ix == DPCHAPPWDBENAVPREDO) return("DpchAppWdbeNavPreDo");
	if (ix == DPCHAPPWDBEPINAPARDATA) return("DpchAppWdbePinAParData");
	if (ix == DPCHAPPWDBEPINAPARDO) return("DpchAppWdbePinAParDo");
	if (ix == DPCHAPPWDBEPINDETAILDATA) return("DpchAppWdbePinDetailData");
	if (ix == DPCHAPPWDBEPINDETAILDO) return("DpchAppWdbePinDetailDo");
	if (ix == DPCHAPPWDBEPINDO) return("DpchAppWdbePinDo");
	if (ix == DPCHAPPWDBEPINLISTDATA) return("DpchAppWdbePinListData");
	if (ix == DPCHAPPWDBEPINLISTDO) return("DpchAppWdbePinListDo");
	if (ix == DPCHAPPWDBEPINRECDO) return("DpchAppWdbePinRecDo");
	if (ix == DPCHAPPWDBEPPHAPARDATA) return("DpchAppWdbePphAParData");
	if (ix == DPCHAPPWDBEPPHAPARDO) return("DpchAppWdbePphAParDo");
	if (ix == DPCHAPPWDBEPPHDETAILDATA) return("DpchAppWdbePphDetailData");
	if (ix == DPCHAPPWDBEPPHDETAILDO) return("DpchAppWdbePphDetailDo");
	if (ix == DPCHAPPWDBEPPHDO) return("DpchAppWdbePphDo");
	if (ix == DPCHAPPWDBEPPHLISTDATA) return("DpchAppWdbePphListData");
	if (ix == DPCHAPPWDBEPPHLISTDO) return("DpchAppWdbePphListDo");
	if (ix == DPCHAPPWDBEPPHRECDO) return("DpchAppWdbePphRecDo");
	if (ix == DPCHAPPWDBEPRCDETAILDATA) return("DpchAppWdbePrcDetailData");
	if (ix == DPCHAPPWDBEPRCDETAILDO) return("DpchAppWdbePrcDetailDo");
	if (ix == DPCHAPPWDBEPRCDO) return("DpchAppWdbePrcDo");
	if (ix == DPCHAPPWDBEPRCFSMFSM1NFSMSTATEDATA) return("DpchAppWdbePrcFsmFsm1NFsmstateData");
	if (ix == DPCHAPPWDBEPRCFSMFSM1NFSMSTATEDO) return("DpchAppWdbePrcFsmFsm1NFsmstateDo");
	if (ix == DPCHAPPWDBEPRCKHDLTYPEDATA) return("DpchAppWdbePrcKHdltypeData");
	if (ix == DPCHAPPWDBEPRCKHDLTYPEDO) return("DpchAppWdbePrcKHdltypeDo");
	if (ix == DPCHAPPWDBEPRCLISTDATA) return("DpchAppWdbePrcListData");
	if (ix == DPCHAPPWDBEPRCLISTDO) return("DpchAppWdbePrcListDo");
	if (ix == DPCHAPPWDBEPRCMGE1NSIGNALDATA) return("DpchAppWdbePrcMge1NSignalData");
	if (ix == DPCHAPPWDBEPRCMGE1NSIGNALDO) return("DpchAppWdbePrcMge1NSignalDo");
	if (ix == DPCHAPPWDBEPRCPRC1NVARIABLEDATA) return("DpchAppWdbePrcPrc1NVariableData");
	if (ix == DPCHAPPWDBEPRCPRC1NVARIABLEDO) return("DpchAppWdbePrcPrc1NVariableDo");
	if (ix == DPCHAPPWDBEPRCRECDO) return("DpchAppWdbePrcRecDo");
	if (ix == DPCHAPPWDBEPRJ1NVERSIONDATA) return("DpchAppWdbePrj1NVersionData");
	if (ix == DPCHAPPWDBEPRJ1NVERSIONDO) return("DpchAppWdbePrj1NVersionDo");
	if (ix == DPCHAPPWDBEPRJDETAILDATA) return("DpchAppWdbePrjDetailData");
	if (ix == DPCHAPPWDBEPRJDETAILDO) return("DpchAppWdbePrjDetailDo");
	if (ix == DPCHAPPWDBEPRJDO) return("DpchAppWdbePrjDo");
	if (ix == DPCHAPPWDBEPRJLISTDATA) return("DpchAppWdbePrjListData");
	if (ix == DPCHAPPWDBEPRJLISTDO) return("DpchAppWdbePrjListDo");
	if (ix == DPCHAPPWDBEPRJMNPERSONDATA) return("DpchAppWdbePrjMNPersonData");
	if (ix == DPCHAPPWDBEPRJMNPERSONDO) return("DpchAppWdbePrjMNPersonDo");
	if (ix == DPCHAPPWDBEPRJRECDO) return("DpchAppWdbePrjRecDo");
	if (ix == DPCHAPPWDBEPRSADETAILDATA) return("DpchAppWdbePrsADetailData");
	if (ix == DPCHAPPWDBEPRSADETAILDO) return("DpchAppWdbePrsADetailDo");
	if (ix == DPCHAPPWDBEPRSDETAILDATA) return("DpchAppWdbePrsDetailData");
	if (ix == DPCHAPPWDBEPRSDETAILDO) return("DpchAppWdbePrsDetailDo");
	if (ix == DPCHAPPWDBEPRSDO) return("DpchAppWdbePrsDo");
	if (ix == DPCHAPPWDBEPRSLISTDATA) return("DpchAppWdbePrsListData");
	if (ix == DPCHAPPWDBEPRSLISTDO) return("DpchAppWdbePrsListDo");
	if (ix == DPCHAPPWDBEPRSMNCOREPROJECTDATA) return("DpchAppWdbePrsMNCoreprojectData");
	if (ix == DPCHAPPWDBEPRSMNCOREPROJECTDO) return("DpchAppWdbePrsMNCoreprojectDo");
	if (ix == DPCHAPPWDBEPRSMNPROJECTDATA) return("DpchAppWdbePrsMNProjectData");
	if (ix == DPCHAPPWDBEPRSMNPROJECTDO) return("DpchAppWdbePrsMNProjectDo");
	if (ix == DPCHAPPWDBEPRSRECDO) return("DpchAppWdbePrsRecDo");
	if (ix == DPCHAPPWDBEPRTDETAILDATA) return("DpchAppWdbePrtDetailData");
	if (ix == DPCHAPPWDBEPRTDETAILDO) return("DpchAppWdbePrtDetailDo");
	if (ix == DPCHAPPWDBEPRTDO) return("DpchAppWdbePrtDo");
	if (ix == DPCHAPPWDBEPRTLISTDATA) return("DpchAppWdbePrtListData");
	if (ix == DPCHAPPWDBEPRTLISTDO) return("DpchAppWdbePrtListDo");
	if (ix == DPCHAPPWDBEPRTRECDO) return("DpchAppWdbePrtRecDo");
	if (ix == DPCHAPPWDBERESUME) return("DpchAppWdbeResume");
	if (ix == DPCHAPPWDBERLSDETAILDATA) return("DpchAppWdbeRlsDetailData");
	if (ix == DPCHAPPWDBERLSDETAILDO) return("DpchAppWdbeRlsDetailDo");
	if (ix == DPCHAPPWDBERLSDO) return("DpchAppWdbeRlsDo");
	if (ix == DPCHAPPWDBERLSLISTDATA) return("DpchAppWdbeRlsListData");
	if (ix == DPCHAPPWDBERLSLISTDO) return("DpchAppWdbeRlsListDo");
	if (ix == DPCHAPPWDBERLSRECDO) return("DpchAppWdbeRlsRecDo");
	if (ix == DPCHAPPWDBESIGDETAILDATA) return("DpchAppWdbeSigDetailData");
	if (ix == DPCHAPPWDBESIGDETAILDO) return("DpchAppWdbeSigDetailDo");
	if (ix == DPCHAPPWDBESIGDO) return("DpchAppWdbeSigDo");
	if (ix == DPCHAPPWDBESIGLISTDATA) return("DpchAppWdbeSigListData");
	if (ix == DPCHAPPWDBESIGLISTDO) return("DpchAppWdbeSigListDo");
	if (ix == DPCHAPPWDBESIGRECDO) return("DpchAppWdbeSigRecDo");
	if (ix == DPCHAPPWDBESIL1NBANKDATA) return("DpchAppWdbeSil1NBankData");
	if (ix == DPCHAPPWDBESIL1NBANKDO) return("DpchAppWdbeSil1NBankDo");
	if (ix == DPCHAPPWDBESIL1NPERIPHERALDATA) return("DpchAppWdbeSil1NPeripheralData");
	if (ix == DPCHAPPWDBESIL1NPERIPHERALDO) return("DpchAppWdbeSil1NPeripheralDo");
	if (ix == DPCHAPPWDBESIL1NTARGETDATA) return("DpchAppWdbeSil1NTargetData");
	if (ix == DPCHAPPWDBESIL1NTARGETDO) return("DpchAppWdbeSil1NTargetDo");
	if (ix == DPCHAPPWDBESILDETAILDATA) return("DpchAppWdbeSilDetailData");
	if (ix == DPCHAPPWDBESILDETAILDO) return("DpchAppWdbeSilDetailDo");
	if (ix == DPCHAPPWDBESILDO) return("DpchAppWdbeSilDo");
	if (ix == DPCHAPPWDBESILFWD1NCONTROLLERDATA) return("DpchAppWdbeSilFwd1NControllerData");
	if (ix == DPCHAPPWDBESILFWD1NCONTROLLERDO) return("DpchAppWdbeSilFwd1NControllerDo");
	if (ix == DPCHAPPWDBESILHK1NMODULEDATA) return("DpchAppWdbeSilHk1NModuleData");
	if (ix == DPCHAPPWDBESILHK1NMODULEDO) return("DpchAppWdbeSilHk1NModuleDo");
	if (ix == DPCHAPPWDBESILHK1NVECTORDATA) return("DpchAppWdbeSilHk1NVectorData");
	if (ix == DPCHAPPWDBESILHK1NVECTORDO) return("DpchAppWdbeSilHk1NVectorDo");
	if (ix == DPCHAPPWDBESILLISTDATA) return("DpchAppWdbeSilListData");
	if (ix == DPCHAPPWDBESILLISTDO) return("DpchAppWdbeSilListDo");
	if (ix == DPCHAPPWDBESILRECDO) return("DpchAppWdbeSilRecDo");
	if (ix == DPCHAPPWDBESILREF1NCOMMANDDATA) return("DpchAppWdbeSilRef1NCommandData");
	if (ix == DPCHAPPWDBESILREF1NCOMMANDDO) return("DpchAppWdbeSilRef1NCommandDo");
	if (ix == DPCHAPPWDBESILREF1NERRORDATA) return("DpchAppWdbeSilRef1NErrorData");
	if (ix == DPCHAPPWDBESILREF1NERRORDO) return("DpchAppWdbeSilRef1NErrorDo");
	if (ix == DPCHAPPWDBESILSIL1NUNITDATA) return("DpchAppWdbeSilSil1NUnitData");
	if (ix == DPCHAPPWDBESILSIL1NUNITDO) return("DpchAppWdbeSilSil1NUnitDo");
	if (ix == DPCHAPPWDBESYSDETAILDATA) return("DpchAppWdbeSysDetailData");
	if (ix == DPCHAPPWDBESYSDETAILDO) return("DpchAppWdbeSysDetailDo");
	if (ix == DPCHAPPWDBESYSDO) return("DpchAppWdbeSysDo");
	if (ix == DPCHAPPWDBESYSHK1NVECTORDATA) return("DpchAppWdbeSysHk1NVectorData");
	if (ix == DPCHAPPWDBESYSHK1NVECTORDO) return("DpchAppWdbeSysHk1NVectorDo");
	if (ix == DPCHAPPWDBESYSLISTDATA) return("DpchAppWdbeSysListData");
	if (ix == DPCHAPPWDBESYSLISTDO) return("DpchAppWdbeSysListDo");
	if (ix == DPCHAPPWDBESYSRECDO) return("DpchAppWdbeSysRecDo");
	if (ix == DPCHAPPWDBESYSSYS1NTARGETDATA) return("DpchAppWdbeSysSys1NTargetData");
	if (ix == DPCHAPPWDBESYSSYS1NTARGETDO) return("DpchAppWdbeSysSys1NTargetDo");
	if (ix == DPCHAPPWDBETRGDETAILDATA) return("DpchAppWdbeTrgDetailData");
	if (ix == DPCHAPPWDBETRGDETAILDO) return("DpchAppWdbeTrgDetailDo");
	if (ix == DPCHAPPWDBETRGDO) return("DpchAppWdbeTrgDo");
	if (ix == DPCHAPPWDBETRGLISTDATA) return("DpchAppWdbeTrgListData");
	if (ix == DPCHAPPWDBETRGLISTDO) return("DpchAppWdbeTrgListDo");
	if (ix == DPCHAPPWDBETRGRECDO) return("DpchAppWdbeTrgRecDo");
	if (ix == DPCHAPPWDBEUNT1NBANKDATA) return("DpchAppWdbeUnt1NBankData");
	if (ix == DPCHAPPWDBEUNT1NBANKDO) return("DpchAppWdbeUnt1NBankDo");
	if (ix == DPCHAPPWDBEUNT1NPERIPHERALDATA) return("DpchAppWdbeUnt1NPeripheralData");
	if (ix == DPCHAPPWDBEUNT1NPERIPHERALDO) return("DpchAppWdbeUnt1NPeripheralDo");
	if (ix == DPCHAPPWDBEUNT1NTARGETDATA) return("DpchAppWdbeUnt1NTargetData");
	if (ix == DPCHAPPWDBEUNT1NTARGETDO) return("DpchAppWdbeUnt1NTargetDo");
	if (ix == DPCHAPPWDBEUNTDETAILDATA) return("DpchAppWdbeUntDetailData");
	if (ix == DPCHAPPWDBEUNTDETAILDO) return("DpchAppWdbeUntDetailDo");
	if (ix == DPCHAPPWDBEUNTDO) return("DpchAppWdbeUntDo");
	if (ix == DPCHAPPWDBEUNTFWD1NCONTROLLERDATA) return("DpchAppWdbeUntFwd1NControllerData");
	if (ix == DPCHAPPWDBEUNTFWD1NCONTROLLERDO) return("DpchAppWdbeUntFwd1NControllerDo");
	if (ix == DPCHAPPWDBEUNTHK1NMODULEDATA) return("DpchAppWdbeUntHk1NModuleData");
	if (ix == DPCHAPPWDBEUNTHK1NMODULEDO) return("DpchAppWdbeUntHk1NModuleDo");
	if (ix == DPCHAPPWDBEUNTHK1NVECTORDATA) return("DpchAppWdbeUntHk1NVectorData");
	if (ix == DPCHAPPWDBEUNTHK1NVECTORDO) return("DpchAppWdbeUntHk1NVectorDo");
	if (ix == DPCHAPPWDBEUNTLISTDATA) return("DpchAppWdbeUntListData");
	if (ix == DPCHAPPWDBEUNTLISTDO) return("DpchAppWdbeUntListDo");
	if (ix == DPCHAPPWDBEUNTRECDO) return("DpchAppWdbeUntRecDo");
	if (ix == DPCHAPPWDBEUNTREF1NCOMMANDDATA) return("DpchAppWdbeUntRef1NCommandData");
	if (ix == DPCHAPPWDBEUNTREF1NCOMMANDDO) return("DpchAppWdbeUntRef1NCommandDo");
	if (ix == DPCHAPPWDBEUNTREF1NERRORDATA) return("DpchAppWdbeUntRef1NErrorData");
	if (ix == DPCHAPPWDBEUNTREF1NERRORDO) return("DpchAppWdbeUntRef1NErrorDo");
	if (ix == DPCHAPPWDBEUNTSIL1NUNITDATA) return("DpchAppWdbeUntSil1NUnitData");
	if (ix == DPCHAPPWDBEUNTSIL1NUNITDO) return("DpchAppWdbeUntSil1NUnitDo");
	if (ix == DPCHAPPWDBEUSGAACCESSDATA) return("DpchAppWdbeUsgAAccessData");
	if (ix == DPCHAPPWDBEUSGAACCESSDO) return("DpchAppWdbeUsgAAccessDo");
	if (ix == DPCHAPPWDBEUSGDETAILDATA) return("DpchAppWdbeUsgDetailData");
	if (ix == DPCHAPPWDBEUSGDETAILDO) return("DpchAppWdbeUsgDetailDo");
	if (ix == DPCHAPPWDBEUSGDO) return("DpchAppWdbeUsgDo");
	if (ix == DPCHAPPWDBEUSGLISTDATA) return("DpchAppWdbeUsgListData");
	if (ix == DPCHAPPWDBEUSGLISTDO) return("DpchAppWdbeUsgListDo");
	if (ix == DPCHAPPWDBEUSGMNUSERDATA) return("DpchAppWdbeUsgMNUserData");
	if (ix == DPCHAPPWDBEUSGMNUSERDO) return("DpchAppWdbeUsgMNUserDo");
	if (ix == DPCHAPPWDBEUSGRECDO) return("DpchAppWdbeUsgRecDo");
	if (ix == DPCHAPPWDBEUSR1NSESSIONDATA) return("DpchAppWdbeUsr1NSessionData");
	if (ix == DPCHAPPWDBEUSR1NSESSIONDO) return("DpchAppWdbeUsr1NSessionDo");
	if (ix == DPCHAPPWDBEUSRAACCESSDATA) return("DpchAppWdbeUsrAAccessData");
	if (ix == DPCHAPPWDBEUSRAACCESSDO) return("DpchAppWdbeUsrAAccessDo");
	if (ix == DPCHAPPWDBEUSRDETAILDATA) return("DpchAppWdbeUsrDetailData");
	if (ix == DPCHAPPWDBEUSRDETAILDO) return("DpchAppWdbeUsrDetailDo");
	if (ix == DPCHAPPWDBEUSRDO) return("DpchAppWdbeUsrDo");
	if (ix == DPCHAPPWDBEUSRLISTDATA) return("DpchAppWdbeUsrListData");
	if (ix == DPCHAPPWDBEUSRLISTDO) return("DpchAppWdbeUsrListDo");
	if (ix == DPCHAPPWDBEUSRMNUSERGROUPDATA) return("DpchAppWdbeUsrMNUsergroupData");
	if (ix == DPCHAPPWDBEUSRMNUSERGROUPDO) return("DpchAppWdbeUsrMNUsergroupDo");
	if (ix == DPCHAPPWDBEUSRRECDO) return("DpchAppWdbeUsrRecDo");
	if (ix == DPCHAPPWDBEUTLDO) return("DpchAppWdbeUtlDo");
	if (ix == DPCHAPPWDBEVARDETAILDATA) return("DpchAppWdbeVarDetailData");
	if (ix == DPCHAPPWDBEVARDETAILDO) return("DpchAppWdbeVarDetailDo");
	if (ix == DPCHAPPWDBEVARDO) return("DpchAppWdbeVarDo");
	if (ix == DPCHAPPWDBEVARLISTDATA) return("DpchAppWdbeVarListData");
	if (ix == DPCHAPPWDBEVARLISTDO) return("DpchAppWdbeVarListDo");
	if (ix == DPCHAPPWDBEVARRECDO) return("DpchAppWdbeVarRecDo");
	if (ix == DPCHAPPWDBEVECDETAILDATA) return("DpchAppWdbeVecDetailData");
	if (ix == DPCHAPPWDBEVECDETAILDO) return("DpchAppWdbeVecDetailDo");
	if (ix == DPCHAPPWDBEVECDO) return("DpchAppWdbeVecDo");
	if (ix == DPCHAPPWDBEVECLISTDATA) return("DpchAppWdbeVecListData");
	if (ix == DPCHAPPWDBEVECLISTDO) return("DpchAppWdbeVecListDo");
	if (ix == DPCHAPPWDBEVECRECDO) return("DpchAppWdbeVecRecDo");
	if (ix == DPCHAPPWDBEVECVEC1NVECTORITEMDATA) return("DpchAppWdbeVecVec1NVectoritemData");
	if (ix == DPCHAPPWDBEVECVEC1NVECTORITEMDO) return("DpchAppWdbeVecVec1NVectoritemDo");
	if (ix == DPCHAPPWDBEVER1NRELEASEDATA) return("DpchAppWdbeVer1NReleaseData");
	if (ix == DPCHAPPWDBEVER1NRELEASEDO) return("DpchAppWdbeVer1NReleaseDo");
	if (ix == DPCHAPPWDBEVER1NSYSTEMDATA) return("DpchAppWdbeVer1NSystemData");
	if (ix == DPCHAPPWDBEVER1NSYSTEMDO) return("DpchAppWdbeVer1NSystemDo");
	if (ix == DPCHAPPWDBEVER1NUNITDATA) return("DpchAppWdbeVer1NUnitData");
	if (ix == DPCHAPPWDBEVER1NUNITDO) return("DpchAppWdbeVer1NUnitDo");
	if (ix == DPCHAPPWDBEVERBVR1NVERSIONDATA) return("DpchAppWdbeVerBvr1NVersionData");
	if (ix == DPCHAPPWDBEVERBVR1NVERSIONDO) return("DpchAppWdbeVerBvr1NVersionDo");
	if (ix == DPCHAPPWDBEVERDETAILDATA) return("DpchAppWdbeVerDetailData");
	if (ix == DPCHAPPWDBEVERDETAILDO) return("DpchAppWdbeVerDetailDo");
	if (ix == DPCHAPPWDBEVERDO) return("DpchAppWdbeVerDo");
	if (ix == DPCHAPPWDBEVERLISTDATA) return("DpchAppWdbeVerListData");
	if (ix == DPCHAPPWDBEVERLISTDO) return("DpchAppWdbeVerListDo");
	if (ix == DPCHAPPWDBEVERMNLIBRARYDATA) return("DpchAppWdbeVerMNLibraryData");
	if (ix == DPCHAPPWDBEVERMNLIBRARYDO) return("DpchAppWdbeVerMNLibraryDo");
	if (ix == DPCHAPPWDBEVERRECDO) return("DpchAppWdbeVerRecDo");
	if (ix == DPCHAPPWDBEVERREF1NFILEDATA) return("DpchAppWdbeVerRef1NFileData");
	if (ix == DPCHAPPWDBEVERREF1NFILEDO) return("DpchAppWdbeVerRef1NFileDo");
	if (ix == DPCHAPPWDBEVITDETAILDATA) return("DpchAppWdbeVitDetailData");
	if (ix == DPCHAPPWDBEVITDETAILDO) return("DpchAppWdbeVitDetailDo");
	if (ix == DPCHAPPWDBEVITDO) return("DpchAppWdbeVitDo");
	if (ix == DPCHAPPWDBEVITLISTDATA) return("DpchAppWdbeVitListData");
	if (ix == DPCHAPPWDBEVITLISTDO) return("DpchAppWdbeVitListDo");
	if (ix == DPCHAPPWDBEVITRECDO) return("DpchAppWdbeVitRecDo");

	return("");
};

