# file Makefile.inc
# make file paths for Wdbe operation daemon, release wdbeopd2_awsubt
# author Alexander Wirthmueller
# date created: 11 Jul 2020
# modified: 11 Jul 2020

SRCROOT = /home/ubuntu/src
LIBROOT = /home/ubuntu/lib
BINROOT = /home/ubuntu/bin

